Marconi Firmware: Core/Src/gnss.c File Reference
gnss.c File Reference
#include "main.h"
#include "gnss.h"
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <math.h>
#include <stdbool.h>
Functions
void gnss_begin_dma ()
void gnss_dma_handling (UART_HandleTypeDef *huart, uint16_t data_len)
Main GNSS data processing callback, triggered by UART Idle Line DMA.
void gnss_enable_agps ()
void gnss_config ()
Configures the TESEO module for high-speed operation and message filtering.
int gnss_ping ()
Pings the module to check for communication.
void gnss_init ()
Initializes the GNSS module.
void gnss_save ()
Saves the current configuration to the TESEO's non-volatile memory.
void gnss_reset ()
Performs a software reset of the TESEO module.
char calc_checksum (char *buffer)
void hex_checksum (char *out, char *buffer)
void set_checksum (char *buffer, size_t len)
int vbuild_nmea (char *out, size_t size, const NMEA_CMD *cmd, va_list args)
int build_nmea (char *out, size_t size, const NMEA_CMD *cmd,...)
Builds a complete, checksummed NMEA sentence in a buffer.
int send_nmea (const NMEA_CMD *cmd,...)
Builds and transmits an NMEA sentence via blocking UART.
int check_nmea (char *buffer, size_t max_size, const NMEA_CMD *cmd)
Validates an NMEA sentence string.
int vparse_nmea (char *buffer, size_t max_size, const NMEA_CMD *cmd, va_list out)
int parse_nmea (char *buffer, size_t max_size, const NMEA_CMD *cmd,...)
Parses the data fields from a validated NMEA sentence.
Variables
const NMEA_CMD PSTMGETSWVER = {"PSTMGETSWVER", ",%d"}
Command: Get firmware version.
const NMEA_CMD PSTMNMEAREQUEST = {"PSTMNMEAREQUEST", ",%08x,%08x"}
Command: Request a specific set of NMEA messages.
const NMEA_CMD PSTMSETPAR = {"PSTMSETPAR", ",%d%d,%s"}
Command: Set a configuration parameter in volatile memory.
const NMEA_CMD PSTMCFGMSGL = {"PSTMCFGMSGL", ",%d,%d,%s,%s"}
Command: Set the message list for a specific interface.
const NMEA_CMD PSTMSAVEPAR = {"PSTMSAVEPAR", ""}
Command: Save configuration parameters to NVM.
const NMEA_CMD PSTMSRR = {"PSTMSRR", ""}
Command: Perform a software reset of the module.
const NMEA_CMD PSTMGETAGPSSTATUS = {"PSTMGETAGPSSTATUS", ""}
const NMEA_CMD PSTMSTAGPSONOFF = {"PSTMSTAGPSONOFF", ",%d"}
Command: Set the AGPS mode (on/off).
const NMEA_CMD PSTMTPOLONOFFERROR = {"PSTMTPOLONOFFERROR",""}
const NMEA_CMD PSTMPV = {"PSTMPV", ",%2d%2d%2d.%3d,%2d%2d.%5d,%c,%3d%2d.%5d,%c,%d.%d,%c,%d.%d,%d.%d,%d.%d"}
Proprietary Position/Velocity data message.
char send_buf [NMEA_BUFFER_SIZE]
char recv_buf [DMA_GNSS_BUFFER_SIZE]
volatile float teseo_latitude = 0.0f
Latest valid latitude in decimal degrees.
volatile float teseo_longitude = 0.0f
Latest valid longitude in decimal degrees.
volatile float teseo_velocity_x = 0.0f
Latest valid velocity in the North direction (m/s).
volatile float teseo_velocity_y = 0.0f
Latest valid velocity in the East direction (m/s).
volatile float teseo_velocity_z = 0.0f
Latest valid velocity in the Vertical direction (m/s).
float fix_quality = 0.0f
float nb_satellites = 0.0f
float gps_velocity = 0.0f
Calculated 3D speed magnitude (m/s).
float gps_velocity_last = 0.0f
bool is_new_velocity_valid = true
Function Documentation
calc_checksum()
char calc_checksum (char * buffer)
Definition at line 332 of file gnss.c.
{
    unsigned char res = 0; // 0 ^ A = A
    for(int i = 0; buffer[i] != '\0'; i++) {
        if(buffer[i] == '$') {
            res = 0;
            continue;
        } else if(buffer[i] == '*')
            break;
        res ^= buffer[i];
    }
    return res;
}
Referenced by check_nmea(), and hex_checksum().
gnss_begin_dma()
void gnss_begin_dma ()
Definition at line 324 of file gnss.c.
                      {
    HAL_StatusTypeDef status = HAL_UARTEx_ReceiveToIdle_DMA(&huart5, (uint8_t*) recv_buf, DMA_GNSS_BUFFER_SIZE);
    if(status != HAL_OK ) {
        errno = EIO;
        return;
    }
}
References DMA_GNSS_BUFFER_SIZE, huart5, and recv_buf.
Referenced by gnss_dma_handling(), and gnss_init().
gnss_enable_agps()
void gnss_enable_agps ()
Definition at line 174 of file gnss.c.
{
    if(send_nmea(&PSTMSTAGPSONOFF, 1)) {
        // check errno for error type
        return;
    }
}
References PSTMSTAGPSONOFF, and send_nmea().
Referenced by gnss_config().
hex_checksum()
void hex_checksum (char * out, char * buffer)
Definition at line 348 of file gnss.c.
{
    sprintf(out, "%.2x", calc_checksum(buffer));
}
References calc_checksum().
Referenced by set_checksum().
set_checksum()
void set_checksum (char * buffer, size_t len)
Definition at line 352 of file gnss.c.
{
    hex_checksum(&buffer[len - 4], buffer);
    buffer[len - 2] = '\r'; // remove \0 terminator added by hex_checksum
}
References hex_checksum().
Referenced by vbuild_nmea().
vbuild_nmea()
int vbuild_nmea (char * out, size_t size, const NMEA_CMD * cmd, va_list args)
Definition at line 357 of file gnss.c.
{
    int pos = 0;
    if((pos += snprintf(out + pos, size - pos, "$%s", cmd->name)) >= size)
        return pos;
    if((pos += vsnprintf(out + pos, size - pos, cmd->format, args)) >= size)
        return pos;
    if((pos += snprintf(out + pos, size - pos, "*FF\r\n")) >= size)
        return pos;
    set_checksum(out, pos);
    return pos;
}
References NMEA_CMD::format, NMEA_CMD::name, and set_checksum().
Referenced by build_nmea(), and send_nmea().
vparse_nmea()
int vparse_nmea (char * buffer, size_t max_size, const NMEA_CMD * cmd, va_list out)
Definition at line 436 of file gnss.c.
{
    int res;
    if((res = check_nmea(buffer, max_size, cmd)) != NMEA_VALID)
        return res;
    return vsscanf(buffer + 1 + strlen(cmd->name), cmd->format, out);
}
References check_nmea(), NMEA_CMD::format, NMEA_CMD::name, and NMEA_VALID.
Referenced by parse_nmea().
Variable Documentation
fix_quality
float fix_quality = 0.0f
Definition at line 43 of file gnss.c.
Referenced by gnss_dma_handling().
gps_velocity_last
float gps_velocity_last = 0.0f
Definition at line 47 of file gnss.c.
is_new_velocity_valid
bool is_new_velocity_valid = true
Definition at line 48 of file gnss.c.
nb_satellites
float nb_satellites = 0.0f
Definition at line 44 of file gnss.c.
Referenced by gnss_dma_handling().
PSTMGETAGPSSTATUS
const NMEA_CMD PSTMGETAGPSSTATUS = {"PSTMGETAGPSSTATUS", ""}
Definition at line 27 of file gnss.c.
PSTMTPOLONOFFERROR
const NMEA_CMD PSTMTPOLONOFFERROR = {"PSTMTPOLONOFFERROR",""}
Definition at line 31 of file gnss.c.
recv_buf
char recv_buf[DMA_GNSS_BUFFER_SIZE]
Definition at line 36 of file gnss.c.
Referenced by gnss_begin_dma(), gnss_config(), gnss_dma_handling(), and gnss_init().
send_buf
char send_buf[NMEA_BUFFER_SIZE]
Definition at line 35 of file gnss.c.
Referenced by gnss_config(), gnss_init(), and send_nmea().