Marconi Firmware: GNSS Driver Functions
GNSS Driver Functions
GNSS Positioning
Public API for initializing, configuring, and parsing data from the GNSS module.
Functions
void gnss_dma_handling (UART_HandleTypeDef *huart, uint16_t data_len)
Main GNSS data processing callback, triggered by UART Idle Line DMA.
int build_nmea (char *out, size_t size, const NMEA_CMD *cmd,...)
Builds a complete, checksummed NMEA sentence in a buffer.
int send_nmea (const NMEA_CMD *cmd,...)
Builds and transmits an NMEA sentence via blocking UART.
int check_nmea (char *buffer, size_t max_size, const NMEA_CMD *cmd)
Validates an NMEA sentence string.
int parse_nmea (char *buffer, size_t max_size, const NMEA_CMD *cmd,...)
Parses the data fields from a validated NMEA sentence.
void gnss_init ()
Initializes the GNSS module.
void gnss_config ()
Configures the TESEO module for high-speed operation and message filtering.
int gnss_ping ()
Pings the module to check for communication.
void gnss_save ()
Saves the current configuration to the TESEO's non-volatile memory.
void gnss_reset ()
Performs a software reset of the TESEO module.
Detailed Description
Public API for initializing, configuring, and parsing data from the GNSS module.
Function Documentation
build_nmea()
int build_nmea (char * out, size_t size, const NMEA_CMD * cmd, ...)
Builds a complete, checksummed NMEA sentence in a buffer.
Parameters
out Pointer to the output character buffer.
size Size of the output buffer.
cmd Pointer to the NMEA_CMD structure to use.
... Variadic arguments matching the cmd->format string.
Returns
The total number of bytes written to the buffer, or -1 on error.
Definition at line 374 of file gnss.c.
{
    va_list args;
    va_start(args, cmd);
    int pos = vbuild_nmea(out, size, cmd, args);
    va_end(args);
    return pos;
}
References vbuild_nmea().
check_nmea()
int check_nmea (char * buffer, size_t max_size, const NMEA_CMD * cmd)
Validates an NMEA sentence string.
Checks for '$', correct command name (if cmd is not NULL), and a valid checksum.
Parameters
buffer Pointer to the string buffer containing the NMEA sentence.
max_size The maximum size to search within the buffer.
cmd (Optional) The expected NMEA command to check against.
Returns
A validation code (e.g., NMEA_VALID, NMEA_CHECKSUM).
Definition at line 403 of file gnss.c.
{
    if(buffer[0] != '$')
        return NMEA_INVALID; // Not an NMEA sentence
    if(cmd != NULL) {
        if(strncmp(buffer + 1, cmd->name, strlen(cmd->name)) != 0)
            return NMEA_UNEXPECTED; // Not the expected command
        // Find end of the sentence
        // Points at the \n character
        char* end = memchr(buffer+1, '\n', max_size);
        // end - buffer gives the length of the string.
        // strlen(cmd->name) gets optimized out by the compiler because
        // it is a const char*, aka string literal.
        // must have at minimum 6 characters + name: %name*FF\r\n
        if(end == NULL){
            return NMEA_INVALID;
        }
        if((end - buffer) < strlen(cmd->name)+6)
            return NMEA_INVALID; // Not enough data to check checksum
        long checksum = strtol(&end[-3], NULL, 16); // Provided
        long calc = calc_checksum(buffer);          // Calculated
        if(checksum != calc)
            return NMEA_CHECKSUM; // Checksum mismatch
    }
    return NMEA_VALID;
}
References calc_checksum(), NMEA_CMD::name, NMEA_CHECKSUM, NMEA_INVALID, NMEA_UNEXPECTED, and NMEA_VALID.
Referenced by gnss_dma_handling(), and vparse_nmea().
gnss_config()
void gnss_config ()
Configures the TESEO module for high-speed operation and message filtering.
Attempts to set the module baud rate to 921600, re-initializes the host UART, pings the module, and sets the desired NMEA message list (to output only $PSTMPV) and enables AGPS.
Teseo-LIV3F CONFIGURATION ROUTINE Primarily used to set which messages we want to receive from the module over UART
This routine needs to be applied only once per module, but running it multiple times is not harmful.
AFTER APPLYING THIS CONFIGURATION, THE MODULE MUST BE RESET FOR IT TO APPLY.
Definition at line 192 of file gnss.c.
                   {
    //first of all, make sure the baud rate is correct
    // set UART to 921600 baud
    // if it's already set at high speed, the teseo will receive garbage but that's ok
    if(send_nmea(&PSTMSETPAR, TESEO_CFG_NVM, TESEO_CDB_BAUD, TESEO_921600_BAUD)) {
        return;
    }
    // TODO: reenable resets
    gnss_save();
    gnss_reset();
    // Switch STM32 UART to high speed
    HAL_UART_DeInit(&U_GNSS);
    U_GNSS.Init.BaudRate = 921600;
    if(HAL_UART_Init(&U_GNSS) != HAL_OK) {
        // TODO: do something
        return;
    }
    HAL_Delay(1000);
    if(!gnss_ping()) {
        // uh oh
        // TODO: big trouble
        return;
    }
    // baud rate set, now select messages
    if(send_nmea(&PSTMCFGMSGL, TESEO_MSGLIST_UART, 1, "00000002", "00000001")) {
        // check errno for error type
        return;
    }
    send_buf[0] ='\0';
    // Because changes only apply after reset,
    // we need to save the configuration in persistent memory
    gnss_save();
    gnss_reset();
    HAL_Delay(5000);
    send_buf[0] = '\0'; // clear buffer TEST
    uint32_t size = sizeof(send_buf);
    memset(send_buf,'\0',size);
    uint32_t size_2 = sizeof(recv_buf);
    memset(recv_buf,'\0',size_2);
    if(!gnss_ping()) {
        // uh oh
        // TODO: big trouble
        return;
    }
    gnss_enable_agps();
    //memset(recv_buf,'\0',size_2);
    //if(send_nmea(&PSTMGETAGPSSTATUS, 1)) {
            // check errno for error type
    //      return;
    //  }
    //HAL_UART_Receive(&huart5,(uint8_t*)recv_buf,200000,100000);
    // we reset twice instead of setting everything at once because in case the teseo is already set up
    // at the correct baud rate the only thing we transmit at the wrong rate is the baud rate set message
    // itself, which is fine to lose if the teseo is already set up.
    // We have to make sure though that in case the Teseo IS NOT at the high speed baud rate,
    // that it is set before sending any other messages, otherwise they will be lost too.
}
References gnss_enable_agps(), gnss_ping(), gnss_reset(), gnss_save(), PSTMCFGMSGL, PSTMSETPAR, recv_buf, send_buf, send_nmea(), TESEO_921600_BAUD, TESEO_CDB_BAUD, TESEO_CFG_NVM, TESEO_MSGLIST_UART, and U_GNSS.
Referenced by gnss_init().
gnss_dma_handling()
void gnss_dma_handling (UART_HandleTypeDef * huart, uint16_t data_len)
Main GNSS data processing callback, triggered by UART Idle Line DMA.
This function is called from the UART interrupt. It copies and re-aligns the data from the circular DMA buffer, then iterates through it to find and parse valid $PSTMPV messages. Parsed data is used to update the global teseo_... variables.
Parameters
huart The UART handle that triggered the interrupt.
data_len The number of bytes received since the last idle event.
Definition at line 52 of file gnss.c.
{
    recv_buf[data_len] = '\0';
    for(int i = 0; i < data_len; i++) {
        if(check_nmea(recv_buf + i, data_len - i, NULL) != NMEA_VALID) {
            // Not a valid NMEA sentence, skip to next '$'
            continue;
        }
        PSTMPV_Data data;
        memset(&data, 0, sizeof(PSTMPV_Data));
        int status;
            if((status = parse_nmea(recv_buf + i, data_len - i, &PSTMPV,
                    &data.hour, &data.minute, &data.second, &data.ms,
                    &data.lat_deg, &data.lat_min, &data.lat_part, &data.lat_dir,
                    &data.lon_deg, &data.lon_min, &data.lon_part, &data.lon_dir,
                    &data.altitude, &data.altitude_dec, &data.altitude_unit,
                    &data.vel_n, &data.vel_n_dec,
                    &data.vel_e, &data.vel_e_dec,
                    &data.vel_v, &data.vel_v_dec))) {
                // found
                if(data.lat_deg != 0) {
                    teseo_latitude = data.lat_deg*100 + (data.lat_min) + (data.lat_part / 100000.0f);
                    if(data.lat_dir == 'S')
                        teseo_latitude = -teseo_latitude;
                }
                if(data.lon_deg) {
                    teseo_longitude = data.lon_deg*100 + (data.lon_min) + (data.lon_part / 100000.0f);
                    if(data.lon_dir == 'W')
                        teseo_longitude = -teseo_longitude;
                }
                if (data.vel_n >= 0) {
                    teseo_velocity_x = data.vel_n + (data.vel_n_dec / 10.0f);
                } else {
                    // data.vel_n is already negative.
                    // data.vel_n_dec represents the positive fractional part.
                    teseo_velocity_x = data.vel_n - (data.vel_n_dec / 10.0f);
                }
                if (data.vel_e >= 0) {
                    teseo_velocity_y = data.vel_e + (data.vel_e_dec / 10.0f);
                } else {
                    // data.vel_n is already negative.
                    // data.vel_n_dec represents the positive fractional part.
                    teseo_velocity_y = data.vel_e - (data.vel_e_dec / 10.0f);
                }
                if (data.vel_v >= 0) {
                    teseo_velocity_z = data.vel_v + (data.vel_v_dec / 10.0f);
                } else {
                    // data.vel_n is already negative.
                    // data.vel_n_dec represents the positive fractional part.
                    teseo_velocity_z = data.vel_v - (data.vel_v_dec / 10.0f);
                }
                if (isnan(teseo_velocity_x) || isinf(teseo_velocity_x)
                        || isnan(teseo_velocity_y) || isinf(teseo_velocity_y)
                        || isnan(teseo_velocity_z) || isinf(teseo_velocity_z)) {
                    gps_velocity = -1;
                } else {
                    gps_velocity = sqrtf(
                            teseo_velocity_x * teseo_velocity_x +
                            teseo_velocity_y * teseo_velocity_y +
                            teseo_velocity_z * teseo_velocity_z);
                    if(isnan(gps_velocity)
                            || isinf(gps_velocity)
                            || gps_velocity == 0)
                        gps_velocity = -1.0;
                }
                if(gps_velocity != 0.0 && gps_velocity != -1.0){
                    HAL_GPIO_TogglePin(GPIO_LED3_GPIO_Port, GPIO_LED3_Pin);
                }
                break;
            } /* else {
                switch(status) {
                case NMEA_CHECKSUM:
                    ...
                case NMEA_UNEXPECTED:
                    ...
            } */
            if (strncmp((char *)recv_buf , "$GPGGA", 6) == 0){
                char *token;
                int field_index = 0;
                char *rest = (char *)recv_buf; // Pointer to the remaining part of the string
                // Tokenize the string by commas
                while ((token = strtok_r(rest, ",", &rest)))
                    {
                    switch (field_index)
{
                        case 6: // Vel_N is the 9th field (index 8)
                            fix_quality = atof(token);
                            if(fix_quality !=0.0){
                                HAL_GPIO_TogglePin(GPIO_LED2_GPIO_Port, GPIO_LED2_Pin);
                            }
                            break;
                        case 7:
                            nb_satellites = atof(token);
                            if(nb_satellites >0.0){
                                HAL_GPIO_TogglePin(GPIO_LED3_GPIO_Port, GPIO_LED3_Pin);
                            }
                            break;
                        }
                    field_index++;
                    }
            }
    }
    gnss_begin_dma();
}
References PSTMPV_Data::altitude, PSTMPV_Data::altitude_dec, PSTMPV_Data::altitude_unit, check_nmea(), fix_quality, gnss_begin_dma(), GPIO_LED2_GPIO_Port, GPIO_LED2_Pin, GPIO_LED3_GPIO_Port, GPIO_LED3_Pin, gps_velocity, PSTMPV_Data::hour, PSTMPV_Data::lat_deg, PSTMPV_Data::lat_dir, PSTMPV_Data::lat_min, PSTMPV_Data::lat_part, PSTMPV_Data::lon_deg, PSTMPV_Data::lon_dir, PSTMPV_Data::lon_min, PSTMPV_Data::lon_part, PSTMPV_Data::minute, PSTMPV_Data::ms, nb_satellites, NMEA_VALID, parse_nmea(), PSTMPV, recv_buf, PSTMPV_Data::second, teseo_latitude, teseo_longitude, teseo_velocity_x, teseo_velocity_y, teseo_velocity_z, PSTMPV_Data::vel_e, PSTMPV_Data::vel_e_dec, PSTMPV_Data::vel_n, PSTMPV_Data::vel_n_dec, PSTMPV_Data::vel_v, and PSTMPV_Data::vel_v_dec.
Referenced by HAL_UARTEx_RxEventCallback().
gnss_init()
void gnss_init ()
Initializes the GNSS module.
Runs the gnss_config routine, clears buffers, and starts the UART DMA reception (gnss_begin_dma).
Definition at line 297 of file gnss.c.
                 {
    gnss_config();
    memset(send_buf,'\0', NMEA_BUFFER_SIZE);
    memset(recv_buf, '\0', DMA_GNSS_BUFFER_SIZE);
    HAL_GPIO_TogglePin(GPIO_LED1_GPIO_Port, GPIO_LED1_Pin);
    gnss_begin_dma();
}
References DMA_GNSS_BUFFER_SIZE, gnss_begin_dma(), gnss_config(), GPIO_LED1_GPIO_Port, GPIO_LED1_Pin, NMEA_BUFFER_SIZE, recv_buf, and send_buf.
Referenced by main().
gnss_ping()
int gnss_ping ()
Pings the module to check for communication.
Sends a $PSTMGETSWVER command and waits for a $PSTMVER response.
Returns
1 on successful ping, 0 or negative on failure.
Definition at line 270 of file gnss.c.
                {
    int err;
    if((err = send_nmea(&PSTMGETSWVER, 12))) {
        return err;
    }
    char buf[8+1+2]; // $PSTMVER + '\0' + one extra character before and after
    buf[0] = '\0'; // check for overwrite
    HAL_StatusTypeDef d = HAL_UART_Receive(&U_GNSS, (unsigned char*) buf, 11, 1500);
    if(d != HAL_OK && buf[0] == '\0') {
        return -1;
    }
    buf[10] = '\0'; // null terminate
    for(int i = 1; buf[i] != '\0'; i++) {
        if(buf[i] != '$' && buf[i-1] == '$') {
            buf[i+7] = '\0';
            return strcmp(buf + i, "PSTMVER") == 0;
        }
    }
    return 0; // false
}
References PSTMGETSWVER, send_nmea(), and U_GNSS.
Referenced by gnss_config().
gnss_reset()
void gnss_reset ()
Performs a software reset of the TESEO module.
Sends the $PSTMSRR command.
Definition at line 315 of file gnss.c.
                  {
    if(send_nmea(&PSTMSRR)){
        // check errno for error type
        return;
    }
}
References PSTMSRR, and send_nmea().
Referenced by gnss_config().
gnss_save()
void gnss_save ()
Saves the current configuration to the TESEO's non-volatile memory.
Sends the $PSTMSAVEPAR command.
Definition at line 308 of file gnss.c.
                 {
    if(send_nmea(&PSTMSAVEPAR)) {
        // check errno for error type
        return;
    }
}
References PSTMSAVEPAR, and send_nmea().
Referenced by gnss_config().
parse_nmea()
int parse_nmea (char * buffer, size_t max_size, const NMEA_CMD * cmd, ...)
Parses the data fields from a validated NMEA sentence.
Uses vsscanf to extract data based on the cmd->format string.
Parameters
buffer Pointer to the NMEA sentence string.
max_size Maximum size of the buffer.
cmd The NMEA_CMD structure defining the expected format.
... Variadic output pointers (e.g., &data.hour) to store parsed values.
Returns
Result of vsscanf (number of fields parsed) or an error code.
Definition at line 445 of file gnss.c.
{
    va_list args;
    va_start(args, cmd);
    int res = vparse_nmea(buffer, max_size, cmd, args);
    va_end(args);
    return res;
}
References vparse_nmea().
Referenced by gnss_dma_handling().
send_nmea()
int send_nmea (const NMEA_CMD * cmd, ...)
Builds and transmits an NMEA sentence via blocking UART.
Uses an internal buffer (send_buf) to build the message.
Parameters
cmd Pointer to the NMEA_CMD structure to use.
... Variadic arguments matching the cmd->format string.
Returns
HAL_StatusTypeDef from the HAL_UART_Transmit call.
Definition at line 385 of file gnss.c.
{
    va_list args;
    va_start(args, cmd);
    if(vbuild_nmea(send_buf, NMEA_BUFFER_SIZE, cmd, args) >= NMEA_BUFFER_SIZE) {
        // buffer overflow
        errno = ENOBUFS;
        return -1;
    }
    HAL_StatusTypeDef res =
            HAL_UART_Transmit(&U_GNSS, (unsigned char*) send_buf, strlen(send_buf), 1000);
    va_end(args);
    return res;
}
References NMEA_BUFFER_SIZE, send_buf, U_GNSS, and vbuild_nmea().
Referenced by gnss_config(), gnss_enable_agps(), gnss_ping(), gnss_reset(), and gnss_save().