Marconi Firmware: E220 Driver Functions
E220 Driver Functions
System Core » Telemetry
Public functions for controlling the E220 LoRa module.
Functions
HAL_StatusTypeDef E220_WaitAuxHigh (uint32_t timeout)
Waits for the E220's AUX pin to go to a HIGH state.
HAL_StatusTypeDef SetConfiguration (uint8_t channel, uint8_t persistence)
Sets the module's channel and persistence using a direct register command.
HAL_StatusTypeDef E220_SendATCommand (const char *command, UART_HandleTypeDef huart)
Sends an AT command string to the E220 module via UART DMA.
bool E220_WaitForResponse (uint32_t timeout_ms)
Waits for a response from the E220 module after sending an AT command.
HAL_StatusTypeDef E220_Init_AT (const E220_Config_AT_t *config, uint8_t operating_mode, UART_HandleTypeDef huart)
Initializes the E220 LoRa module using AT commands.
HAL_StatusTypeDef E220_Change_Channel (uint8_t channel, UART_HandleTypeDef huart)
Changes the E220's operating channel using an AT command.
HAL_StatusTypeDef E220_SetConfiguration_RegisterMode (const E220_ModuleConfig_Register_t *config, UART_HandleTypeDef *huart)
Sets the E220 configuration using direct register writes.
HAL_StatusTypeDef E220_ReadConfiguration_RegisterMode (E220_ModuleConfig_Register_t *config, UART_HandleTypeDef *huart)
Reads the E220 module configuration using direct register reads.
Detailed Description
Public functions for controlling the E220 LoRa module.
Function Documentation
E220_Change_Channel()
HAL_StatusTypeDef E220_Change_Channel (uint8_t channel, UART_HandleTypeDef huart)
Changes the E220's operating channel using an AT command.
Convenience function to send the 'AT+CHANNEL=...' command. Handles mode switching.
Parameters
channel The new RF channel to set.
huart The UART handle to use for communication.
Return values
HAL_OK Command sent successfully.
HAL_ERROR Failed to send command.
Definition at line 118 of file e220.c.
{
    HAL_StatusTypeDef status = HAL_ERROR;
    char cmd_buffer[64]; // Buffer to build AT command strings
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_SET);
    HAL_Delay(20);
    while(HAL_GPIO_ReadPin(E220_AUX_GPIO_Port, E220_AUX_Pin) == GPIO_PIN_RESET);
    HAL_Delay(2);
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+CHANNEL=%d", channel);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    HAL_Delay(50); // Wait for response
    // TODO: TRY TO READ THE RESPONSE AND EVALUATE IF IT CAN BE WORTHY TO IMPLEMENT E220_WaitForResponse
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
    HAL_Delay(20);
    while(HAL_GPIO_ReadPin(E220_AUX_GPIO_Port, E220_AUX_Pin) == GPIO_PIN_RESET);
    HAL_Delay(2);
    return HAL_OK;
}
References E220_AUX_GPIO_Port, E220_AUX_Pin, E220_M0_GPIO_Port, E220_M0_Pin, E220_M1_GPIO_Port, E220_M1_Pin, and E220_SendATCommand().
E220_Init_AT()
HAL_StatusTypeDef E220_Init_AT (const E220_Config_AT_t * config, uint8_t operating_mode, UART_HandleTypeDef huart)
Initializes the E220 LoRa module using AT commands.
This function enters configuration mode (M0=1, M1=1), sends a series of AT commands based on the config struct, and then switches to the specified operating_mode.
Parameters
config Pointer to the E220_Config_AT_t structure with desired settings.
operating_mode Desired final mode (0:Normal, 1:WOR Sending, 2:WOR Receiving, 3:Deep Sleep).
huart The UART handle to use for communication.
Return values
HAL_OK Configuration commands were sent successfully.
HAL_ERROR An invalid parameter or transmission error occurred.
Definition at line 150 of file e220.c.
{
    HAL_StatusTypeDef status = HAL_ERROR;
    char cmd_buffer[64]; // Buffer to build AT command strings
    // --- Step 1: Enter Configuration Mode (M1=1, M0=1) ---
    // Ensure M0 and M1 are configured as output GPIOs in your .ioc file.
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_SET);
    // Wait for the module to enter configuration mode.
    // Datasheet suggests ~9-11ms for mode switching. Waiting for AUX rising edge is best.
    // For simplicity in this template, we'll use a delay.
    HAL_Delay(20); // Adjust delay based on testing if needed
    //wait for AUX to go high:
    while(HAL_GPIO_ReadPin(E220_AUX_GPIO_Port, E220_AUX_Pin) == GPIO_PIN_RESET);
    HAL_Delay(2); // Additional delay after AUX rising edge as per datasheet suggestion
    // In configuration mode, the UART baud rate is fixed at 9600 8N1 for AT commands.
    // Ensure your microcontroller's UART is configured to 9600 8N1 before sending AT commands.
    // --- Step 2: Send AT Commands to Configure Parameters ---
    // Send AT+RESET (Optional, but good practice to start from a known state)
    status = E220_SendATCommand("AT+RESET",huart);
    if (status != HAL_OK) return status;
    // Wait for module reset and response. Reset might take longer than other commands.
    E220_WaitForResponse(100);
    // Send AT+UART=baud,parity
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+UART=%d,%d", config->uart_baud_rate, config->uart_parity);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+RATE=rate
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+RATE=%d", config->air_data_rate);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+PACKET=packet
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+PACKET=%d", config->sub_packet_setting);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+WTIME=wtime
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+WTIME=%d", config->wor_cycle);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+POWER=power
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+POWER=%d", config->transmitting_power);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+CHANNEL=channel
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+CHANNEL=%d", config->channel);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+DRSSI=data_rssi
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+DRSSI=%d", config->rssi_byte_enable ? 1 : 0);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+TRANS=trans
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+TRANS=%d", config->transmission_method ? 1 : 0);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+LBT=lbt
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+LBT=%d", config->lbt_enable ? 1 : 0);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+ADDR=addr
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+ADDR=%d", config->address);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+KEY=key
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+KEY=%d", config->crypt_key);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+DELAY=delay
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+DELAY=%d", config->wor_delay);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+SWITCH=switch
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+SWITCH=%d", config->software_switching_enable ? 1 : 0);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // Send AT+UAUX=uaux
    snprintf(cmd_buffer, sizeof(cmd_buffer), "AT+UAUX=%d", config->aux_indication_mode);
    status = E220_SendATCommand(cmd_buffer,huart);
    if (status != HAL_OK) return status;
    E220_WaitForResponse(50); // Wait for response
    // --- Step 3: Exit Configuration Mode and Enter Desired Operating Mode ---
    // Set M0 and M1 to the desired operating mode.
    // 0: Normal (M0=0, M1=0)
    // 1: WOR Sending (M0=0, M1=1)
    // 2: WOR Receiving (M0=1, M1=0)
    // 3: Deep Sleep (M0=1, M1=1)
    GPIO_PinState m0_state = GPIO_PIN_RESET;
    GPIO_PinState m1_state = GPIO_PIN_RESET;
    switch(operating_mode)
    {
        case 0: // Normal Mode (M0=0, M1=0)
            m0_state = GPIO_PIN_RESET;
            m1_state = GPIO_PIN_RESET;
            break;
        case 1: // WOR Sending Mode (M0=0, M1=1)
            m0_state = GPIO_PIN_RESET;
            m1_state = GPIO_PIN_SET;
            break;
        case 2: // WOR Receiving Mode (M0=1, M1=0)
            m0_state = GPIO_PIN_SET;
            m1_state = GPIO_PIN_RESET;
            break;
        case 3: // Deep Sleep Mode (M0=1, M1=1)
            m0_state = GPIO_PIN_SET;
            m1_state = GPIO_PIN_SET;
            break;
        default:
            // Invalid operating mode, handle error
            return HAL_ERROR;
    }
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, m0_state);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, m1_state);
    // Wait for the module to switch modes (wait for AUX rising edge).
    while(HAL_GPIO_ReadPin(E220_AUX_GPIO_Port, E220_AUX_Pin) == GPIO_PIN_RESET);
    HAL_Delay(2); // Additional delay after AUX rising edge
    return HAL_OK; // Indicate commands were sent (response success not verified in this template)
}
References E220_Config_AT_t::address, E220_Config_AT_t::air_data_rate, E220_Config_AT_t::aux_indication_mode, E220_Config_AT_t::channel, E220_Config_AT_t::crypt_key, E220_AUX_GPIO_Port, E220_AUX_Pin, E220_M0_GPIO_Port, E220_M0_Pin, E220_M1_GPIO_Port, E220_M1_Pin, E220_SendATCommand(), E220_WaitForResponse(), E220_Config_AT_t::lbt_enable, E220_Config_AT_t::rssi_byte_enable, E220_Config_AT_t::software_switching_enable, E220_Config_AT_t::sub_packet_setting, E220_Config_AT_t::transmission_method, E220_Config_AT_t::transmitting_power, E220_Config_AT_t::uart_baud_rate, E220_Config_AT_t::uart_parity, E220_Config_AT_t::wor_cycle, and E220_Config_AT_t::wor_delay.
E220_ReadConfiguration_RegisterMode()
HAL_StatusTypeDef E220_ReadConfiguration_RegisterMode (E220_ModuleConfig_Register_t * config, UART_HandleTypeDef * huart)
Reads the E220 module configuration using direct register reads.
Handles switching to config mode, sending the 0xC1 read command, parsing the response into the config struct, and returning to normal mode.
Note
Assumes UART is 9600 8N1 during config.
Parameters
config Pointer to a structure where the read configuration will be stored.
huart Pointer to the UART handle for communication.
Return values
HAL_OK on success, HAL_ERROR or HAL_TIMEOUT on failure.
Definition at line 438 of file e220.c.
{
    if (config == NULL || huart == NULL) {
        return HAL_ERROR; // Invalid arguments
    }
    HAL_StatusTypeDef status = HAL_OK;
    uint8_t command_buffer[3]; // CMD, StartAddr, Length
    uint8_t response_buffer[3 + E220_CONFIG_REGS_LENGTH]; // Expected: C1, StartAddr, Length, Data...
    // --- Step 1: Enter Configuration Mode (M0=1, M1=1) ---
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_SET);
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(10);
#else
    HAL_Delay(10);
#endif
    status = E220_WaitAuxHigh(1000);
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2);
#else
    HAL_Delay(2);
#endif
    // --- Step 2: Prepare Read Command ---
    command_buffer[0] = 0xC1; // Read parameters command
    command_buffer[1] = E220_CONFIG_REGS_START_ADDR;
    command_buffer[2] = E220_CONFIG_REGS_LENGTH;
    // --- Step 3: Transmit Read Command ---
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2);
#else
    HAL_Delay(2);
#endif
    status = HAL_UART_Transmit(huart, command_buffer, sizeof(command_buffer), 100);
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
    // --- Step 4: Wait for AUX High (Module processes command and prepares data) ---
    status = E220_WaitAuxHigh(1000);
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2);
#else
    HAL_Delay(2);
#endif
    // --- Step 5: Receive Response ---
    status = HAL_UART_Receive(huart, response_buffer, sizeof(response_buffer), 100);
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
    // --- Step 6: Validate and Parse Response ---
    if (response_buffer[0] != 0xC1 || response_buffer[1] != E220_CONFIG_REGS_START_ADDR || response_buffer[2] != E220_CONFIG_REGS_LENGTH) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return HAL_ERROR; // Response header mismatch
    }
    // Parse data into config struct
    uint8_t* data = &response_buffer[3];
    config->address = ((uint16_t)data[0] << 8) | data[1]; // ADDH, ADDL
    // REG0
    config->uart_baud_rate_idx = (data[2] >> 5) & 0x07;
    config->uart_parity_idx    = (data[2] >> 3) & 0x03;
    config->air_data_rate_idx  = data[2] & 0x07;
    // REG1
    config->subpacket_size_idx        = (data[3] >> 6) & 0x03;
    config->rssi_ambient_noise_enable = (data[3] >> 5) & 0x01;
    // Bit 4 is reserved
    config->transmitting_power_idx    = data[3] & 0x03;
    // REG2
    // Bit 7 is reserved
    config->channel = data[4] & 0x7F;
    // REG3
    config->rssi_byte_enable        = (data[5] >> 7) & 0x01;
    config->transmission_method     = (data[5] >> 6) & 0x01;
    config->repeater_enable         = (data[5] >> 5) & 0x01;
    config->lbt_enable              = (data[5] >> 4) & 0x01;
    config->wor_transmitter_control = (data[5] >> 3) & 0x01;
    config->wor_cycle_idx           = data[5] & 0x07;
    config->net_id = data[6];
    // --- Step 7: Exit Configuration Mode (Return to Normal Mode M0=0, M1=0) ---
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(10);
#else
    HAL_Delay(10);
#endif
    status = E220_WaitAuxHigh(1000);
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2);
#else
    HAL_Delay(2);
#endif
    return status;
}
References E220_ModuleConfig_Register_t::address, E220_ModuleConfig_Register_t::air_data_rate_idx, E220_ModuleConfig_Register_t::channel, E220_CONFIG_REGS_LENGTH, E220_CONFIG_REGS_START_ADDR, E220_M0_GPIO_Port, E220_M0_Pin, E220_M1_GPIO_Port, E220_M1_Pin, E220_WaitAuxHigh(), E220_ModuleConfig_Register_t::lbt_enable, E220_ModuleConfig_Register_t::net_id, E220_ModuleConfig_Register_t::repeater_enable, E220_ModuleConfig_Register_t::rssi_ambient_noise_enable, E220_ModuleConfig_Register_t::rssi_byte_enable, E220_ModuleConfig_Register_t::subpacket_size_idx, E220_ModuleConfig_Register_t::transmission_method, E220_ModuleConfig_Register_t::transmitting_power_idx, E220_ModuleConfig_Register_t::uart_baud_rate_idx, E220_ModuleConfig_Register_t::uart_parity_idx, E220_ModuleConfig_Register_t::wor_cycle_idx, and E220_ModuleConfig_Register_t::wor_transmitter_control.
E220_SendATCommand()
HAL_StatusTypeDef E220_SendATCommand (const char * command, UART_HandleTypeDef huart)
Sends an AT command string to the E220 module via UART DMA.
Assumes module is in AT command mode (M0=1, M1=1) and UART is 9600 8N1.
Parameters
command Null-terminated string containing the AT command (e.g., "AT+RESET").
huart The UART handle to use for transmission.
Return values
HAL_StatusTypeDef Status of the HAL_UART_Transmit_DMA operation.
Definition at line 77 of file e220.c.
{
    // AT commands typically end with CR+LF (\r\n)
    char cmd_buffer[64]; // Adjust size as needed for longest command + termination
    int len = snprintf(cmd_buffer, sizeof(cmd_buffer), "%s", command);
    if (len < 0 || len >= sizeof(cmd_buffer))
    {
        // Handle buffer overflow or encoding error
        return HAL_ERROR;
    }
    // Send the command buffer using DMA
    // This is non-blocking. You would typically wait for TX completion
    // and/or the module's response after calling this.
    return HAL_UART_Transmit_DMA(&huart, (uint8_t*)cmd_buffer, len);
}
Referenced by E220_Change_Channel(), and E220_Init_AT().
E220_SetConfiguration_RegisterMode()
HAL_StatusTypeDef E220_SetConfiguration_RegisterMode (const E220_ModuleConfig_Register_t * config, UART_HandleTypeDef * huart)
Sets the E220 configuration using direct register writes.
Handles switching to config mode, sending the 0xC0 write command with data from the config struct, and returning to normal mode.
Note
Assumes UART is 9600 8N1 during config.
Parameters
config Pointer to the E220_ModuleConfig_Register_t structure with desired settings.
huart Pointer to the UART handle for communication.
Return values
HAL_OK Configuration written and verified successfully.
HAL_ERROR or HAL_TIMEOUT Failed to write, verify, or time out.
Definition at line 309 of file e220.c.
{
    if (config == NULL || huart == NULL) {
        return HAL_ERROR; // Invalid arguments
    }
    HAL_StatusTypeDef status = HAL_OK;
    uint8_t command_buffer[3 + E220_CONFIG_REGS_LENGTH]; // CMD, ADDR, LEN + Data
    uint8_t response_buffer[3 + E220_CONFIG_REGS_LENGTH];
    // --- Step 1: Enter Configuration Mode (M0=1, M1=1) ---
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_SET);
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(10); // Allow time for pins to settle and module to react (e.g. 4ms + buffer)
#else
    HAL_Delay(10);
#endif
    status = E220_WaitAuxHigh(1000);
    if (status != HAL_OK) {
        // Failed to enter config mode or AUX not responding
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET); // Revert to Normal Mode
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status; // HAL_TIMEOUT or other error
    }
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2); // Short delay after AUX high
#else
    HAL_Delay(2);
#endif
    // --- Step 2: Prepare Command Buffer ---
    // Command: 0xC0, StartAddr (0x00), Length (0x07), Data...
    command_buffer[0] = 0xC0; // Write parameters and save to EEPROM
    command_buffer[1] = E220_CONFIG_REGS_START_ADDR;
    command_buffer[2] = E220_CONFIG_REGS_LENGTH;
    command_buffer[3] = (config->address >> 8) & 0xFF; // ADDH
    command_buffer[4] = config->address & 0xFF;        // ADDL
    // REG0 (UART Baud, Parity, Air Data Rate)
    command_buffer[5] = (config->uart_baud_rate_idx << 5) |
                        (config->uart_parity_idx << 3)    |
                        (config->air_data_rate_idx & 0x07);
    // REG1 (Subpacket, RSSI Noise Enable, Tx Power - Bit 4 is reserved, assumed 0)
    command_buffer[6] = (config->subpacket_size_idx << 6)        |
                        (config->rssi_ambient_noise_enable << 5) |
                        // Bit 4 is reserved (keep 0 as per most datasheets)
                        (config->transmitting_power_idx & 0x03);
    // REG2 (Channel - Bit 7 is reserved, assumed 0)
    command_buffer[7] = (config->channel & 0x7F); // Bit 7 reserved
    // REG3 (RSSI Enable, Tx Method, Repeater, LBT, WOR Control, WOR Cycle)
    command_buffer[8] = (config->rssi_byte_enable << 7)        |
                        (config->transmission_method << 6)     |
                        (config->repeater_enable << 5)         |
                        (config->lbt_enable << 4)              |
                        (config->wor_transmitter_control << 3) |
                        (config->wor_cycle_idx & 0x07);
    command_buffer[9] = config->net_id; // NETID
    // --- Step 3: Transmit Command ---
    // Ensure UART is 9600 8N1 for Configuration Mode. This is caller's responsibility
    // or reconfigure UART here if necessary.
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2); // Small delay before transmission
#else
    HAL_Delay(2);
#endif
    status = HAL_UART_Transmit(huart, command_buffer, sizeof(command_buffer), 100);
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET); // Revert to Normal Mode
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
    // --- Step 4: Wait for AUX High (Module processes and saves to EEPROM) ---
    status = E220_WaitAuxHigh(1000); // Saving to EEPROM can take longer
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET); // Revert to Normal Mode
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2); // Short delay after AUX high
#else
    HAL_Delay(2);
#endif
    // --- Step 5: Receive Response ---
    status = HAL_UART_Receive(huart, response_buffer, sizeof(response_buffer), 100);
    if (status != HAL_OK) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET); // Revert to Normal Mode
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return status;
    }
    // --- Step 6: Validate Response ---
    // Expected: C1 <same StartAddr> <same Length> <same Data...>
    if (response_buffer[0] != 0xC1 || memcmp(&response_buffer[1], &command_buffer[1], sizeof(command_buffer) - 1) != 0) {
        HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET); // Revert to Normal Mode
        HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
        return HAL_ERROR; // Response mismatch
    }
    // --- Step 7: Exit Configuration Mode (Return to Normal Mode M0=0, M1=0) ---
    HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(10); // Allow time for mode switch (e.g. 4ms + buffer)
#else
    HAL_Delay(10);
#endif
    status = E220_WaitAuxHigh(1000); // Wait for AUX to confirm mode switch
#if defined(USE_FREERTOS) && USE_FREERTOS == 1
    osDelay(2); // Short delay after AUX high
#else
    HAL_Delay(2);
#endif
    // If E220_WaitAuxHigh failed, status will be HAL_TIMEOUT.
    // If it was OK, status is HAL_OK.
    return status;
}
References E220_ModuleConfig_Register_t::address, E220_ModuleConfig_Register_t::air_data_rate_idx, E220_ModuleConfig_Register_t::channel, E220_CONFIG_REGS_LENGTH, E220_CONFIG_REGS_START_ADDR, E220_M0_GPIO_Port, E220_M0_Pin, E220_M1_GPIO_Port, E220_M1_Pin, E220_WaitAuxHigh(), E220_ModuleConfig_Register_t::lbt_enable, E220_ModuleConfig_Register_t::net_id, E220_ModuleConfig_Register_t::repeater_enable, E220_ModuleConfig_Register_t::rssi_ambient_noise_enable, E220_ModuleConfig_Register_t::rssi_byte_enable, E220_ModuleConfig_Register_t::subpacket_size_idx, E220_ModuleConfig_Register_t::transmission_method, E220_ModuleConfig_Register_t::transmitting_power_idx, E220_ModuleConfig_Register_t::uart_baud_rate_idx, E220_ModuleConfig_Register_t::uart_parity_idx, E220_ModuleConfig_Register_t::wor_cycle_idx, and E220_ModuleConfig_Register_t::wor_transmitter_control.
E220_WaitAuxHigh()
HAL_StatusTypeDef E220_WaitAuxHigh (uint32_t timeout)
Waits for the E220's AUX pin to go to a HIGH state.
The AUX pin signals when the module is ready (e.g., finished processing a command or booting). This function polls the pin with an RTOS-aware delay.
Parameters
timeout Maximum time to wait in milliseconds.
Return values
HAL_OK AUX pin went HIGH within the timeout.
HAL_ERROR Timed out waiting for AUX pin.
Definition at line 20 of file e220.c.
{
    uint32_t start_time = HAL_GetTick();
    while(HAL_GPIO_ReadPin( E220_AUX_GPIO_Port, E220_AUX_Pin) == GPIO_PIN_RESET){
        if(HAL_GetTick() - start_time > timeout){
            return HAL_ERROR;
        }
        osDelay(1);
    }
    return HAL_OK;
}
References E220_AUX_GPIO_Port, and E220_AUX_Pin.
Referenced by E220_ReadConfiguration_RegisterMode(), E220_SetConfiguration_RegisterMode(), SetConfiguration(), and StartLoRaTransmitTask().
E220_WaitForResponse()
bool E220_WaitForResponse (uint32_t timeout_ms)
Waits for a response from the E220 module after sending an AT command.
This is a placeholder function. A real implementation would involve UART RX (DMA or IT) and response parsing (e.g., 'OK', 'ERR').
Parameters
timeout_ms Timeout in milliseconds to wait for a response.
Return values
true Placeholder, indicates 'OK' was (theoretically) received.
false Placeholder, indicates timeout or 'ERR'.
Definition at line 99 of file e220.c.
{
    // --- PLACEHOLDER IMPLEMENTATION ---
    // In a real system, you would:
    // 1. Ensure UART RX is enabled (e.g., HAL_UART_Receive_DMA or IT).
    // 2. Have a buffer to store incoming UART data.
    // 3. In your UART RX callback, append received bytes to the buffer.
    // 4. In this function, wait (with a timeout) for the buffer to contain
    //    the expected response string ("Command = OK", "=ERR", etc.).
    // 5. Parse the buffer content.
    // For now, we'll just use a delay as a simplified placeholder.
    // This is NOT reliable for production code.
    HAL_Delay(timeout_ms);
    // Assume success for the placeholder
    return true; // Assume OK response received after delay
}
Referenced by E220_Init_AT().
SetConfiguration()
HAL_StatusTypeDef SetConfiguration (uint8_t channel, uint8_t persistence)
Sets the module's channel and persistence using a direct register command.
This function sends a specific command to write to the channel register. It handles entering/exiting config mode.
Parameters
channel The RF channel to set (e.g., 0-83).
persistence The command byte (e.g., 0xC0 to save, 0xC2 for temporary).
Return values
HAL_OK Command sent successfully.
HAL_ERROR Failed to send command or wait for AUX.
Definition at line 31 of file e220.c.
{
    HAL_StatusTypeDef status = HAL_OK;
    uint8_t command_buffer[] = {persistence, 0x04, 0x01, channel};
    HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_SET);
    osDelay(10);
//  HAL_Delay(10);
    status = E220_WaitAuxHigh(1000);
    if (status != HAL_OK) {
       HAL_GPIO_WritePin(E220_M0_GPIO_Port, E220_M0_Pin, GPIO_PIN_RESET);
       HAL_GPIO_WritePin(E220_M1_GPIO_Port, E220_M1_Pin, GPIO_PIN_RESET);
       return status;
    }
    osDelay(5);
//  HAL_Delay(10);
    HAL_StatusTypeDef sts = HAL_UART_Transmit(&huart4, (uint8_t*)command_buffer, sizeof(command_buffer),200);
    if (sts != HAL_OK){
        HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_RESET);
        HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
        osDelay(10);
//      HAL_Delay(10);
        return HAL_ERROR;
    }
//  HAL_StatusTypeDef sts_2 = HAL_UART_Receive(&huart4, (uint8_t*) response, sizeof(response),100);
//  if (sts_2 != HAL_OK){
//         HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_RESET);
//         HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
//         osDelay(10);
//         return HAL_ERROR;
//  }
   HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_RESET);
   HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
   osDelay(50);
//   HAL_Delay(50);
    return status;
}
References E220_M0_GPIO_Port, E220_M0_Pin, E220_M1_GPIO_Port, E220_M1_Pin, E220_WaitAuxHigh(), GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, and huart4.
Referenced by LoRa_SetChannel().