Marconi Firmware: Servo Driver Functions
Servo Driver Functions
Airbrake Control
Public API for controlling a servo motor.
Functions
uint32_t servo_init (servo_t *servo, uint32_t pwm_freq, uint32_t target_arr)
Initializes the servo and its associated hardware timer.
float servo_moveto_deg (servo_t *servo, float angle)
Commands the servo to move to a specific angle (in degrees).
float servo_rawmove (servo_t *servo, uint32_t ccr)
Commands the servo by writing a raw CCR (pulse width) value.
void servo_update_ccr (servo_t *servo, uint32_t ccr)
Directly updates the timer's hardware CCR register.
float servo_dutycycle (servo_t *servo, float angle)
Converts an angle (in degrees) to a normalized duty cycle (0.0 to 1.0).
float servo_dutycycle_ccr (servo_t *servo, uint32_t ccr)
Converts a raw CCR value to a normalized duty cycle (0.0 to 1.0).
uint32_t servo_ccr (servo_t *servo, float dutycycle)
Converts a normalized duty cycle (0.0 to 1.0) to a raw CCR value.
float servo_angle (servo_t *servo, float dutycycle)
Converts a normalized duty cycle (0.0 to 1.0) to an angle (in degrees).
Detailed Description
Public API for controlling a servo motor.
Function Documentation
servo_angle()
float servo_angle (servo_t * servo, float dutycycle)
Converts a normalized duty cycle (0.0 to 1.0) to an angle (in degrees).
Parameters
servo Pointer to the initialized servo_t object.
dutycycle The normalized duty cycle (0.0 to 1.0).
Returns
The corresponding angle in degrees.
Definition at line 147 of file servo.c.
{
    return (dutycycle * (servo->max_angle - servo->min_angle)) + servo->min_angle;
}
References servo_t::max_angle, and servo_t::min_angle.
Referenced by servo_rawmove().
servo_ccr()
uint32_t servo_ccr (servo_t * servo, float dutycycle)
Converts a normalized duty cycle (0.0 to 1.0) to a raw CCR value.
Parameters
servo Pointer to the initialized servo_t object.
dutycycle The normalized duty cycle (0.0 to 1.0).
Returns
The corresponding raw CCR value.
Definition at line 143 of file servo.c.
{
    return (dutycycle * (servo->maxpos_ccr - servo->minpos_ccr)) + servo->minpos_ccr;
}
References servo_t::maxpos_ccr, and servo_t::minpos_ccr.
Referenced by servo_init(), and servo_moveto_deg().
servo_dutycycle()
float servo_dutycycle (servo_t * servo, float angle)
Converts an angle (in degrees) to a normalized duty cycle (0.0 to 1.0).
Parameters
servo Pointer to the initialized servo_t object.
angle The angle to convert.
Returns
The normalized duty cycle (0.0 for min_angle, 1.0 for max_angle).
Definition at line 135 of file servo.c.
{
    return (angle - servo->min_angle) / (servo->max_angle - servo->min_angle);
}
References servo_t::max_angle, and servo_t::min_angle.
Referenced by servo_moveto_deg().
servo_dutycycle_ccr()
float servo_dutycycle_ccr (servo_t * servo, uint32_t ccr)
Converts a raw CCR value to a normalized duty cycle (0.0 to 1.0).
Parameters
servo Pointer to the initialized servo_t object.
ccr The CCR value to convert.
Returns
The normalized duty cycle (0.0 for minpos_ccr, 1.0 for maxpos_ccr).
Definition at line 139 of file servo.c.
{
    return ((float) (ccr - servo->minpos_ccr)) / ((float) (servo->maxpos_ccr - servo->minpos_ccr));
}
References servo_t::maxpos_ccr, and servo_t::minpos_ccr.
Referenced by servo_rawmove().
servo_init()
uint32_t servo_init (servo_t * servo, uint32_t pwm_freq, uint32_t target_arr)
Initializes the servo and its associated hardware timer.
Calculates the required PSC and ARR values based on pwm_freq and target_arr.
Calculates the minpos_ccr and maxpos_ccr values from the ms pulse widths.
Sets the TIM_CCR pointer to the correct hardware register.
De-initializes and re-initializes the HAL timer (servo->htim) in PWM mode.
Configures the specified PWM channel (servo->pwm_channel).
Starts the PWM signal.
Parameters
servo Pointer to the servo_t object to initialize.
pwm_freq The desired PWM frequency (e.g., PWM_FREQ).
target_arr The target ARR value for calculation (e.g., TARGET_ARR).
Returns
The calculated timer counter frequency (timer_freq).
Definition at line 14 of file servo.c.
{
    TIM_MasterConfigTypeDef master_conf = {0};
//  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
    TIM_OC_InitTypeDef oc_conf = {0};
    // see __HAL_TIM_SET_COMPARE source
    switch(servo->pwm_channel) {
    case TIM_CHANNEL_1:
            servo->TIM_CCR = &(servo->htim->Instance->CCR1);
            break;
    case TIM_CHANNEL_2:
            servo->TIM_CCR = &(servo->htim->Instance->CCR2);
            break;
    case TIM_CHANNEL_3:
            servo->TIM_CCR = &(servo->htim->Instance->CCR3);
            break;
    default:
            servo->TIM_CCR = &(servo->htim->Instance->CCR4);
            break;
    }
    servo->psc = (uint32_t) servo->bus_freq / (pwm_freq * target_arr);
    servo->arr = (uint32_t) servo->bus_freq / (pwm_freq * (servo->psc + 1)) - 1;
    uint32_t timer_freq = servo->bus_freq / (servo->psc + 1);
    // /1000 because periods are in ms
    servo -> minpos_ccr =  (uint32_t) (servo->minpos_period_ms * timer_freq) / 1000;
    servo -> maxpos_ccr =  (uint32_t) (servo->maxpos_period_ms * timer_freq) / 1000;
    // Timer deinit
    HAL_TIM_PWM_DeInit(servo->htim);
    // __HAL_RCC_TIM3_CLK_ENABLE(); // Not needed? i think it's done in Init
    // Assume timer instance is set before call to servo_init
    // servo->htim.Instance = servo->TIM;
    // Timer init
    servo->htim->Init.Prescaler = servo->psc;
    servo->htim->Init.CounterMode = TIM_COUNTERMODE_UP;
    servo->htim->Init.Period = servo->arr;
    servo->htim->Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    servo->htim->Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
    HAL_TIM_PWM_Init(servo->htim);
//  Clock Source init
//  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
//  HAL_TIM_ConfigClockSource(&htim, &sClockSourceConfig);
    // Timer master mode init
    master_conf.MasterOutputTrigger = TIM_TRGO_RESET;
    master_conf.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
    HAL_TIMEx_MasterConfigSynchronization(servo->htim, &master_conf);
    // Timer PWM channel init
    oc_conf.OCMode = TIM_OCMODE_PWM1;
    oc_conf.Pulse = servo_ccr(servo, 0); // ccr for 0% dutycycle
    oc_conf.OCPolarity = TIM_OCPOLARITY_HIGH;
    oc_conf.OCFastMode = TIM_OCFAST_DISABLE;
    HAL_TIM_PWM_ConfigChannel(servo->htim, &oc_conf, servo->pwm_channel);
    // GPIO pin init // Not needed, you just set it in IOC to the pwm channel
    // gpio_init.Pin = servo->gpio_pin;
    // gpio_init.Mode = GPIO_MODE_AF_PP;
    // gpio_init.Speed = GPIO_SPEED_FREQ_LOW;
    // __HAL_RCC_GPIOB_CLK_ENABLE();
    // HAL_GPIO_Init(servo->gpio_port, &gpio_init);
    HAL_TIM_PWM_Start(servo->htim, servo->pwm_channel);
    return timer_freq;
}
References servo_t::arr, servo_t::bus_freq, servo_t::htim, servo_t::maxpos_period_ms, servo_t::minpos_period_ms, servo_t::psc, servo_t::pwm_channel, servo_ccr(), and servo_t::TIM_CCR.
Referenced by airbrakes_init().
servo_moveto_deg()
float servo_moveto_deg (servo_t * servo, float angle)
Commands the servo to move to a specific angle (in degrees).
Clamps the requested angle within the servo's min/max limits. Converts the angle to a duty cycle, then to a CCR value, and updates the timer's hardware register.
Parameters
servo Pointer to the initialized servo_t object.
angle The target angle in degrees.
Returns
The difference between the requested and the clamped angle (0 on success, non-zero if clamping occurred).
Definition at line 103 of file servo.c.
{
    float o_angle = angle;
    if (angle < servo->min_angle) {
        angle = servo->min_angle;
        errno = ERANGE;
    }
    if (angle > servo->max_angle) {
        angle = servo->max_angle;
        errno = ERANGE;
    }
    // angle to ccr
    uint32_t ccr = servo_ccr(servo, servo_dutycycle(servo, angle));
    servo_update_ccr(servo, ccr);
    return angle - o_angle; // 0 on success
}
References servo_t::max_angle, servo_t::min_angle, servo_ccr(), servo_dutycycle(), and servo_update_ccr().
Referenced by airbrakes_init(), and StartReceived_Pckg().
servo_rawmove()
float servo_rawmove (servo_t * servo, uint32_t ccr)
Commands the servo by writing a raw CCR (pulse width) value.
Clamps the ccr value within the calculated minpos_ccr and maxpos_ccr limits. This is a lower-level move function.
Parameters
servo Pointer to the initialized servo_t object.
ccr The raw Capture Compare Register value to write.
Returns
The angle (in degrees) corresponding to the ccr value, or 0 if clamping occurred (errno is set to ERANGE).
Definition at line 123 of file servo.c.
{
    if (ccr <= servo->maxpos_ccr && ccr >= servo->minpos_ccr) {
        servo_update_ccr(servo, ccr);
        // ccr to angle
        return servo_angle(servo, servo_dutycycle_ccr(servo, ccr));
    } else {
        errno = ERANGE;
        return 0;
    }
}
References servo_t::minpos_ccr, servo_angle(), servo_dutycycle_ccr(), and servo_update_ccr().
servo_update_ccr()
void servo_update_ccr (servo_t * servo, uint32_t ccr)
Directly updates the timer's hardware CCR register.
This function uses the pre-set TIM_CCR pointer for a fast write. It is called by servo_moveto_deg and servo_rawmove.
Parameters
servo Pointer to the initialized servo_t object.
ccr The new CCR value to write.
Definition at line 98 of file servo.c.
{
    *(servo -> TIM_CCR) = ccr;
    __HAL_TIM_SET_COMPARE(servo->htim, servo->pwm_channel, ccr);
}
References servo_t::htim, and servo_t::pwm_channel.
Referenced by servo_moveto_deg(), and servo_rawmove().