Marconi Firmware: Telemetry
Telemetry
System Core
Communication with the Ground Station.
Modules
Telemetry Buffers & Packets
E220 LoRa Module GPIO Pins
GPIO pin definitions mapping to the E220 module's control lines.
E220 Register Map Addresses
Address offsets for the module's internal configuration registers.
E220 Driver Functions
Public functions for controlling the E220 LoRa module.
Data Structures
struct E220_ModuleConfig_Register_t
Represents the E220 module's configuration based on its direct register map.
struct E220_Config_AT_t
Represents the E220 module's configuration based on AT command parameters.
struct Data_Package_To_GS
Data structure for packets sent to the Ground Station.
Macros
#define E220_MODULE_CONFIG_REGISTER_T_DEFINED
Functions
void LoRa_SetChannel (uint8_t *channel)
Sets the LoRa module's RF channel using a register write.
void processMessage (uint8_t command, uint8_t *data)
Processes incoming commands from the Ground Station.
Variables
Data_Package_To_GS packet2
Global instance for the outgoing GS packet.
bool Acked = true
LoRa ACK state machine flag. true = OK to send data.
bool Changing_Freq = false
LoRa ACK state machine flag. true = waiting for freq change ACK.
uint8_t old_channel
Stores previous LoRa channel during a change.
uint8_t current_channel = 0x12
Current active LoRa channel.
char ACK [3] = "~G!"
ACK packet sent on 'G' command.
Detailed Description
Communication with the Ground Station.
Manages data packet formatting and transmission/reception via XBEE and/or LoRa modules.
Macro Definition Documentation
E220_MODULE_CONFIG_REGISTER_T_DEFINED
#define E220_MODULE_CONFIG_REGISTER_T_DEFINED
Definition at line 68 of file e220.h.
Function Documentation
LoRa_SetChannel()
void LoRa_SetChannel (uint8_t * channel)
Sets the LoRa module's RF channel using a register write.
This function is called by processMessage when an 'F' command is received. It updates current_channel and old_channel.
Parameters
channel Pointer to a 2-char array (e.g., "12") to set the channel.
Definition at line 453 of file main.c.
{
    //TODO de-comment the acking system when we will implement it
    //Acked = false;
    //TODO de-comment the acking system when we will implement it
    char temp[3] = { (char)channel[0], (char)channel[1], '\0' };
    char *endptr;
    long value = strtol(temp, &endptr, 10);
    old_channel = current_channel;
    current_channel = value;
    SetConfiguration(value, 0xC0);
    HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
}
References current_channel, GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, old_channel, and SetConfiguration().
Referenced by processMessage().
processMessage()
void processMessage (uint8_t command, uint8_t * data)
Processes incoming commands from the Ground Station.
This function is called by LoRaCommandTask when a command is received in the loraCmdQueue.
Parameters
command The command byte (e.g., 'F', 'G', 'X').
data Pointer to the 2-byte data payload.
Definition at line 477 of file main.c.
{
    switch ((char)command) {
        case 'F': // Change LoRa channel
            LoRa_SetChannel(data);
            //TODO de-comment the acking system when we will implement it
            //osTimerStart(FrequencyTimerHandle, 0);
            //Changing_Freq = true;
            //E220_WaitAuxHigh(1000);
            //HAL_UART_Transmit_DMA(&huart4, ack_S, sizeof(ack));
            //E220_WaitAuxHigh(1000);
            //HAL_UART_Transmit_DMA(&huart4, ack, sizeof(ack));
            //E220_WaitAuxHigh(1000);
            //HAL_UART_Transmit_DMA(&huart4, ack_E, sizeof(ack));
            //E220_WaitAuxHigh(1000);
            //TODO de-comment the acking system when we will implement it
            break;
        case 'G': // Send ACK
            if(!Acked){
                if(Changing_Freq){
                    osTimerStop(FrequencyTimerHandle);
                    osTimerDelete(FrequencyTimerHandle);
                    Changing_Freq = false;
                }
                Acked = true;
            }
            //TODO de-comment the acking system when we will implement it
            //E220_WaitAuxHigh(1000);
            //HAL_UART_Transmit_DMA(&huart4, (uint8_t *)ACK, 3);
            //E220_WaitAuxHigh(1000);
            //TODO de-comment the acking system when we will implement it
            break;
        case 'X': //Turn camera ON
            if(flag_Version == BOARD_ROLE_AVNBAY){
                CAMERA_ON(GPIO_Camera_GPIO_Port,GPIO_Camera_Pin);
            }
            //TODO de-comment the acking system when we will implement it
            //E220_WaitAuxHigh(1000);
            //HAL_UART_Transmit_DMA(&huart4, ack, sizeof(ack));
            //E220_WaitAuxHigh(1000);
            //TODO de-comment the acking system when we will implement it
        default:
            // Handle unknown command
            break;
    }
}
References Acked, BOARD_ROLE_AVNBAY, CAMERA_ON, Changing_Freq, flag_Version, FrequencyTimerHandle, GPIO_Camera_GPIO_Port, GPIO_Camera_Pin, and LoRa_SetChannel().
Referenced by StartLoRaCommandTask().
Variable Documentation
ACK
char ACK[3] = "~G!"
ACK packet sent on 'G' command.
Definition at line 445 of file main.c.
Referenced by StartLoRaTransmitTask().
Acked
bool Acked = true
LoRa ACK state machine flag. true = OK to send data.
Definition at line 331 of file main.c.
Referenced by Frequency_Died(), processMessage(), and StartLoRaTransmitTask().
Changing_Freq
bool Changing_Freq = false
LoRa ACK state machine flag. true = waiting for freq change ACK.
Definition at line 333 of file main.c.
Referenced by Frequency_Died(), and processMessage().
current_channel
uint8_t current_channel = 0x12
Current active LoRa channel.
Definition at line 337 of file main.c.
Referenced by LoRa_SetChannel().
old_channel
uint8_t old_channel
Stores previous LoRa channel during a change.
Definition at line 335 of file main.c.
Referenced by LoRa_SetChannel().
packet2
Data_Package_To_GS packet2
Global instance for the outgoing GS packet.
Definition at line 320 of file main.c.