Marconi Firmware: System Core
System Core
Core system files, main application logic, and global definitions.
Modules
Core Configuration
Defines related to the board's identity and core functionality.
RTOS Event Flags
Event flags used for task notification and synchronization.
Peripheral Configuration
Hardware-related constants for peripherals like ADC and I2C.
EEPROM Configuration
Constants for the 24LC512 EEPROM driver.
Telemetry Buffers & Packets
Global State Variables
Buzzer Control
Provides functions and data for playing melodies on a PWM buzzer (TIM11).
Note Definitions
Tempo Definitions
System Interrupt Callbacks
HAL interrupt and event callback implementations.
RTOS Task Periods
Defines the execution periods for various RTOS tasks in milliseconds.
Peripheral Drivers
Low-level HAL handles and pin definitions.
Telemetry
Communication with the Ground Station.
Data Storage
Manages on-board non-volatile memory.
RTOS_Tasks
RTOS_Timers
Data Structures
struct Note
Represents a single musical note with frequency and duration.
Functions
void SystemClock_Config (void)
System Clock Configuration.
static void MX_GPIO_Init (void)
GPIO Initialization Function.
static void MX_DMA_Init (void)
static void MX_SPI2_Init (void)
SPI2 Initialization Function.
static void MX_UART4_Init (void)
UART4 Initialization Function.
static void MX_USART1_UART_Init (void)
USART1 Initialization Function.
static void MX_USART6_UART_Init (void)
USART6 Initialization Function.
static void MX_ADC1_Init (void)
ADC1 Initialization Function.
static void MX_I2C1_Init (void)
I2C1 Initialization Function.
static void MX_UART5_Init (void)
UART5 Initialization Function.
static void MX_UART7_Init (void)
UART7 Initialization Function.
static void MX_USART3_Init (void)
USART3 Initialization Function.
static void MX_TIM11_Init (void)
TIM11 Initialization Function.
static void MX_TIM3_Init (void)
TIM3 Initialization Function.
void StartReceived_Pckg (void *argument)
RTOS Task: Received Package Handler.
void StartLoRaTransmitTask (void *argument)
RTOS Task: LoRa Transmit Task.
void StartLoRaCommandTask (void *argument)
RTOS Task: LoRa Command Task.
void Frequency_Died (void *argument)
RTOS Timer Callback for LoRa frequency change timeout.
void initDWT (void)
Initializes the DWT (Data Watchpoint and Trace) unit for high-resolution timing (used for debugging).
int main (void)
The application entry point.
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
ADC_HandleTypeDef hadc1
I2C_HandleTypeDef hi2c1
SPI_HandleTypeDef hspi2
TIM_HandleTypeDef htim3
HAL Timer handle for TIM3 (Servo PWM).
TIM_HandleTypeDef htim11
UART_HandleTypeDef huart4
HAL UART handle for UART4 (External XBEE).
UART_HandleTypeDef huart5
HAL UART handle for UART5 (TESEO GNSS).
UART_HandleTypeDef huart7
UART_HandleTypeDef huart1
USART_HandleTypeDef husart3
UART_HandleTypeDef huart6
DMA_HandleTypeDef hdma_uart4_rx
DMA_HandleTypeDef hdma_uart4_tx
DMA_HandleTypeDef hdma_uart5_rx
DMA_HandleTypeDef hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_tx
DMA_HandleTypeDef hdma_usart6_rx
DMA_HandleTypeDef hdma_usart6_tx
osThreadId_t Received_PckgHandle
const osThreadAttr_t Received_Pckg_attributes
osThreadId_t LoRa_Transmit_THandle
const osThreadAttr_t LoRa_Transmit_T_attributes
osThreadId_t LoRaCommandTaskHandle
const osThreadAttr_t LoRaCommandTask_attributes
osMessageQueueId_t loraTxQueueHandle
const osMessageQueueAttr_t loraTxQueue_attributes
osMessageQueueId_t loraCmdQueueHandle
const osMessageQueueAttr_t loraCmdQueue_attributes
osTimerId_t FrequencyTimerHandle
const osTimerAttr_t FrequencyTimer_attributes
osMutexId_t uart4MutexHandle
const osMutexAttr_t uart4Mutex_attributes
osSemaphoreId_t loraTxDoneSemaphoreHandle
const osSemaphoreAttr_t loraTxDoneSemaphore_attributes
uint16_t melody_length = sizeof(Musica_Maestro) / sizeof(Note)
Detailed Description
Core system files, main application logic, and global definitions.
This includes main.h, stm32f4xx_it.h, and peripheral initializations.
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 1849 of file main.c.
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
Referenced by MX_ADC1_Init(), MX_I2C1_Init(), MX_SPI2_Init(), MX_TIM11_Init(), MX_TIM3_Init(), MX_UART4_Init(), MX_UART5_Init(), MX_UART7_Init(), MX_USART1_UART_Init(), MX_USART3_Init(), MX_USART6_UART_Init(), StartLoRaCommandTask(), StartReceived_Pckg(), and SystemClock_Config().
Frequency_Died()
void Frequency_Died (void * argument)
RTOS Timer Callback for LoRa frequency change timeout.
If the GS doesn't ACK a frequency change in time, this callback (TODO: revert to the old_channel and) re-enables normal telemetry by setting Acked = true.
Parameters
argument Not used
Definition at line 1810 of file main.c.
{
  /* USER CODE BEGIN Frequency_Died */
    // TODO de comment the content of this callback when we will reintroduce ACKING
    //LoRa_SetChannel(old_channel);
    Acked = true;
    Changing_Freq = false;
    // TODO de comment the content of this callback when we will reintroduce ACKING
  /* USER CODE END Frequency_Died */
}
References Acked, and Changing_Freq.
Referenced by main().
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM1 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
Definition at line 1831 of file main.c.
{
  /* USER CODE BEGIN Callback 0 */
  /* USER CODE END Callback 0 */
  if (htim->Instance == TIM1)
  {
    HAL_IncTick();
  }
  /* USER CODE BEGIN Callback 1 */
  /* USER CODE END Callback 1 */
}
initDWT()
void initDWT (void)
Initializes the DWT (Data Watchpoint and Trace) unit for high-resolution timing (used for debugging).
Definition at line 745 of file main.c.
                   {
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk; // Enable trace
    DWT->CYCCNT = 0; // Reset the counter
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk; // Enable cycle counter
}
Referenced by main().
main()
int main (void)
The application entry point.
Return values
int
Definition at line 758 of file main.c.
{
  /* USER CODE BEGIN 1 */
  /* USER CODE END 1 */
  /* MCU Configuration--------------------------------------------------------*/
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();
  /* USER CODE BEGIN Init */
  /* USER CODE END Init */
  /* Configure the system clock */
  SystemClock_Config();
  /* USER CODE BEGIN SysInit */
  initDWT();
  /* USER CODE END SysInit */
  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_SPI2_Init();
  MX_UART4_Init();
  MX_USART1_UART_Init();
  MX_USART6_UART_Init();
  MX_ADC1_Init();
  MX_I2C1_Init();
  MX_UART5_Init();
  MX_UART7_Init();
  MX_USART3_Init();
  MX_TIM11_Init();
  MX_TIM3_Init();
  /* USER CODE BEGIN 2 */
  //---------------------------------------------------------------------------------------------------------------------------------TEST ZONE, IGNORE
  //E220_ModuleConfig_Register_t lora;
  //E220_ModuleConfig_Register_t lora2;
  //HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_RESET);
  //HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
  //E220_ReadConfiguration_RegisterMode(&lora,&huart4);
  //if(lora.uart_baud_rate_idx !=7){
    //  lora2 = lora;
     // lora2.uart_baud_rate_idx = 7;
     // E220_SetConfiguration_RegisterMode(&lora2,&huart4);
     // HAL_UART_DeInit(&huart4);
     // huart4.Init.BaudRate = 115200;
     // HAL_UART_Init(&huart4);
  //}
  //E220_ReadConfiguration_RegisterMode(&lora,&huart4);
  //if(lora.uart_baud_rate_idx !=7){
//    __asm("nop");
//  }
 // else{
//    __asm("nop");
 // }
//---------------------------------------------------------------------------------------------------------------------------------TEST ZONE, IGNORE
  HAL_GPIO_WritePin(GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
//  SetConfiguration(0x1A, 0xC0);
  HAL_TIM_PWM_Start(&htim11, TIM_CHANNEL_1); // Start PWM on CHANNEL 1
  for(int i =0; i<melody_length;i++ ){
  if (Musica_Maestro[i].frequency == 0 || Musica_Maestro[i].duration_ms == 0) {
              // Rest or invalid duration
           HAL_TIM_PWM_Stop(&htim11, TIM_CHANNEL_1); // Stop PWM on CHANNEL 1
           if (Musica_Maestro[i].duration_ms > 0) {
               HAL_Delay(Musica_Maestro[i].duration_ms); // Wait for the rest duration
           }
  }else{
      uint32_t arr_value = (TIMER_CLOCK_FREQ / ((uint32_t)1000 * Musica_Maestro[i].frequency)) - 1;
      if (arr_value > 0xFFFF) arr_value = 0xFFFF; // Clamp if frequency too low
      if (arr_value == 0) arr_value = 1;
      __HAL_TIM_SET_PRESCALER(&htim11, arr_value);
      HAL_Delay(Musica_Maestro[i].duration_ms);
      __HAL_TIM_SET_PRESCALER(&htim11, 0);  // pause
      HAL_Delay(100);
          }
    }
  uint8_t pData = 2;
  EEPROM_Write(&hi2c1, EEPROM_ADDR_BOARD_ROLE, &pData, 1); //function to write which Marconi board we are in the EEPROM, useful for testing and to prepare the competition BEWARE. We need one board on 1 (AIRBRAKES), ONE BOARD ON 2 AVNBAY and ONE BOARD ON 3 NOSECONE
  //TODO: SALVARE NELLA EPROM LA CONFIGURAZIONE ABK AVN O NOS @SAMUELE @MICHELE @MARCO @ANDREA
  EEPROM_Read(&hi2c1, EEPROM_ADDR_BOARD_ROLE, &flag_Version, 1); //function to read which Marconi board we are, absolutely indispensable
  if(flag_Version != 1 && flag_Version != 2 && flag_Version != 3  ){
      LED_ON(GPIO_LED3_GPIO_Port, GPIO_LED3_Pin);
  }
  gnss_init();
  /* USER CODE END 2 */
  /* Init scheduler */
  osKernelInitialize();
  /* Create the mutex(es) */
  /* creation of uart4Mutex */
  uart4MutexHandle = osMutexNew(&uart4Mutex_attributes);
  /* USER CODE BEGIN RTOS_MUTEX */
  /* add mutexes, ... */
  /* USER CODE END RTOS_MUTEX */
  /* Create the semaphores(s) */
  /* creation of loraTxDoneSemaphore */
  loraTxDoneSemaphoreHandle = osSemaphoreNew(1, 0, &loraTxDoneSemaphore_attributes);
  /* USER CODE BEGIN RTOS_SEMAPHORES */
  /* add semaphores, ... */
  /* USER CODE END RTOS_SEMAPHORES */
  /* Create the timer(s) */
  /* creation of FrequencyTimer */
  FrequencyTimerHandle = osTimerNew(Frequency_Died, osTimerOnce, NULL, &FrequencyTimer_attributes);
  /* USER CODE BEGIN RTOS_TIMERS */
  /* start timers, add new ones, ... */
  /* USER CODE END RTOS_TIMERS */
  /* Create the queue(s) */
  /* creation of loraTxQueue */
  loraTxQueueHandle = osMessageQueueNew (10, 78, &loraTxQueue_attributes);
  /* creation of loraCmdQueue */
  loraCmdQueueHandle = osMessageQueueNew (5, 3, &loraCmdQueue_attributes);
  /* USER CODE BEGIN RTOS_QUEUES */
  /* add queues, ... */
  /* USER CODE END RTOS_QUEUES */
  /* Create the thread(s) */
  /* creation of Received_Pckg */
  Received_PckgHandle = osThreadNew(StartReceived_Pckg, NULL, &Received_Pckg_attributes);
  /* creation of LoRa_Transmit_T */
  LoRa_Transmit_THandle = osThreadNew(StartLoRaTransmitTask, NULL, &LoRa_Transmit_T_attributes);
  /* creation of LoRaCommandTask */
  LoRaCommandTaskHandle = osThreadNew(StartLoRaCommandTask, NULL, &LoRaCommandTask_attributes);
  /* USER CODE BEGIN RTOS_THREADS */
  /* add threads, ... */
  /* USER CODE END RTOS_THREADS */
  /* USER CODE BEGIN RTOS_EVENTS */
  /* add events, ... */
  /* USER CODE END RTOS_EVENTS */
  /* Start scheduler */
  osKernelStart();
  /* We should never get here as control is now taken by the scheduler */
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */
    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}
References EEPROM_ADDR_BOARD_ROLE, EEPROM_Read(), EEPROM_Write(), flag_Version, Frequency_Died(), FrequencyTimer_attributes, FrequencyTimerHandle, gnss_init(), GPIO_LED3_GPIO_Port, GPIO_LED3_Pin, GPIO_LoRa_M0_GPIO_Port, GPIO_LoRa_M0_Pin, GPIO_LoRa_M1_GPIO_Port, GPIO_LoRa_M1_Pin, hi2c1, htim11, initDWT(), LED_ON, LoRa_Transmit_T_attributes, LoRa_Transmit_THandle, loraCmdQueue_attributes, loraCmdQueueHandle, LoRaCommandTask_attributes, LoRaCommandTaskHandle, loraTxDoneSemaphore_attributes, loraTxDoneSemaphoreHandle, loraTxQueue_attributes, loraTxQueueHandle, melody_length, Musica_Maestro, MX_ADC1_Init(), MX_DMA_Init(), MX_GPIO_Init(), MX_I2C1_Init(), MX_SPI2_Init(), MX_TIM11_Init(), MX_TIM3_Init(), MX_UART4_Init(), MX_UART5_Init(), MX_UART7_Init(), MX_USART1_UART_Init(), MX_USART3_Init(), MX_USART6_UART_Init(), Received_Pckg_attributes, Received_PckgHandle, StartLoRaCommandTask(), StartLoRaTransmitTask(), StartReceived_Pckg(), SystemClock_Config(), TIMER_CLOCK_FREQ, uart4Mutex_attributes, and uart4MutexHandle.
MX_ADC1_Init()
static void MX_ADC1_Init (void) static
ADC1 Initialization Function.
Parameters
None
Return values
None
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 1003 of file main.c.
{
  /* USER CODE BEGIN ADC1_Init 0 */
  /* USER CODE END ADC1_Init 0 */
  ADC_ChannelConfTypeDef sConfig = {0};
  /* USER CODE BEGIN ADC1_Init 1 */
  /* USER CODE END ADC1_Init 1 */
  hadc1.Instance = ADC1;
  hadc1.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;
  hadc1.Init.Resolution = ADC_RESOLUTION_12B;
  hadc1.Init.ScanConvMode = DISABLE;
  hadc1.Init.ContinuousConvMode = DISABLE;
  hadc1.Init.DiscontinuousConvMode = DISABLE;
  hadc1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
  hadc1.Init.ExternalTrigConv = ADC_SOFTWARE_START;
  hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc1.Init.NbrOfConversion = 1;
  hadc1.Init.DMAContinuousRequests = DISABLE;
  hadc1.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  if (HAL_ADC_Init(&hadc1) != HAL_OK)
  {
    Error_Handler();
  }
  sConfig.Channel = ADC_CHANNEL_12;
  sConfig.Rank = 1;
  sConfig.SamplingTime = ADC_SAMPLETIME_3CYCLES;
  if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC1_Init 2 */
  /* USER CODE END ADC1_Init 2 */
}
References Error_Handler(), and hadc1.
Referenced by main().
MX_DMA_Init()
static void MX_DMA_Init (void) static
Enable DMA controller clock
Definition at line 1419 of file main.c.
{
  /* DMA controller clock enable */
  __HAL_RCC_DMA1_CLK_ENABLE();
  __HAL_RCC_DMA2_CLK_ENABLE();
  /* DMA interrupt init */
  /* DMA1_Stream0_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Stream0_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA1_Stream0_IRQn);
  /* DMA1_Stream2_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Stream2_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA1_Stream2_IRQn);
  /* DMA1_Stream4_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Stream4_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA1_Stream4_IRQn);
  /* DMA2_Stream1_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA2_Stream1_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA2_Stream1_IRQn);
  /* DMA2_Stream2_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA2_Stream2_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA2_Stream2_IRQn);
  /* DMA2_Stream6_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA2_Stream6_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA2_Stream6_IRQn);
  /* DMA2_Stream7_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA2_Stream7_IRQn, 5, 0);
  HAL_NVIC_EnableIRQ(DMA2_Stream7_IRQn);
}
Referenced by main().
MX_GPIO_Init()
static void MX_GPIO_Init (void) static
GPIO Initialization Function.
Parameters
None
Return values
None
Definition at line 1456 of file main.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */
  /* USER CODE END MX_GPIO_Init_1 */
  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOC, GPIO_LED2_Pin|GPIO_LED3_Pin|GPIO_Airbrakes_A_UX_Pin|GPIO_Int_XBEE_Sleep_Pin, GPIO_PIN_RESET);
  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOA, GPIO_Ext_XBEE_SPI_UART_CONF_Pin|GPIO_LoRa_M0_Pin|GPIO_LoRa_M1_Pin, GPIO_PIN_RESET);
  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOB, GPIO_Camera_Pin|GPIO_Payload_CS_Pin|EE_Write_Protect_Pin|GPIO_LED1_Pin, GPIO_PIN_RESET);
  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOC, GPIO_Int_XBEE_NRST_Pin|GPIO_TESEO_RST_Pin, GPIO_PIN_SET);
  /*Configure GPIO pins : RTC_calibration_main_battery_removal_detect_Pin GPIO_Marc_DaVinci_Sync_Pin */
  GPIO_InitStruct.Pin = RTC_calibration_main_battery_removal_detect_Pin|GPIO_Marc_DaVinci_Sync_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
  /*Configure GPIO pins : GPIO_LED2_Pin GPIO_LED3_Pin GPIO_Airbrakes_A_UX_Pin GPIO_Int_XBEE_Sleep_Pin
                           GPIO_Int_XBEE_NRST_Pin */
  GPIO_InitStruct.Pin = GPIO_LED2_Pin|GPIO_LED3_Pin|GPIO_Airbrakes_A_UX_Pin|GPIO_Int_XBEE_Sleep_Pin
                          |GPIO_Int_XBEE_NRST_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
  /*Configure GPIO pins : GPIO_Ext_XBEE_SPI_UART_CONF_Pin GPIO_LoRa_M0_Pin GPIO_LoRa_M1_Pin */
  GPIO_InitStruct.Pin = GPIO_Ext_XBEE_SPI_UART_CONF_Pin|GPIO_LoRa_M0_Pin|GPIO_LoRa_M1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  /*Configure GPIO pins : GPIO_LoRa_AUX_Pin GPIO_TESEO_PPS_Input_Pin */
  GPIO_InitStruct.Pin = GPIO_LoRa_AUX_Pin|GPIO_TESEO_PPS_Input_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  /*Configure GPIO pin : GPIO_Camera_Pin */
  GPIO_InitStruct.Pin = GPIO_Camera_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_PULLDOWN;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIO_Camera_GPIO_Port, &GPIO_InitStruct);
  /*Configure GPIO pins : GPIO_Payload_CS_Pin EE_Write_Protect_Pin GPIO_LED1_Pin */
  GPIO_InitStruct.Pin = GPIO_Payload_CS_Pin|EE_Write_Protect_Pin|GPIO_LED1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
  /*Configure GPIO pin : GPIO_TESEO_RST_Pin */
  GPIO_InitStruct.Pin = GPIO_TESEO_RST_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIO_TESEO_RST_GPIO_Port, &GPIO_InitStruct);
  /* USER CODE BEGIN MX_GPIO_Init_2 */
  /* USER CODE END MX_GPIO_Init_2 */
}
References EE_Write_Protect_Pin, GPIO_Airbrakes_A_UX_Pin, GPIO_Camera_GPIO_Port, GPIO_Camera_Pin, GPIO_Ext_XBEE_SPI_UART_CONF_Pin, GPIO_Int_XBEE_NRST_Pin, GPIO_Int_XBEE_Sleep_Pin, GPIO_LED1_Pin, GPIO_LED2_Pin, GPIO_LED3_Pin, GPIO_LoRa_AUX_Pin, GPIO_LoRa_M0_Pin, GPIO_LoRa_M1_Pin, GPIO_Marc_DaVinci_Sync_Pin, GPIO_Payload_CS_Pin, GPIO_TESEO_PPS_Input_Pin, GPIO_TESEO_RST_GPIO_Port, GPIO_TESEO_RST_Pin, and RTC_calibration_main_battery_removal_detect_Pin.
Referenced by main().
MX_I2C1_Init()
static void MX_I2C1_Init (void) static
I2C1 Initialization Function.
Parameters
None
Return values
None
Definition at line 1055 of file main.c.
{
  /* USER CODE BEGIN I2C1_Init 0 */
  /* USER CODE END I2C1_Init 0 */
  /* USER CODE BEGIN I2C1_Init 1 */
  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.ClockSpeed = 100000;
  hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */
  /* USER CODE END I2C1_Init 2 */
}
References Error_Handler(), and hi2c1.
Referenced by main().
MX_SPI2_Init()
static void MX_SPI2_Init (void) static
SPI2 Initialization Function.
Parameters
None
Return values
None
Definition at line 1089 of file main.c.
{
  /* USER CODE BEGIN SPI2_Init 0 */
  /* USER CODE END SPI2_Init 0 */
  /* USER CODE BEGIN SPI2_Init 1 */
  /* USER CODE END SPI2_Init 1 */
  /* SPI2 parameter configuration*/
  hspi2.Instance = SPI2;
  hspi2.Init.Mode = SPI_MODE_MASTER;
  hspi2.Init.Direction = SPI_DIRECTION_2LINES;
  hspi2.Init.DataSize = SPI_DATASIZE_8BIT;
  hspi2.Init.CLKPolarity = SPI_POLARITY_LOW;
  hspi2.Init.CLKPhase = SPI_PHASE_1EDGE;
  hspi2.Init.NSS = SPI_NSS_SOFT;
  hspi2.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2;
  hspi2.Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi2.Init.TIMode = SPI_TIMODE_DISABLE;
  hspi2.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
  hspi2.Init.CRCPolynomial = 10;
  if (HAL_SPI_Init(&hspi2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN SPI2_Init 2 */
  /* USER CODE END SPI2_Init 2 */
}
References Error_Handler(), and hspi2.
Referenced by main().
MX_TIM11_Init()
static void MX_TIM11_Init (void) static
TIM11 Initialization Function.
Parameters
None
Return values
None
Definition at line 1176 of file main.c.
{
  /* USER CODE BEGIN TIM11_Init 0 */
  /* USER CODE END TIM11_Init 0 */
  TIM_OC_InitTypeDef sConfigOC = {0};
  /* USER CODE BEGIN TIM11_Init 1 */
  /* USER CODE END TIM11_Init 1 */
  htim11.Instance = TIM11;
  htim11.Init.Prescaler = 0;
  htim11.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim11.Init.Period = 1000;
  htim11.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim11.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim11) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_TIM_PWM_Init(&htim11) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 500;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  if (HAL_TIM_PWM_ConfigChannel(&htim11, &sConfigOC, TIM_CHANNEL_1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM11_Init 2 */
  /* USER CODE END TIM11_Init 2 */
  HAL_TIM_MspPostInit(&htim11);
}
References Error_Handler(), HAL_TIM_MspPostInit(), and htim11.
Referenced by main().
MX_TIM3_Init()
static void MX_TIM3_Init (void) static
TIM3 Initialization Function.
Parameters
None
Return values
None
Definition at line 1127 of file main.c.
{
  /* USER CODE BEGIN TIM3_Init 0 */
  /* USER CODE END TIM3_Init 0 */
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};
  /* USER CODE BEGIN TIM3_Init 1 */
  /* USER CODE END TIM3_Init 1 */
  htim3.Instance = TIM3;
  htim3.Init.Prescaler = 0;
  htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim3.Init.Period = 65535;
  htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_PWM_Init(&htim3) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim3, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 0;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  if (HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_3) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM3_Init 2 */
  /* USER CODE END TIM3_Init 2 */
  HAL_TIM_MspPostInit(&htim3);
}
References Error_Handler(), HAL_TIM_MspPostInit(), and htim3.
Referenced by main().
MX_UART4_Init()
static void MX_UART4_Init (void) static
UART4 Initialization Function.
Parameters
None
Return values
None
Definition at line 1222 of file main.c.
{
  /* USER CODE BEGIN UART4_Init 0 */
  /* USER CODE END UART4_Init 0 */
  /* USER CODE BEGIN UART4_Init 1 */
  /* USER CODE END UART4_Init 1 */
  huart4.Instance = UART4;
  huart4.Init.BaudRate = 9600;
  huart4.Init.WordLength = UART_WORDLENGTH_8B;
  huart4.Init.StopBits = UART_STOPBITS_1;
  huart4.Init.Parity = UART_PARITY_NONE;
  huart4.Init.Mode = UART_MODE_TX_RX;
  huart4.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart4.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart4) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN UART4_Init 2 */
  /* USER CODE END UART4_Init 2 */
}
References Error_Handler(), and huart4.
Referenced by main().
MX_UART5_Init()
static void MX_UART5_Init (void) static
UART5 Initialization Function.
Parameters
None
Return values
None
Definition at line 1255 of file main.c.
{
  /* USER CODE BEGIN UART5_Init 0 */
  /* USER CODE END UART5_Init 0 */
  /* USER CODE BEGIN UART5_Init 1 */
  /* USER CODE END UART5_Init 1 */
  huart5.Instance = UART5;
  huart5.Init.BaudRate = 9600;
  huart5.Init.WordLength = UART_WORDLENGTH_8B;
  huart5.Init.StopBits = UART_STOPBITS_1;
  huart5.Init.Parity = UART_PARITY_NONE;
  huart5.Init.Mode = UART_MODE_TX_RX;
  huart5.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart5.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart5) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN UART5_Init 2 */
  /* USER CODE END UART5_Init 2 */
}
References Error_Handler(), and huart5.
Referenced by main().
MX_UART7_Init()
static void MX_UART7_Init (void) static
UART7 Initialization Function.
Parameters
None
Return values
None
Definition at line 1288 of file main.c.
{
  /* USER CODE BEGIN UART7_Init 0 */
  /* USER CODE END UART7_Init 0 */
  /* USER CODE BEGIN UART7_Init 1 */
  /* USER CODE END UART7_Init 1 */
  huart7.Instance = UART7;
  huart7.Init.BaudRate = 115200;
  huart7.Init.WordLength = UART_WORDLENGTH_8B;
  huart7.Init.StopBits = UART_STOPBITS_1;
  huart7.Init.Parity = UART_PARITY_NONE;
  huart7.Init.Mode = UART_MODE_TX_RX;
  huart7.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart7.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart7) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN UART7_Init 2 */
  /* USER CODE END UART7_Init 2 */
}
References Error_Handler(), and huart7.
Referenced by main().
MX_USART1_UART_Init()
static void MX_USART1_UART_Init (void) static
USART1 Initialization Function.
Parameters
None
Return values
None
Definition at line 1321 of file main.c.
{
  /* USER CODE BEGIN USART1_Init 0 */
  /* USER CODE END USART1_Init 0 */
  /* USER CODE BEGIN USART1_Init 1 */
  /* USER CODE END USART1_Init 1 */
  huart1.Instance = USART1;
  huart1.Init.BaudRate = 1843200;
  huart1.Init.WordLength = UART_WORDLENGTH_8B;
  huart1.Init.StopBits = UART_STOPBITS_1;
  huart1.Init.Parity = UART_PARITY_NONE;
  huart1.Init.Mode = UART_MODE_TX_RX;
  huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart1.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART1_Init 2 */
  /* USER CODE END USART1_Init 2 */
}
References Error_Handler(), and huart1.
Referenced by main().
MX_USART3_Init()
static void MX_USART3_Init (void) static
USART3 Initialization Function.
Parameters
None
Return values
None
Definition at line 1354 of file main.c.
{
  /* USER CODE BEGIN USART3_Init 0 */
  /* USER CODE END USART3_Init 0 */
  /* USER CODE BEGIN USART3_Init 1 */
  /* USER CODE END USART3_Init 1 */
  husart3.Instance = USART3;
  husart3.Init.BaudRate = 115200;
  husart3.Init.WordLength = USART_WORDLENGTH_8B;
  husart3.Init.StopBits = USART_STOPBITS_1;
  husart3.Init.Parity = USART_PARITY_NONE;
  husart3.Init.Mode = USART_MODE_TX_RX;
  husart3.Init.CLKPolarity = USART_POLARITY_LOW;
  husart3.Init.CLKPhase = USART_PHASE_1EDGE;
  husart3.Init.CLKLastBit = USART_LASTBIT_DISABLE;
  if (HAL_USART_Init(&husart3) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART3_Init 2 */
  /* USER CODE END USART3_Init 2 */
}
References Error_Handler(), and husart3.
Referenced by main().
MX_USART6_UART_Init()
static void MX_USART6_UART_Init (void) static
USART6 Initialization Function.
Parameters
None
Return values
None
Definition at line 1388 of file main.c.
{
  /* USER CODE BEGIN USART6_Init 0 */
  /* USER CODE END USART6_Init 0 */
  /* USER CODE BEGIN USART6_Init 1 */
  /* USER CODE END USART6_Init 1 */
  huart6.Instance = USART6;
  huart6.Init.BaudRate = 921600;
  huart6.Init.WordLength = UART_WORDLENGTH_8B;
  huart6.Init.StopBits = UART_STOPBITS_1;
  huart6.Init.Parity = UART_PARITY_NONE;
  huart6.Init.Mode = UART_MODE_TX_RX;
  huart6.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart6.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart6) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART6_Init 2 */
  /* USER CODE END USART6_Init 2 */
}
References Error_Handler(), and huart6.
Referenced by main().
StartLoRaCommandTask()
void StartLoRaCommandTask (void * argument)
RTOS Task: LoRa Command Task.
This task processes incoming commands from the Ground Station.
Starts by arming the UART4 DMA (dmaBuffer).
Waits for a command to arrive in loraCmdQueue (put by UART4 ISR).
Acquires uart4Mutex to safely reconfigure the LoRa module.
Aborts any pending TX/RX on UART4 to take control.
Calls processMessage to handle the command (e.g., change frequency).
Re-arms the UART4 DMA to listen for the next command.
Releases the uart4Mutex.
Parameters
argument Not used
Return values
None
Definition at line 1738 of file main.c.
{
  /* USER CODE BEGIN StartLoRaCommandTask */
    uint8_t cmd_data_from_queue[DMA_BUFFER_SIZE_EXT];
    osStatus_t q_status;
    // Initial arming of UART4 DMA RX for commands from ground station.
    // This needs to happen once after UART4 is initialized.
    // A small delay can be good to ensure peripheral is stable.
    osDelay(100);
    if (HAL_UART_Receive_DMA(&huart4, dmaBuffer, DMA_BUFFER_SIZE_EXT) != HAL_OK) {
          Error_Handler(); // Or log and retry
    }
  /* Infinite loop */
  for(;;)
  {
      q_status = osMessageQueueGet(loraCmdQueueHandle, cmd_data_from_queue, NULL, osWaitForever);
      if (q_status == osOK) {
          uint8_t command_byte = cmd_data_from_queue[0];
          uint8_t *data_bytes = cmd_data_from_queue+1;
          // Acquire mutex before accessing LoRa module (UART4) for configuration
          if (osMutexAcquire(uart4MutexHandle, osWaitForever) == osOK) {
              // At this point, LoRaCommandTask has exclusive access to UART4.
              // The main UART4 RX DMA (for ground station commands) was NOT re-armed in the ISR.
              // So, SetConfiguration can safely use HAL_UART_Transmit/Receive (blocking).
              // Abort any ongoing UART4 TX from LoRaTransmitTask if it was interleaved.
              // if LoRaCommandTask needs immediate, clean access.
              if (huart4.gState != HAL_UART_STATE_READY || huart4.RxState != HAL_UART_STATE_READY) {
                  HAL_UART_Abort(&huart4);
                  // Aborting calls Tx/Rx Cplt callbacks with HAL_UART_ERROR_ABORT.
                  //This is done so that we have time to do our frequency change
              }
              processMessage(command_byte, data_bytes); // Calls LoRa_SetChannel -> SetConfiguration
              if (HAL_UART_Receive_DMA(&huart4, dmaBuffer, DMA_BUFFER_SIZE_EXT) != HAL_OK) {
                  // Error handling: Failed to re-arm DMA reception
                  Error_Handler();
              }
              osMutexRelease(uart4MutexHandle);
          } else {
              Error_Handler();
          }
      }
  }
  /* USER CODE END StartLoRaCommandTask */
}
References DMA_BUFFER_SIZE_EXT, dmaBuffer, Error_Handler(), huart4, loraCmdQueueHandle, processMessage(), and uart4MutexHandle.
Referenced by main().
StartLoRaTransmitTask()
void StartLoRaTransmitTask (void * argument)
RTOS Task: LoRa Transmit Task.
This task acts as a serialized transmitter for the LoRa module.
Waits for a packet to arrive in loraTxQueue.
Acquires the uart4Mutex to get exclusive access to the LoRa.
Checks the Acked state (part of a simple ACK protocol).
Transmits the data packet via UART4 DMA (prescaled to ~1Hz).
Releases the uart4Mutex.
Parameters
argument Not used
Return values
None
Definition at line 1657 of file main.c.
{
  /* USER CODE BEGIN StartLoRaTransmitTask */
    uint8_t msg_to_transmit[sizeof(message_gs)];
    osStatus_t status;
    //bool first_message = true; ACK system , not used for now
    static uint32_t prescaler = 0;
  /* Infinite loop */
  for(;;)
  {
          status = osMessageQueueGet(loraTxQueueHandle, msg_to_transmit, NULL, osWaitForever);
          if (status == osOK)
          {
             //t1 = DWT->CYCCNT;
             if (osMutexAcquire(uart4MutexHandle, osWaitForever) == osOK) {
                 //------------------------------------------------------------------------------ ACK system , not used for now
                 //if(first_message) {
                     //E220_WaitAuxHigh(1000);
                     //HAL_UART_Transmit_DMA(&huart4, ack_S, sizeof(ack_S));
                //   first_message = false;
                 //}
                 //------------------------------------------------------------------------------ ACK system , not used for now
                 E220_WaitAuxHigh(1000);
                 if(Acked){
                     ++prescaler; //prescaler system is a tinkering to send a message to the gs every second rather than every half second //TODO try sending every 500 ms after increasing the baud rate
                     if(prescaler ==2){
                         prescaler =0;
                         HAL_UART_Transmit_DMA(&huart4, msg_to_transmit, sizeof(message_gs));
                     }
                 }
                 else{
                     HAL_UART_Transmit_DMA(&huart4, (uint8_t*) ACK, sizeof(ACK));
                 }
                 E220_WaitAuxHigh(1000);
                 //------------------------------------------------------------------------------ ACK system , not used for now
                 //uint32_t count = osMessageQueueGetCount(loraTxQueueHandle);
                 //if(count == 0){
                          //HAL_UART_Transmit_DMA(&huart4, ack_E, sizeof(ack_E));
                          //E220_WaitAuxHigh(1000);
                          //first_message = true;
                 //}
                 //------------------------------------------------------------------------------ ACK system , not used for now
                 osMutexRelease(uart4MutexHandle);
             }
         }
             //t2 = DWT->CYCCNT;
             //diff = t2 - t1;
             //uint64_t diff_64 = (uint64_t)diff;
             //uint64_t time_ms = (diff_64 * 1000ULL) / SystemCoreClock; // for microseconds : 1000000ULL nanoseconds 1000000000ULL
  }
  /* USER CODE END StartLoRaTransmitTask */
}
References ACK, Acked, E220_WaitAuxHigh(), huart4, loraTxQueueHandle, message_gs, and uart4MutexHandle.
Referenced by main().
StartReceived_Pckg()
void StartReceived_Pckg (void * argument)
RTOS Task: Received Package Handler.
This is the central data processing task.
Waits for RECEIVED_FLAG (set by UART ISRs).
Reads the ADC for battery voltage (adc).
If AVNBAY/NOSECONE: Processes message from DaVinci.
If AIRBRAKES: Processes dmaBuffer_2 for new angle, moves servo.
If AVNBAY: Relays airbrakes_deg to the Airbrakes board (UART6).
Constructs the message_gs telemetry packet (temp_message_gs_buffer).
Puts the message_gs packet into the loraTxQueue.
Parameters
argument Not used
Return values
None
Definition at line 1557 of file main.c.
{
  /* USER CODE BEGIN 5 */
  if(flag_Version == BOARD_ROLE_AVNBAY || flag_Version == BOARD_ROLE_NOSECONE){
          HAL_UART_Receive_DMA(&huart1, message, sizeof(message));
      }
  if( flag_Version == BOARD_ROLE_AIRBRAKES){
      HAL_UART_Receive_DMA(&huart6, dmaBuffer_2, DMA_BUFFER_SIZE_INT);
      airbrakes_init();
  }
  static uint32_t prescaler = 0;
  uint8_t temp_message_gs_buffer[sizeof(message_gs)]; // Create a temporary local buffer
  /* Infinite loop */
  for(;;)
  {
         osThreadFlagsWait(RECEIVED_FLAG, osFlagsWaitAny, osWaitForever);
         HAL_ADC_Start(&hadc1);
         HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
         uint32_t adcVal = HAL_ADC_GetValue(&hadc1);
         HAL_ADC_Stop(&hadc1);
         Vin=((adcVal/3180.0f)*3.09f);
         memset(temp_message_gs_buffer, 0, sizeof(temp_message_gs_buffer));
         /*The batteryVolts variable is calculating the battery percentage between 9v to 7v as we want to
          * see battery percentage at which the system is operational not to see the complete 0v,because the system will
          * already be dead at 7v,and the ground station should not be seeing a dead system at 70% they would be definitely mad.
          * The ADC has the 4096 representable value which means the (2v/4096)*adcValue +7(where 7 is acting as the final bound).
          * the resolution of ADC is 488.28uV which mean each decrement of beautiful amount on the left will decrease 1%*/
          adc= (Vin*((2700.0f+4700.0f)/2700.0f));
         ((uint8_t*)temp_message_gs_buffer )[0] = '~';
         memcpy((uint8_t*)temp_message_gs_buffer  + sizeof(message) + 10, &adc, sizeof(float));
         memcpy((uint8_t*)temp_message_gs_buffer  + sizeof(message) + 2, &teseo_longitude, sizeof(float));
         memcpy((uint8_t*)temp_message_gs_buffer  + sizeof(message) + 6, &teseo_latitude, sizeof(float));
         ((uint8_t*)temp_message_gs_buffer )[sizeof(message_gs) - 1] = '!';
         if(flag_Version == BOARD_ROLE_AIRBRAKES){
             ((uint8_t*)temp_message_gs_buffer )[1] = 'p';
             memcpy((uint8_t*)temp_message_gs_buffer  + 55, &airbrakes_deg, sizeof(airbrakes_deg));
             // Update the servo position based on the received value
             servo_moveto_deg(&airbrakes, airbrakes_deg);
         }
         else {
             memcpy((uint8_t*)temp_message_gs_buffer  +2, (uint8_t*)message, sizeof(message));
             if(flag_Version == BOARD_ROLE_NOSECONE){
                 ((uint8_t*)temp_message_gs_buffer )[1] = 'D';
             }
             else{ //if AVNBAY
                 memcpy(&packet, (uint8_t*)message, sizeof(message));
                 airbrakes_deg = packet.deg;
                 HAL_UART_Transmit_DMA(&huart6, (uint8_t*)&airbrakes_deg, sizeof(airbrakes_deg));
                 ((uint8_t*)temp_message_gs_buffer )[1] = 'A';
             }
         }
         // LED toggling for live debugging
         ++prescaler;
         if (prescaler == 2)  // 1 second
            {
                 prescaler = 0;
            //        //toggle_led();
                LED_TOGGLE(GPIO_LED2_GPIO_Port,GPIO_LED2_Pin);
         }
         // LED toggling for live debugging
         // Send the constructed message to the LoRa transmit queue
         if(flag_Version == BOARD_ROLE_NOSECONE || flag_Version == BOARD_ROLE_AVNBAY){ //------------------------------------------EXCEPTIONALLY ADDED THIS "IF" because the marconi in the airbrakes will fly without a LoRa in the IREC competition
             if (osMessageQueuePut(loraTxQueueHandle, temp_message_gs_buffer , 0U, osWaitForever) != osOK)
                 {
                 // Handle error: Queue full or invalid. Should not happen with osWaitForever unless queue is broken.
                 Error_Handler();
                 }
         }
  }
  /* USER CODE END 5 */
}
References adc, airbrakes, airbrakes_deg, airbrakes_init(), BOARD_ROLE_AIRBRAKES, BOARD_ROLE_AVNBAY, BOARD_ROLE_NOSECONE, Data_Package_From_DAVINKI::deg, DMA_BUFFER_SIZE_INT, dmaBuffer_2, Error_Handler(), flag_Version, GPIO_LED2_GPIO_Port, GPIO_LED2_Pin, hadc1, huart1, huart6, LED_TOGGLE, loraTxQueueHandle, message, message_gs, packet, RECEIVED_FLAG, servo_moveto_deg(), teseo_latitude, teseo_longitude, and Vin.
Referenced by main().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 956 of file main.c.
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 5;
  RCC_OscInitStruct.PLL.PLLN = 100;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK)
  {
    Error_Handler();
  }
}
References Error_Handler().
Referenced by main().
Variable Documentation
FrequencyTimer_attributes
const osTimerAttr_t FrequencyTimer_attributes
Initial value:
= {
  .name = "FrequencyTimer"
}
Definition at line 175 of file main.c.
Referenced by main().
FrequencyTimerHandle
osTimerId_t FrequencyTimerHandle
Definition at line 174 of file main.c.
Referenced by main(), and processMessage().
hadc1
ADC_HandleTypeDef hadc1
Definition at line 119 of file main.c.
Referenced by MX_ADC1_Init(), and StartReceived_Pckg().
hdma_uart4_rx
DMA_HandleTypeDef hdma_uart4_rx
Definition at line 134 of file main.c.
hdma_uart4_tx
DMA_HandleTypeDef hdma_uart4_tx
Definition at line 135 of file main.c.
hdma_uart5_rx
DMA_HandleTypeDef hdma_uart5_rx
Definition at line 136 of file main.c.
hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_rx
Definition at line 137 of file main.c.
hdma_usart1_tx
DMA_HandleTypeDef hdma_usart1_tx
Definition at line 138 of file main.c.
hdma_usart6_rx
DMA_HandleTypeDef hdma_usart6_rx
Definition at line 139 of file main.c.
hdma_usart6_tx
DMA_HandleTypeDef hdma_usart6_tx
Definition at line 140 of file main.c.
hi2c1
I2C_HandleTypeDef hi2c1
Definition at line 121 of file main.c.
Referenced by main(), and MX_I2C1_Init().
hspi2
SPI_HandleTypeDef hspi2
Definition at line 123 of file main.c.
Referenced by MX_SPI2_Init().
htim11
TIM_HandleTypeDef htim11
Definition at line 126 of file main.c.
Referenced by main(), and MX_TIM11_Init().
htim3
TIM_HandleTypeDef htim3
HAL Timer handle for TIM3 (Servo PWM).
Definition at line 125 of file main.c.
Referenced by MX_TIM3_Init().
huart1
UART_HandleTypeDef huart1
Definition at line 131 of file main.c.
Referenced by HAL_UART_ErrorCallback(), HAL_UART_RxCpltCallback(), HAL_UARTEx_RxEventCallback(), MX_USART1_UART_Init(), and StartReceived_Pckg().
huart4
UART_HandleTypeDef huart4
HAL UART handle for UART4 (External XBEE).
Definition at line 128 of file main.c.
Referenced by HAL_UART_ErrorCallback(), HAL_UART_RxCpltCallback(), MX_UART4_Init(), SetConfiguration(), StartLoRaCommandTask(), and StartLoRaTransmitTask().
huart5
UART_HandleTypeDef huart5
HAL UART handle for UART5 (TESEO GNSS).
Definition at line 129 of file main.c.
Referenced by gnss_begin_dma(), HAL_UARTEx_RxEventCallback(), and MX_UART5_Init().
huart6
UART_HandleTypeDef huart6
Definition at line 133 of file main.c.
Referenced by HAL_UART_RxCpltCallback(), MX_USART6_UART_Init(), and StartReceived_Pckg().
huart7
UART_HandleTypeDef huart7
Definition at line 130 of file main.c.
Referenced by MX_UART7_Init().
husart3
USART_HandleTypeDef husart3
Definition at line 132 of file main.c.
Referenced by MX_USART3_Init().
LoRa_Transmit_T_attributes
const osThreadAttr_t LoRa_Transmit_T_attributes
Initial value:
= {
  .name = "LoRa_Transmit_T",
  .stack_size = 256 * 4,
  .priority = (osPriority_t) osPriorityLow,
}
Definition at line 151 of file main.c.
Referenced by main().
LoRa_Transmit_THandle
osThreadId_t LoRa_Transmit_THandle
Definition at line 150 of file main.c.
Referenced by main().
loraCmdQueue_attributes
const osMessageQueueAttr_t loraCmdQueue_attributes
Initial value:
= {
  .name = "loraCmdQueue"
}
Definition at line 170 of file main.c.
Referenced by main().
loraCmdQueueHandle
osMessageQueueId_t loraCmdQueueHandle
Definition at line 169 of file main.c.
Referenced by HAL_UART_RxCpltCallback(), main(), and StartLoRaCommandTask().
LoRaCommandTask_attributes
const osThreadAttr_t LoRaCommandTask_attributes
Initial value:
= {
  .name = "LoRaCommandTask",
  .stack_size = 256 * 4,
  .priority = (osPriority_t) osPriorityBelowNormal,
}
Definition at line 158 of file main.c.
Referenced by main().
LoRaCommandTaskHandle
osThreadId_t LoRaCommandTaskHandle
Definition at line 157 of file main.c.
Referenced by main().
loraTxDoneSemaphore_attributes
const osSemaphoreAttr_t loraTxDoneSemaphore_attributes
Initial value:
= {
  .name = "loraTxDoneSemaphore"
}
Definition at line 185 of file main.c.
Referenced by main().
loraTxDoneSemaphoreHandle
osSemaphoreId_t loraTxDoneSemaphoreHandle
Definition at line 184 of file main.c.
Referenced by main().
loraTxQueue_attributes
const osMessageQueueAttr_t loraTxQueue_attributes
Initial value:
= {
  .name = "loraTxQueue"
}
Definition at line 165 of file main.c.
Referenced by main().
loraTxQueueHandle
osMessageQueueId_t loraTxQueueHandle
Definition at line 164 of file main.c.
Referenced by main(), StartLoRaTransmitTask(), and StartReceived_Pckg().
melody_length
uint16_t melody_length = sizeof(Musica_Maestro) / sizeof(Note)
Definition at line 437 of file main.c.
Referenced by main().
Received_Pckg_attributes
const osThreadAttr_t Received_Pckg_attributes
Initial value:
= {
  .name = "Received_Pckg",
  .stack_size = 128 * 4,
  .priority = (osPriority_t) osPriorityNormal,
}
Definition at line 144 of file main.c.
Referenced by main().
Received_PckgHandle
osThreadId_t Received_PckgHandle
Definition at line 143 of file main.c.
Referenced by HAL_UART_RxCpltCallback(), and main().
uart4Mutex_attributes
const osMutexAttr_t uart4Mutex_attributes
Initial value:
= {
  .name = "uart4Mutex"
}
Definition at line 180 of file main.c.
Referenced by main().
uart4MutexHandle
osMutexId_t uart4MutexHandle
Definition at line 179 of file main.c.
Referenced by main(), StartLoRaCommandTask(), and StartLoRaTransmitTask().