Marconi Firmware: Airbrake Control
Airbrake Control
Manages the airbrake servo system.
Modules
Airbrake Servo Configuration
Constants defining the servo's pulse widths, angle limits, and hardware resources.
Default Timer Configuration
Default hardware timing constants for PWM generation.
Servo Driver Functions
Public API for controlling a servo motor.
Data Structures
struct servo_t
Main structure for holding servo configuration and state.
Functions
void airbrakes_init ()
Initializes the airbrake servo.
Variables
float airbrakes_deg = 0.0f
Current target airbrakes angle (degrees).
servo_t airbrakes
Global servo object for the airbrake system.
Detailed Description
Manages the airbrake servo system.
Includes the servo driver and any logic to command the airbrake position.
Function Documentation
airbrakes_init()
void airbrakes_init ()
Initializes the airbrake servo.
This function calls servo_init() to configure the global airbrakes servo object using the defined hardware settings. It also sets the initial position of the airbrakes by moving the servo to its maximum angle (180.0 degrees).
Definition at line 18 of file airbrakes.c.
                      {
    servo_init(&airbrakes, PWM_FREQ, TARGET_ARR);
    servo_moveto_deg(&airbrakes, 180.0);
}
References airbrakes, PWM_FREQ, servo_init(), servo_moveto_deg(), and TARGET_ARR.
Referenced by StartReceived_Pckg().
Variable Documentation
airbrakes
airbrakes extern
Global servo object for the airbrake system.
This object holds the state and configuration of the airbrake servo, initialized in Airbrakes.c.
Definition at line 5 of file airbrakes.c.
Referenced by airbrakes_init(), and StartReceived_Pckg().
airbrakes_deg
float airbrakes_deg = 0.0f
Current target airbrakes angle (degrees).
Definition at line 223 of file main.c.
Referenced by HAL_UART_RxCpltCallback(), and StartReceived_Pckg().