Da Vinci Firmware: LSM6DSO32_significant_motion
LSM6DSO32_significant_motion
Peripheral Drivers » "LSM6DSO32 IMU Driver"
This section groups all the functions that manage the significant motion detection.
Functions
int32_t lsm6dso32_motion_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable significant motion detection function.[set].
int32_t lsm6dso32_motion_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable significant motion detection function.[get].
int32_t lsm6dso32_motion_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Interrupt status bit for significant motion detection.[get].
Detailed Description
This section groups all the functions that manage the significant motion detection.
Function Documentation
lsm6dso32_motion_flag_data_ready_get()
int32_t lsm6dso32_motion_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Interrupt status bit for significant motion detection.[get].
Parameters
ctx read / write interface definitions
val change the values of is_sigmot in reg EMB_FUNC_STATUS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7350 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_status_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_STATUS,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.is_sigmot;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_status_t::is_sigmot, LSM6DSO32_EMB_FUNC_STATUS, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_motion_sens_get()
int32_t lsm6dso32_motion_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable significant motion detection function.[get].
Parameters
ctx read / write interface definitions
val change the values of sign_motion_en in reg EMB_FUNC_EN_A
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7320 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_en_a_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.sign_motion_en;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMB_FUNC_EN_A, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, and lsm6dso32_emb_func_en_a_t::sign_motion_en.
lsm6dso32_motion_sens_set()
int32_t lsm6dso32_motion_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable significant motion detection function.[set].
Parameters
ctx read / write interface definitions
val change the values of sign_motion_en in reg EMB_FUNC_EN_A
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7284 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_en_a_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg.sign_motion_en = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMB_FUNC_EN_A, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_write_reg(), and lsm6dso32_emb_func_en_a_t::sign_motion_en.