Da Vinci Firmware: LSM6DSO32_Interfaces_Functions
LSM6DSO32_Interfaces_Functions
Peripheral Drivers » "LSM6DSO32 IMU Driver"
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Functions
int32_t __weak lsm6dso32_read_reg (stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t __weak lsm6dso32_write_reg (stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
Detailed Description
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Function Documentation
lsm6dso32_read_reg()
int32_t __weak lsm6dso32_read_reg (stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 54 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = ctx->read_reg(ctx->handle, reg, data, len);
  return ret;
}
References stmdev_ctx_t::handle, and stmdev_ctx_t::read_reg.
Referenced by lsm6dso32_4d_mode_get(), lsm6dso32_4d_mode_set(), lsm6dso32_6d_threshold_get(), lsm6dso32_6d_threshold_set(), lsm6dso32_acceleration_raw_get(), lsm6dso32_act_mode_get(), lsm6dso32_act_mode_set(), lsm6dso32_act_pin_notification_get(), lsm6dso32_act_pin_notification_set(), lsm6dso32_act_sleep_dur_get(), lsm6dso32_act_sleep_dur_set(), lsm6dso32_all_on_int1_get(), lsm6dso32_all_on_int1_set(), lsm6dso32_all_sources_get(), lsm6dso32_angular_rate_raw_get(), lsm6dso32_auto_increment_get(), lsm6dso32_auto_increment_set(), lsm6dso32_batch_counter_threshold_get(), lsm6dso32_batch_counter_threshold_set(), lsm6dso32_block_data_update_get(), lsm6dso32_block_data_update_set(), lsm6dso32_boot_get(), lsm6dso32_boot_set(), lsm6dso32_compression_algo_get(), lsm6dso32_compression_algo_init_get(), lsm6dso32_compression_algo_init_set(), lsm6dso32_compression_algo_real_time_get(), lsm6dso32_compression_algo_real_time_set(), lsm6dso32_compression_algo_set(), lsm6dso32_data_ready_mode_get(), lsm6dso32_data_ready_mode_set(), lsm6dso32_den_enable_get(), lsm6dso32_den_enable_set(), lsm6dso32_den_mark_axis_x_get(), lsm6dso32_den_mark_axis_x_set(), lsm6dso32_den_mark_axis_y_get(), lsm6dso32_den_mark_axis_y_set(), lsm6dso32_den_mark_axis_z_get(), lsm6dso32_den_mark_axis_z_set(), lsm6dso32_den_mode_get(), lsm6dso32_den_mode_set(), lsm6dso32_den_polarity_get(), lsm6dso32_den_polarity_set(), lsm6dso32_device_id_get(), lsm6dso32_emb_fsm_en_get(), lsm6dso32_emb_fsm_en_set(), lsm6dso32_ff_dur_get(), lsm6dso32_ff_dur_set(), lsm6dso32_ff_threshold_get(), lsm6dso32_ff_threshold_set(), lsm6dso32_fifo_cnt_event_batch_get(), lsm6dso32_fifo_cnt_event_batch_set(), lsm6dso32_fifo_data_level_get(), lsm6dso32_fifo_full_flag_get(), lsm6dso32_fifo_gy_batch_get(), lsm6dso32_fifo_gy_batch_set(), lsm6dso32_fifo_mode_get(), lsm6dso32_fifo_mode_set(), lsm6dso32_fifo_out_raw_get(), lsm6dso32_fifo_ovr_flag_get(), lsm6dso32_fifo_pedo_batch_get(), lsm6dso32_fifo_pedo_batch_set(), lsm6dso32_fifo_sensor_tag_get(), lsm6dso32_fifo_status_get(), lsm6dso32_fifo_stop_on_wtm_get(), lsm6dso32_fifo_stop_on_wtm_set(), lsm6dso32_fifo_temp_batch_get(), lsm6dso32_fifo_temp_batch_set(), lsm6dso32_fifo_timestamp_decimation_get(), lsm6dso32_fifo_timestamp_decimation_set(), lsm6dso32_fifo_virtual_sens_odr_chg_get(), lsm6dso32_fifo_virtual_sens_odr_chg_set(), lsm6dso32_fifo_watermark_get(), lsm6dso32_fifo_watermark_set(), lsm6dso32_fifo_wtm_flag_get(), lsm6dso32_fifo_xl_batch_get(), lsm6dso32_fifo_xl_batch_set(), lsm6dso32_filter_settling_mask_get(), lsm6dso32_filter_settling_mask_set(), lsm6dso32_fsm_data_rate_get(), lsm6dso32_fsm_data_rate_set(), lsm6dso32_fsm_enable_get(), lsm6dso32_fsm_enable_set(), lsm6dso32_fsm_init_get(), lsm6dso32_fsm_init_set(), lsm6dso32_fsm_out_get(), lsm6dso32_gy_data_rate_get(), lsm6dso32_gy_data_rate_set(), lsm6dso32_gy_filter_lp1_get(), lsm6dso32_gy_filter_lp1_set(), lsm6dso32_gy_flag_data_ready_get(), lsm6dso32_gy_full_scale_get(), lsm6dso32_gy_full_scale_set(), lsm6dso32_gy_hp_path_internal_get(), lsm6dso32_gy_hp_path_internal_set(), lsm6dso32_gy_lp1_bandwidth_get(), lsm6dso32_gy_lp1_bandwidth_set(), lsm6dso32_gy_self_test_get(), lsm6dso32_gy_self_test_set(), lsm6dso32_gy_sleep_mode_get(), lsm6dso32_gy_sleep_mode_set(), lsm6dso32_i2c_interface_get(), lsm6dso32_i2c_interface_set(), lsm6dso32_i3c_disable_get(), lsm6dso32_i3c_disable_set(), lsm6dso32_int1_mode_get(), lsm6dso32_int1_mode_set(), lsm6dso32_int_notification_get(), lsm6dso32_int_notification_set(), lsm6dso32_ln_pg_read_byte(), lsm6dso32_ln_pg_write(), lsm6dso32_ln_pg_write_byte(), lsm6dso32_long_clr_get(), lsm6dso32_long_clr_set(), lsm6dso32_long_cnt_flag_data_ready_get(), lsm6dso32_long_cnt_get(), lsm6dso32_mem_bank_get(), lsm6dso32_mem_bank_set(), lsm6dso32_motion_flag_data_ready_get(), lsm6dso32_motion_sens_get(), lsm6dso32_motion_sens_set(), lsm6dso32_number_of_steps_get(), lsm6dso32_odr_cal_reg_get(), lsm6dso32_odr_cal_reg_set(), lsm6dso32_pedo_sens_get(), lsm6dso32_pedo_sens_set(), lsm6dso32_pedo_step_detect_get(), lsm6dso32_pin_int1_route_get(), lsm6dso32_pin_int1_route_set(), lsm6dso32_pin_int2_route_get(), lsm6dso32_pin_int2_route_set(), lsm6dso32_pin_mode_get(), lsm6dso32_pin_mode_set(), lsm6dso32_pin_polarity_get(), lsm6dso32_pin_polarity_set(), lsm6dso32_reset_get(), lsm6dso32_reset_set(), lsm6dso32_rounding_mode_get(), lsm6dso32_rounding_mode_set(), lsm6dso32_rst_batch_counter_get(), lsm6dso32_rst_batch_counter_set(), lsm6dso32_sdo_sa0_mode_get(), lsm6dso32_sdo_sa0_mode_set(), lsm6dso32_sh_batch_slave_0_get(), lsm6dso32_sh_batch_slave_0_set(), lsm6dso32_sh_batch_slave_1_get(), lsm6dso32_sh_batch_slave_1_set(), lsm6dso32_sh_batch_slave_2_get(), lsm6dso32_sh_batch_slave_2_set(), lsm6dso32_sh_batch_slave_3_get(), lsm6dso32_sh_batch_slave_3_set(), lsm6dso32_sh_data_rate_get(), lsm6dso32_sh_data_rate_set(), lsm6dso32_sh_master_get(), lsm6dso32_sh_master_set(), lsm6dso32_sh_pass_through_get(), lsm6dso32_sh_pass_through_set(), lsm6dso32_sh_pin_mode_get(), lsm6dso32_sh_pin_mode_set(), lsm6dso32_sh_read_data_raw_get(), lsm6dso32_sh_reset_get(), lsm6dso32_sh_reset_set(), lsm6dso32_sh_slave_connected_get(), lsm6dso32_sh_slave_connected_set(), lsm6dso32_sh_slv0_cfg_read(), lsm6dso32_sh_slv1_cfg_read(), lsm6dso32_sh_slv2_cfg_read(), lsm6dso32_sh_slv3_cfg_read(), lsm6dso32_sh_status_get(), lsm6dso32_sh_syncro_mode_get(), lsm6dso32_sh_syncro_mode_set(), lsm6dso32_sh_write_mode_get(), lsm6dso32_sh_write_mode_set(), lsm6dso32_spi_mode_get(), lsm6dso32_spi_mode_set(), lsm6dso32_status_reg_get(), lsm6dso32_steps_reset(), lsm6dso32_tap_axis_priority_get(), lsm6dso32_tap_axis_priority_set(), lsm6dso32_tap_detection_on_x_get(), lsm6dso32_tap_detection_on_x_set(), lsm6dso32_tap_detection_on_y_get(), lsm6dso32_tap_detection_on_y_set(), lsm6dso32_tap_detection_on_z_get(), lsm6dso32_tap_detection_on_z_set(), lsm6dso32_tap_dur_get(), lsm6dso32_tap_dur_set(), lsm6dso32_tap_mode_get(), lsm6dso32_tap_mode_set(), lsm6dso32_tap_quiet_get(), lsm6dso32_tap_quiet_set(), lsm6dso32_tap_shock_get(), lsm6dso32_tap_shock_set(), lsm6dso32_tap_threshold_x_get(), lsm6dso32_tap_threshold_x_set(), lsm6dso32_tap_threshold_y_get(), lsm6dso32_tap_threshold_y_set(), lsm6dso32_tap_threshold_z_get(), lsm6dso32_tap_threshold_z_set(), lsm6dso32_temp_flag_data_ready_get(), lsm6dso32_temperature_raw_get(), lsm6dso32_tilt_flag_data_ready_get(), lsm6dso32_tilt_sens_get(), lsm6dso32_tilt_sens_set(), lsm6dso32_timestamp_get(), lsm6dso32_timestamp_raw_get(), lsm6dso32_timestamp_set(), lsm6dso32_wkup_dur_get(), lsm6dso32_wkup_dur_set(), lsm6dso32_wkup_threshold_get(), lsm6dso32_wkup_threshold_set(), lsm6dso32_wkup_ths_weight_get(), lsm6dso32_wkup_ths_weight_set(), lsm6dso32_xl_data_rate_get(), lsm6dso32_xl_data_rate_set(), lsm6dso32_xl_fast_settling_get(), lsm6dso32_xl_fast_settling_set(), lsm6dso32_xl_filter_lp2_get(), lsm6dso32_xl_filter_lp2_set(), lsm6dso32_xl_flag_data_ready_get(), lsm6dso32_xl_full_scale_get(), lsm6dso32_xl_full_scale_set(), lsm6dso32_xl_hp_path_internal_get(), lsm6dso32_xl_hp_path_internal_set(), lsm6dso32_xl_hp_path_on_out_get(), lsm6dso32_xl_hp_path_on_out_set(), lsm6dso32_xl_lp2_on_6d_get(), lsm6dso32_xl_lp2_on_6d_set(), lsm6dso32_xl_offset_weight_get(), lsm6dso32_xl_offset_weight_set(), lsm6dso32_xl_self_test_get(), lsm6dso32_xl_self_test_set(), lsm6dso32_xl_usr_offset_get(), lsm6dso32_xl_usr_offset_on_wkup_get(), lsm6dso32_xl_usr_offset_on_wkup_set(), lsm6dso32_xl_usr_offset_set(), lsm6dso32_xl_usr_offset_x_get(), lsm6dso32_xl_usr_offset_y_get(), and lsm6dso32_xl_usr_offset_z_get().
lsm6dso32_write_reg()
int32_t __weak lsm6dso32_write_reg (stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 75 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = ctx->write_reg(ctx->handle, reg, data, len);
  return ret;
}
References stmdev_ctx_t::handle, and stmdev_ctx_t::write_reg.
Referenced by lsm6dso32_4d_mode_set(), lsm6dso32_6d_threshold_set(), lsm6dso32_act_mode_set(), lsm6dso32_act_pin_notification_set(), lsm6dso32_act_sleep_dur_set(), lsm6dso32_all_on_int1_set(), lsm6dso32_auto_increment_set(), lsm6dso32_batch_counter_threshold_set(), lsm6dso32_block_data_update_set(), lsm6dso32_boot_set(), lsm6dso32_compression_algo_init_set(), lsm6dso32_compression_algo_real_time_set(), lsm6dso32_compression_algo_set(), lsm6dso32_data_ready_mode_set(), lsm6dso32_den_enable_set(), lsm6dso32_den_mark_axis_x_set(), lsm6dso32_den_mark_axis_y_set(), lsm6dso32_den_mark_axis_z_set(), lsm6dso32_den_mode_set(), lsm6dso32_den_polarity_set(), lsm6dso32_emb_fsm_en_get(), lsm6dso32_emb_fsm_en_set(), lsm6dso32_ff_dur_set(), lsm6dso32_ff_threshold_set(), lsm6dso32_fifo_cnt_event_batch_set(), lsm6dso32_fifo_gy_batch_set(), lsm6dso32_fifo_mode_set(), lsm6dso32_fifo_pedo_batch_set(), lsm6dso32_fifo_stop_on_wtm_set(), lsm6dso32_fifo_temp_batch_set(), lsm6dso32_fifo_timestamp_decimation_set(), lsm6dso32_fifo_virtual_sens_odr_chg_set(), lsm6dso32_fifo_watermark_set(), lsm6dso32_fifo_xl_batch_set(), lsm6dso32_filter_settling_mask_set(), lsm6dso32_fsm_data_rate_set(), lsm6dso32_fsm_enable_set(), lsm6dso32_fsm_init_set(), lsm6dso32_gy_data_rate_set(), lsm6dso32_gy_filter_lp1_set(), lsm6dso32_gy_full_scale_set(), lsm6dso32_gy_hp_path_internal_set(), lsm6dso32_gy_lp1_bandwidth_set(), lsm6dso32_gy_self_test_set(), lsm6dso32_gy_sleep_mode_set(), lsm6dso32_i2c_interface_set(), lsm6dso32_i3c_disable_set(), lsm6dso32_int1_mode_set(), lsm6dso32_int_notification_set(), lsm6dso32_ln_pg_read_byte(), lsm6dso32_ln_pg_write(), lsm6dso32_ln_pg_write_byte(), lsm6dso32_long_clr_set(), lsm6dso32_long_cnt_set(), lsm6dso32_mem_bank_set(), lsm6dso32_motion_sens_set(), lsm6dso32_odr_cal_reg_set(), lsm6dso32_pedo_sens_set(), lsm6dso32_pin_int1_route_set(), lsm6dso32_pin_int2_route_set(), lsm6dso32_pin_mode_set(), lsm6dso32_pin_polarity_set(), lsm6dso32_reset_set(), lsm6dso32_rounding_mode_set(), lsm6dso32_rst_batch_counter_set(), lsm6dso32_sdo_sa0_mode_set(), lsm6dso32_sh_batch_slave_0_set(), lsm6dso32_sh_batch_slave_1_set(), lsm6dso32_sh_batch_slave_2_set(), lsm6dso32_sh_batch_slave_3_set(), lsm6dso32_sh_cfg_write(), lsm6dso32_sh_data_rate_set(), lsm6dso32_sh_master_set(), lsm6dso32_sh_pass_through_set(), lsm6dso32_sh_pin_mode_set(), lsm6dso32_sh_reset_set(), lsm6dso32_sh_slave_connected_set(), lsm6dso32_sh_slv0_cfg_read(), lsm6dso32_sh_slv1_cfg_read(), lsm6dso32_sh_slv2_cfg_read(), lsm6dso32_sh_slv3_cfg_read(), lsm6dso32_sh_syncro_mode_set(), lsm6dso32_sh_write_mode_set(), lsm6dso32_spi_mode_set(), lsm6dso32_steps_reset(), lsm6dso32_tap_axis_priority_set(), lsm6dso32_tap_detection_on_x_set(), lsm6dso32_tap_detection_on_y_set(), lsm6dso32_tap_detection_on_z_set(), lsm6dso32_tap_dur_set(), lsm6dso32_tap_mode_set(), lsm6dso32_tap_quiet_set(), lsm6dso32_tap_shock_set(), lsm6dso32_tap_threshold_x_set(), lsm6dso32_tap_threshold_y_set(), lsm6dso32_tap_threshold_z_set(), lsm6dso32_tilt_sens_set(), lsm6dso32_timestamp_set(), lsm6dso32_wkup_dur_set(), lsm6dso32_wkup_threshold_set(), lsm6dso32_wkup_ths_weight_set(), lsm6dso32_xl_data_rate_set(), lsm6dso32_xl_fast_settling_set(), lsm6dso32_xl_filter_lp2_set(), lsm6dso32_xl_full_scale_set(), lsm6dso32_xl_hp_path_internal_set(), lsm6dso32_xl_hp_path_on_out_set(), lsm6dso32_xl_lp2_on_6d_set(), lsm6dso32_xl_offset_weight_set(), lsm6dso32_xl_self_test_set(), lsm6dso32_xl_usr_offset_on_wkup_set(), lsm6dso32_xl_usr_offset_set(), lsm6dso32_xl_usr_offset_x_set(), lsm6dso32_xl_usr_offset_y_set(), and lsm6dso32_xl_usr_offset_z_set().