Da Vinci Firmware: "Interrupts"
"Interrupts"
Peripheral Drivers » "LIS2MDL Magnetometer Driver"
This section group all the functions that manage interrupts.
Functions
int32_t lis2mdl_offset_int_conf_set (const stmdev_ctx_t *ctx, lis2mdl_int_on_dataoff_t val)
The interrupt block recognition checks data after/before the hard-iron correction to discover the interrupt.[set].
int32_t lis2mdl_offset_int_conf_get (const stmdev_ctx_t *ctx, lis2mdl_int_on_dataoff_t *val)
The interrupt block recognition checks data after/before the hard-iron correction to discover the interrupt.[get].
int32_t lis2mdl_drdy_on_pin_set (const stmdev_ctx_t *ctx, uint8_t val)
Data-ready signal on INT_DRDY pin.[set].
int32_t lis2mdl_drdy_on_pin_get (const stmdev_ctx_t *ctx, uint8_t *val)
Data-ready signal on INT_DRDY pin.[get].
int32_t lis2mdl_int_on_pin_set (const stmdev_ctx_t *ctx, uint8_t val)
Interrupt signal on INT_DRDY pin.[set].
int32_t lis2mdl_int_on_pin_get (const stmdev_ctx_t *ctx, uint8_t *val)
Interrupt signal on INT_DRDY pin.[get].
int32_t lis2mdl_int_gen_conf_set (const stmdev_ctx_t *ctx, lis2mdl_int_crtl_reg_t *val)
Interrupt generator configuration register.[set].
int32_t lis2mdl_int_gen_conf_get (const stmdev_ctx_t *ctx, lis2mdl_int_crtl_reg_t *val)
Interrupt generator configuration register.[get].
int32_t lis2mdl_int_gen_source_get (const stmdev_ctx_t *ctx, lis2mdl_int_source_reg_t *val)
Interrupt generator source register.[get].
int32_t lis2mdl_int_gen_threshold_set (const stmdev_ctx_t *ctx, uint16_t val)
User-defined threshold value for xl interrupt event on generator. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG.[set].
int32_t lis2mdl_int_gen_threshold_get (const stmdev_ctx_t *ctx, uint16_t *val)
User-defined threshold value for xl interrupt event on generator. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG.[get].
Detailed Description
This section group all the functions that manage interrupts.
Function Documentation
lis2mdl_drdy_on_pin_get()
int32_t lis2mdl_drdy_on_pin_get (const stmdev_ctx_t * ctx, uint8_t * val)
Data-ready signal on INT_DRDY pin.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of drdy_on_pin in reg CFG_REG_C.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1077 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  *val = reg.drdy_on_pin;
  return ret;
}
References lis2mdl_cfg_reg_c_t::drdy_on_pin, LIS2MDL_CFG_REG_C, and lis2mdl_read_reg().
lis2mdl_drdy_on_pin_set()
int32_t lis2mdl_drdy_on_pin_set (const stmdev_ctx_t * ctx, uint8_t val)
Data-ready signal on INT_DRDY pin.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of drdy_on_pin in reg CFG_REG_C
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1053 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.drdy_on_pin = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::drdy_on_pin, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_write_reg().
lis2mdl_int_gen_conf_get()
int32_t lis2mdl_int_gen_conf_get (const stmdev_ctx_t * ctx, lis2mdl_int_crtl_reg_t * val)
Interrupt generator configuration register.[get].
Parameters
ctx read / write interface definitions.(ptr)
val registers INT_CRTL_REG.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1157 of file lis2mdl_reg.c.
{
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_INT_CRTL_REG, (uint8_t *) val, 1);
  return ret;
}
References LIS2MDL_INT_CRTL_REG, and lis2mdl_read_reg().
lis2mdl_int_gen_conf_set()
int32_t lis2mdl_int_gen_conf_set (const stmdev_ctx_t * ctx, lis2mdl_int_crtl_reg_t * val)
Interrupt generator configuration register.[set].
Parameters
ctx read / write interface definitions.(ptr)
val registers INT_CRTL_REG.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1139 of file lis2mdl_reg.c.
{
  int32_t ret;
  ret = lis2mdl_write_reg(ctx, LIS2MDL_INT_CRTL_REG, (uint8_t *) val, 1);
  return ret;
}
References LIS2MDL_INT_CRTL_REG, and lis2mdl_write_reg().
lis2mdl_int_gen_source_get()
int32_t lis2mdl_int_gen_source_get (const stmdev_ctx_t * ctx, lis2mdl_int_source_reg_t * val)
Interrupt generator source register.[get].
Parameters
ctx read / write interface definitions.(ptr)
val registers INT_SOURCE_REG.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1175 of file lis2mdl_reg.c.
{
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_INT_SOURCE_REG, (uint8_t *) val, 1);
  return ret;
}
References LIS2MDL_INT_SOURCE_REG, and lis2mdl_read_reg().
lis2mdl_int_gen_threshold_get()
int32_t lis2mdl_int_gen_threshold_get (const stmdev_ctx_t * ctx, uint16_t * val)
User-defined threshold value for xl interrupt event on generator. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG.[get].
Parameters
ctx read / write interface definitions.(ptr)
buff that stores data read
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1217 of file lis2mdl_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_INT_THS_L_REG, buff, 2);
  *val = buff[1];
  *val = (*val * 256U) +  buff[0];
  return ret;
}
References LIS2MDL_INT_THS_L_REG, and lis2mdl_read_reg().
lis2mdl_int_gen_threshold_set()
int32_t lis2mdl_int_gen_threshold_set (const stmdev_ctx_t * ctx, uint16_t val)
User-defined threshold value for xl interrupt event on generator. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG.[set].
Parameters
ctx read / write interface definitions.(ptr)
buff that contains data to write
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1195 of file lis2mdl_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  buff[1] = (uint8_t)(val / 256U);
  buff[0] = (uint8_t)(val - (buff[1] * 256U));
  ret = lis2mdl_write_reg(ctx, LIS2MDL_INT_THS_L_REG, buff, 2);
  return ret;
}
References LIS2MDL_INT_THS_L_REG, and lis2mdl_write_reg().
lis2mdl_int_on_pin_get()
int32_t lis2mdl_int_on_pin_get (const stmdev_ctx_t * ctx, uint8_t * val)
Interrupt signal on INT_DRDY pin.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of int_on_pin in reg CFG_REG_C.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1120 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  *val = reg.int_on_pin;
  return ret;
}
References lis2mdl_cfg_reg_c_t::int_on_pin, LIS2MDL_CFG_REG_C, and lis2mdl_read_reg().
lis2mdl_int_on_pin_set()
int32_t lis2mdl_int_on_pin_set (const stmdev_ctx_t * ctx, uint8_t val)
Interrupt signal on INT_DRDY pin.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of int_on_pin in reg CFG_REG_C
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1096 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.int_on_pin = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::int_on_pin, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_write_reg().
lis2mdl_offset_int_conf_get()
int32_t lis2mdl_offset_int_conf_get (const stmdev_ctx_t * ctx, lis2mdl_int_on_dataoff_t * val)
The interrupt block recognition checks data after/before the hard-iron correction to discover the interrupt.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of int_on_dataoff in reg CFG_REG_B.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1019 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  switch (reg.int_on_dataoff)
  {
    case LIS2MDL_CHECK_BEFORE:
      *val = LIS2MDL_CHECK_BEFORE;
      break;
    case LIS2MDL_CHECK_AFTER:
      *val = LIS2MDL_CHECK_AFTER;
      break;
    default:
      *val = LIS2MDL_CHECK_BEFORE;
      break;
  }
  return ret;
}
References lis2mdl_cfg_reg_b_t::int_on_dataoff, LIS2MDL_CFG_REG_B, LIS2MDL_CHECK_AFTER, LIS2MDL_CHECK_BEFORE, and lis2mdl_read_reg().
lis2mdl_offset_int_conf_set()
int32_t lis2mdl_offset_int_conf_set (const stmdev_ctx_t * ctx, lis2mdl_int_on_dataoff_t val)
The interrupt block recognition checks data after/before the hard-iron correction to discover the interrupt.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of int_on_dataoff in reg CFG_REG_B
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 993 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.int_on_dataoff = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_b_t::int_on_dataoff, LIS2MDL_CFG_REG_B, lis2mdl_read_reg(), and lis2mdl_write_reg().