Da Vinci Firmware: LSM6DSO32_tilt_detection
LSM6DSO32_tilt_detection
Peripheral Drivers » "LSM6DSO32 6-Axis IMU Driver"
This section groups all the functions that manage the tilt event detection.
Functions
int32_t lsm6dso32_tilt_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable tilt calculation.[set].
int32_t lsm6dso32_tilt_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable tilt calculation.[get].
int32_t lsm6dso32_tilt_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Interrupt status bit for tilt detection.[get].
Detailed Description
This section groups all the functions that manage the tilt event detection.
Function Documentation
lsm6dso32_tilt_flag_data_ready_get()
int32_t lsm6dso32_tilt_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Interrupt status bit for tilt detection.[get].
Parameters
ctx read / write interface definitions
val change the values of is_tilt in reg EMB_FUNC_STATUS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7461 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_status_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_STATUS,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.is_tilt;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_status_t::is_tilt, LSM6DSO32_EMB_FUNC_STATUS, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_tilt_sens_get()
int32_t lsm6dso32_tilt_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable tilt calculation.[get].
Parameters
ctx read / write interface definitions
val change the values of tilt_en in reg EMB_FUNC_EN_A
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7431 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_en_a_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.tilt_en;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMB_FUNC_EN_A, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, and lsm6dso32_emb_func_en_a_t::tilt_en.
lsm6dso32_tilt_sens_set()
int32_t lsm6dso32_tilt_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable tilt calculation.[set].
Parameters
ctx read / write interface definitions
val change the values of tilt_en in reg EMB_FUNC_EN_A
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7395 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_en_a_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg.tilt_en = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMB_FUNC_EN_A, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_write_reg(), and lsm6dso32_emb_func_en_a_t::tilt_en.