Da Vinci Firmware: "Common"
"Common"
Peripheral Drivers » "LIS2MDL Magnetometer Driver"
This section group common useful functions.
Functions
int32_t lis2mdl_device_id_get (const stmdev_ctx_t *ctx, uint8_t *buff)
DeviceWhoamI.[get].
int32_t lis2mdl_reset_set (const stmdev_ctx_t *ctx, uint8_t val)
Software reset. Restore the default values in user registers.[set].
int32_t lis2mdl_reset_get (const stmdev_ctx_t *ctx, uint8_t *val)
Software reset. Restore the default values in user registers.[get].
int32_t lis2mdl_boot_set (const stmdev_ctx_t *ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
int32_t lis2mdl_boot_get (const stmdev_ctx_t *ctx, uint8_t *val)
Reboot memory content. Reload the calibration parameters.[get].
int32_t lis2mdl_self_test_set (const stmdev_ctx_t *ctx, uint8_t val)
Selftest.[set].
int32_t lis2mdl_self_test_get (const stmdev_ctx_t *ctx, uint8_t *val)
Selftest.[get].
int32_t lis2mdl_data_format_set (const stmdev_ctx_t *ctx, lis2mdl_ble_t val)
Big/Little Endian data selection.[set].
int32_t lis2mdl_data_format_get (const stmdev_ctx_t *ctx, lis2mdl_ble_t *val)
Big/Little Endian data selection.[get].
int32_t lis2mdl_status_get (const stmdev_ctx_t *ctx, lis2mdl_status_reg_t *val)
Info about device status.[get].
Detailed Description
This section group common useful functions.
Function Documentation
lis2mdl_boot_get()
int32_t lis2mdl_boot_get (const stmdev_ctx_t * ctx, uint8_t * val)
Reboot memory content. Reload the calibration parameters.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of reboot in reg CFG_REG_A.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 843 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  *val = reg.reboot;
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), and lis2mdl_cfg_reg_a_t::reboot.
Referenced by lis2mdl_init(), and lis2mdl_init_2().
lis2mdl_boot_set()
int32_t lis2mdl_boot_set (const stmdev_ctx_t * ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of reboot in reg CFG_REG_A
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 819 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.reboot = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_a_t::reboot.
Referenced by lis2mdl_init(), and lis2mdl_init_2().
lis2mdl_data_format_get()
int32_t lis2mdl_data_format_get (const stmdev_ctx_t * ctx, lis2mdl_ble_t * val)
Big/Little Endian data selection.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of ble in reg CFG_REG_C.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 929 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  switch (reg.ble)
  {
    case LIS2MDL_LSB_AT_LOW_ADD:
      *val = LIS2MDL_LSB_AT_LOW_ADD;
      break;
    case LIS2MDL_MSB_AT_LOW_ADD:
      *val = LIS2MDL_MSB_AT_LOW_ADD;
      break;
    default:
      *val = LIS2MDL_LSB_AT_LOW_ADD;
      break;
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::ble, LIS2MDL_CFG_REG_C, LIS2MDL_LSB_AT_LOW_ADD, LIS2MDL_MSB_AT_LOW_ADD, and lis2mdl_read_reg().
lis2mdl_data_format_set()
int32_t lis2mdl_data_format_set (const stmdev_ctx_t * ctx, lis2mdl_ble_t val)
Big/Little Endian data selection.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of ble in reg CFG_REG_C
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 905 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.ble = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::ble, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_write_reg().
lis2mdl_device_id_get()
int32_t lis2mdl_device_id_get (const stmdev_ctx_t * ctx, uint8_t * buff)
DeviceWhoamI.[get].
Parameters
ctx read / write interface definitions.(ptr)
buff that stores data read
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 759 of file lis2mdl_reg.c.
{
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_WHO_AM_I, buff, 1);
  return ret;
}
References lis2mdl_read_reg(), and LIS2MDL_WHO_AM_I.
Referenced by lis2mdl_init(), and lis2mdl_init_2().
lis2mdl_reset_get()
int32_t lis2mdl_reset_get (const stmdev_ctx_t * ctx, uint8_t * val)
Software reset. Restore the default values in user registers.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of soft_rst in reg CFG_REG_A.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 800 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  *val = reg.soft_rst;
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), and lis2mdl_cfg_reg_a_t::soft_rst.
Referenced by lis2mdl_init(), and lis2mdl_init_2().
lis2mdl_reset_set()
int32_t lis2mdl_reset_set (const stmdev_ctx_t * ctx, uint8_t val)
Software reset. Restore the default values in user registers.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of soft_rst in reg CFG_REG_A
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 776 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.soft_rst = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_a_t::soft_rst.
Referenced by lis2mdl_init(), and lis2mdl_init_2().
lis2mdl_self_test_get()
int32_t lis2mdl_self_test_get (const stmdev_ctx_t * ctx, uint8_t * val)
Selftest.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of self_test in reg CFG_REG_C.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 886 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  *val = reg.self_test;
  return ret;
}
References LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_cfg_reg_c_t::self_test.
lis2mdl_self_test_set()
int32_t lis2mdl_self_test_set (const stmdev_ctx_t * ctx, uint8_t val)
Selftest.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of self_test in reg CFG_REG_C
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 862 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.self_test = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_c_t::self_test.
lis2mdl_status_get()
int32_t lis2mdl_status_get (const stmdev_ctx_t * ctx, lis2mdl_status_reg_t * val)
Info about device status.[get].
Parameters
ctx read / write interface definitions.(ptr)
val registers STATUS_REG.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 962 of file lis2mdl_reg.c.
{
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_STATUS_REG, (uint8_t *) val, 1);
  return ret;
}
References lis2mdl_read_reg(), and LIS2MDL_STATUS_REG.