Da Vinci Firmware: LSM6DSO32_filters
LSM6DSO32_filters
Peripheral Drivers » "LSM6DSO32 IMU Driver"
This section group all the functions concerning the filters configuration.
Functions
int32_t lsm6dso32_xl_filter_lp2_set (stmdev_ctx_t *ctx, uint8_t val)
Accelerometer output from LPF2 filtering stage selection.[set].
int32_t lsm6dso32_xl_filter_lp2_get (stmdev_ctx_t *ctx, uint8_t *val)
Accelerometer output from LPF2 filtering stage selection.[get].
int32_t lsm6dso32_gy_filter_lp1_set (stmdev_ctx_t *ctx, uint8_t val)
Enables gyroscope digital LPF1 if auxiliary SPI is disabled; the bandwidth can be selected through FTYPE [2:0] in CTRL6_C (15h).[set].
int32_t lsm6dso32_gy_filter_lp1_get (stmdev_ctx_t *ctx, uint8_t *val)
Enables gyroscope digital LPF1 if auxiliary SPI is disabled; the bandwidth can be selected through FTYPE [2:0] in CTRL6_C (15h).[get].
int32_t lsm6dso32_filter_settling_mask_set (stmdev_ctx_t *ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[set].
int32_t lsm6dso32_filter_settling_mask_get (stmdev_ctx_t *ctx, uint8_t *val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[get].
int32_t lsm6dso32_gy_lp1_bandwidth_set (stmdev_ctx_t *ctx, lsm6dso32_ftype_t val)
Gyroscope lp1 bandwidth.[set].
int32_t lsm6dso32_gy_lp1_bandwidth_get (stmdev_ctx_t *ctx, lsm6dso32_ftype_t *val)
Gyroscope lp1 bandwidth.[get].
int32_t lsm6dso32_xl_lp2_on_6d_set (stmdev_ctx_t *ctx, uint8_t val)
Low pass filter 2 on 6D function selection.[set].
int32_t lsm6dso32_xl_lp2_on_6d_get (stmdev_ctx_t *ctx, uint8_t *val)
Low pass filter 2 on 6D function selection.[get].
int32_t lsm6dso32_xl_hp_path_on_out_set (stmdev_ctx_t *ctx, lsm6dso32_hp_slope_xl_en_t val)
Accelerometer slope filter / high-pass filter selection on output.[set].
int32_t lsm6dso32_xl_hp_path_on_out_get (stmdev_ctx_t *ctx, lsm6dso32_hp_slope_xl_en_t *val)
Accelerometer slope filter / high-pass filter selection on output.[get].
int32_t lsm6dso32_xl_fast_settling_set (stmdev_ctx_t *ctx, uint8_t val)
Enables accelerometer LPF2 and HPF fast-settling mode. The filter sets the second samples after writing this bit. Active only during device exit from power-down mode.[set].
int32_t lsm6dso32_xl_fast_settling_get (stmdev_ctx_t *ctx, uint8_t *val)
Enables accelerometer LPF2 and HPF fast-settling mode. The filter sets the second samples after writing this bit. Active only during device exit from power-down mode.[get].
int32_t lsm6dso32_xl_hp_path_internal_set (stmdev_ctx_t *ctx, lsm6dso32_slope_fds_t val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[set].
int32_t lsm6dso32_xl_hp_path_internal_get (stmdev_ctx_t *ctx, lsm6dso32_slope_fds_t *val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[get].
int32_t lsm6dso32_gy_hp_path_internal_set (stmdev_ctx_t *ctx, lsm6dso32_hpm_g_t val)
Enables gyroscope digital high-pass filter. The filter is enabled only if the gyro is in HP mode.[set].
int32_t lsm6dso32_gy_hp_path_internal_get (stmdev_ctx_t *ctx, lsm6dso32_hpm_g_t *val)
Enables gyroscope digital high-pass filter. The filter is enabled only if the gyro is in HP mode.[get].
Detailed Description
This section group all the functions concerning the filters configuration.
Function Documentation
lsm6dso32_filter_settling_mask_get()
int32_t lsm6dso32_filter_settling_mask_get (stmdev_ctx_t * ctx, uint8_t * val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[get].
Parameters
ctx read / write interface definitions
val change the values of drdy_mask in reg CTRL4_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2272 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl4_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL4_C, (uint8_t *)&reg, 1);
  *val = reg.drdy_mask;
  return ret;
}
References lsm6dso32_ctrl4_c_t::drdy_mask, LSM6DSO32_CTRL4_C, and lsm6dso32_read_reg().
lsm6dso32_filter_settling_mask_set()
int32_t lsm6dso32_filter_settling_mask_set (stmdev_ctx_t * ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[set].
Parameters
ctx read / write interface definitions
val change the values of drdy_mask in reg CTRL4_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2246 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl4_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL4_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.drdy_mask = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL4_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl4_c_t::drdy_mask, LSM6DSO32_CTRL4_C, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_gy_filter_lp1_get()
int32_t lsm6dso32_gy_filter_lp1_get (stmdev_ctx_t * ctx, uint8_t * val)
Enables gyroscope digital LPF1 if auxiliary SPI is disabled; the bandwidth can be selected through FTYPE [2:0] in CTRL6_C (15h).[get].
Parameters
ctx read / write interface definitions
val change the values of lpf1_sel_g in reg CTRL4_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2226 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl4_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL4_C, (uint8_t *)&reg, 1);
  *val = reg.lpf1_sel_g;
  return ret;
}
References lsm6dso32_ctrl4_c_t::lpf1_sel_g, LSM6DSO32_CTRL4_C, and lsm6dso32_read_reg().
lsm6dso32_gy_filter_lp1_set()
int32_t lsm6dso32_gy_filter_lp1_set (stmdev_ctx_t * ctx, uint8_t val)
Enables gyroscope digital LPF1 if auxiliary SPI is disabled; the bandwidth can be selected through FTYPE [2:0] in CTRL6_C (15h).[set].
Parameters
ctx read / write interface definitions
val change the values of lpf1_sel_g in reg CTRL4_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2200 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl4_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL4_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.lpf1_sel_g = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL4_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl4_c_t::lpf1_sel_g, LSM6DSO32_CTRL4_C, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_gy_hp_path_internal_get()
int32_t lsm6dso32_gy_hp_path_internal_get (stmdev_ctx_t * ctx, lsm6dso32_hpm_g_t * val)
Enables gyroscope digital high-pass filter. The filter is enabled only if the gyro is in HP mode.[get].
Parameters
ctx read / write interface definitions
val Get the values of hp_en_g and hp_en_g in reg CTRL7_G
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2705 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl7_g_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL7_G, (uint8_t *)&reg, 1);
  switch ((reg.hp_en_g << 7) + reg.hpm_g)
  {
    case LSM6DSO32_HP_FILTER_NONE:
      *val = LSM6DSO32_HP_FILTER_NONE;
      break;
    case LSM6DSO32_HP_FILTER_16mHz:
      *val = LSM6DSO32_HP_FILTER_16mHz;
      break;
    case LSM6DSO32_HP_FILTER_65mHz:
      *val = LSM6DSO32_HP_FILTER_65mHz;
      break;
    case LSM6DSO32_HP_FILTER_260mHz:
      *val = LSM6DSO32_HP_FILTER_260mHz;
      break;
    case LSM6DSO32_HP_FILTER_1Hz04:
      *val = LSM6DSO32_HP_FILTER_1Hz04;
      break;
    default:
      *val = LSM6DSO32_HP_FILTER_NONE;
      break;
  }
  return ret;
}
References lsm6dso32_ctrl7_g_t::hp_en_g, lsm6dso32_ctrl7_g_t::hpm_g, LSM6DSO32_CTRL7_G, LSM6DSO32_HP_FILTER_16mHz, LSM6DSO32_HP_FILTER_1Hz04, LSM6DSO32_HP_FILTER_260mHz, LSM6DSO32_HP_FILTER_65mHz, LSM6DSO32_HP_FILTER_NONE, and lsm6dso32_read_reg().
lsm6dso32_gy_hp_path_internal_set()
int32_t lsm6dso32_gy_hp_path_internal_set (stmdev_ctx_t * ctx, lsm6dso32_hpm_g_t val)
Enables gyroscope digital high-pass filter. The filter is enabled only if the gyro is in HP mode.[set].
Parameters
ctx read / write interface definitions
val Get the values of hp_en_g and hp_en_g in reg CTRL7_G
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2678 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl7_g_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL7_G, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.hp_en_g = ((uint8_t)val & 0x80U) >> 7;
    reg.hpm_g = (uint8_t)val & 0x03U;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL7_G, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl7_g_t::hp_en_g, lsm6dso32_ctrl7_g_t::hpm_g, LSM6DSO32_CTRL7_G, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_gy_lp1_bandwidth_get()
int32_t lsm6dso32_gy_lp1_bandwidth_get (stmdev_ctx_t * ctx, lsm6dso32_ftype_t * val)
Gyroscope lp1 bandwidth.[get].
Parameters
ctx read / write interface definitions
val Get the values of ftype in reg CTRL6_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2317 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl6_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL6_C, (uint8_t *)&reg, 1);
  switch (reg.ftype)
  {
    case LSM6DSO32_ULTRA_LIGHT:
      *val = LSM6DSO32_ULTRA_LIGHT;
      break;
    case LSM6DSO32_VERY_LIGHT:
      *val = LSM6DSO32_VERY_LIGHT;
      break;
    case LSM6DSO32_LIGHT:
      *val = LSM6DSO32_LIGHT;
      break;
    case LSM6DSO32_MEDIUM:
      *val = LSM6DSO32_MEDIUM;
      break;
    case LSM6DSO32_STRONG:
      *val = LSM6DSO32_STRONG;
      break;
    case LSM6DSO32_VERY_STRONG:
      *val = LSM6DSO32_VERY_STRONG;
      break;
    case LSM6DSO32_AGGRESSIVE:
      *val = LSM6DSO32_AGGRESSIVE;
      break;
    case LSM6DSO32_XTREME:
      *val = LSM6DSO32_XTREME;
      break;
    default:
      *val = LSM6DSO32_ULTRA_LIGHT;
      break;
  }
  return ret;
}
References lsm6dso32_ctrl6_c_t::ftype, LSM6DSO32_AGGRESSIVE, LSM6DSO32_CTRL6_C, LSM6DSO32_LIGHT, LSM6DSO32_MEDIUM, lsm6dso32_read_reg(), LSM6DSO32_STRONG, LSM6DSO32_ULTRA_LIGHT, LSM6DSO32_VERY_LIGHT, LSM6DSO32_VERY_STRONG, and LSM6DSO32_XTREME.
lsm6dso32_gy_lp1_bandwidth_set()
int32_t lsm6dso32_gy_lp1_bandwidth_set (stmdev_ctx_t * ctx, lsm6dso32_ftype_t val)
Gyroscope lp1 bandwidth.[set].
Parameters
ctx read / write interface definitions
val change the values of ftype in reg CTRL6_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2292 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl6_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL6_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.ftype = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL6_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl6_c_t::ftype, LSM6DSO32_CTRL6_C, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_xl_fast_settling_get()
int32_t lsm6dso32_xl_fast_settling_get (stmdev_ctx_t * ctx, uint8_t * val)
Enables accelerometer LPF2 and HPF fast-settling mode. The filter sets the second samples after writing this bit. Active only during device exit from power-down mode.[get].
Parameters
ctx read / write interface definitions
val change the values of fastsettl_mode_xl in reg CTRL8_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2596 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl8_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  *val = reg.fastsettl_mode_xl;
  return ret;
}
References lsm6dso32_ctrl8_xl_t::fastsettl_mode_xl, LSM6DSO32_CTRL8_XL, and lsm6dso32_read_reg().
lsm6dso32_xl_fast_settling_set()
int32_t lsm6dso32_xl_fast_settling_set (stmdev_ctx_t * ctx, uint8_t val)
Enables accelerometer LPF2 and HPF fast-settling mode. The filter sets the second samples after writing this bit. Active only during device exit from power-down mode.[set].
Parameters
ctx read / write interface definitions
val change the values of fastsettl_mode_xl in reg CTRL8_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2570 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl8_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.fastsettl_mode_xl = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl8_xl_t::fastsettl_mode_xl, LSM6DSO32_CTRL8_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_xl_filter_lp2_get()
int32_t lsm6dso32_xl_filter_lp2_get (stmdev_ctx_t * ctx, uint8_t * val)
Accelerometer output from LPF2 filtering stage selection.[get].
Parameters
ctx read / write interface definitions
val change the values of lpf2_xl_en in reg CTRL1_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2179 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl1_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL1_XL, (uint8_t *)&reg, 1);
  *val = reg.lpf2_xl_en;
  return ret;
}
References lsm6dso32_ctrl1_xl_t::lpf2_xl_en, LSM6DSO32_CTRL1_XL, and lsm6dso32_read_reg().
lsm6dso32_xl_filter_lp2_set()
int32_t lsm6dso32_xl_filter_lp2_set (stmdev_ctx_t * ctx, uint8_t val)
Accelerometer output from LPF2 filtering stage selection.[set].
Parameters
ctx read / write interface definitions
val change the values of lpf2_xl_en in reg CTRL1_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2155 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl1_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL1_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.lpf2_xl_en = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL1_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl1_xl_t::lpf2_xl_en, LSM6DSO32_CTRL1_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_xl_hp_path_internal_get()
int32_t lsm6dso32_xl_hp_path_internal_get (stmdev_ctx_t * ctx, lsm6dso32_slope_fds_t * val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[get].
Parameters
ctx read / write interface definitions
val Get the values of slope_fds in reg TAP_CFG0
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2643 of file lsm6dso32_reg.c.
{
  lsm6dso32_tap_cfg0_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_TAP_CFG0, (uint8_t *)&reg, 1);
  switch (reg.slope_fds)
  {
    case LSM6DSO32_USE_SLOPE:
      *val = LSM6DSO32_USE_SLOPE;
      break;
    case LSM6DSO32_USE_HPF:
      *val = LSM6DSO32_USE_HPF;
      break;
    default:
      *val = LSM6DSO32_USE_SLOPE;
      break;
  }
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_TAP_CFG0, LSM6DSO32_USE_HPF, LSM6DSO32_USE_SLOPE, and lsm6dso32_tap_cfg0_t::slope_fds.
lsm6dso32_xl_hp_path_internal_set()
int32_t lsm6dso32_xl_hp_path_internal_set (stmdev_ctx_t * ctx, lsm6dso32_slope_fds_t val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[set].
Parameters
ctx read / write interface definitions
val change the values of slope_fds in reg TAP_CFG0
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2617 of file lsm6dso32_reg.c.
{
  lsm6dso32_tap_cfg0_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_TAP_CFG0, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.slope_fds = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_TAP_CFG0, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_TAP_CFG0, lsm6dso32_write_reg(), and lsm6dso32_tap_cfg0_t::slope_fds.
lsm6dso32_xl_hp_path_on_out_get()
int32_t lsm6dso32_xl_hp_path_on_out_get (stmdev_ctx_t * ctx, lsm6dso32_hp_slope_xl_en_t * val)
Accelerometer slope filter / high-pass filter selection on output.[get].
Parameters
ctx read / write interface definitions
val Get the values of hp_slope_xl_en in reg CTRL8_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2448 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl8_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  switch ((reg.hp_ref_mode_xl << 5) | (reg.hp_slope_xl_en << 4) |
          reg.hpcf_xl)
  {
    case LSM6DSO32_HP_PATH_DISABLE_ON_OUT:
      *val = LSM6DSO32_HP_PATH_DISABLE_ON_OUT;
      break;
    case LSM6DSO32_SLOPE_ODR_DIV_4:
      *val = LSM6DSO32_SLOPE_ODR_DIV_4;
      break;
    case LSM6DSO32_HP_ODR_DIV_10:
      *val = LSM6DSO32_HP_ODR_DIV_10;
      break;
    case LSM6DSO32_HP_ODR_DIV_20:
      *val = LSM6DSO32_HP_ODR_DIV_20;
      break;
    case LSM6DSO32_HP_ODR_DIV_45:
      *val = LSM6DSO32_HP_ODR_DIV_45;
      break;
    case LSM6DSO32_HP_ODR_DIV_100:
      *val = LSM6DSO32_HP_ODR_DIV_100;
      break;
    case LSM6DSO32_HP_ODR_DIV_200:
      *val = LSM6DSO32_HP_ODR_DIV_200;
      break;
    case LSM6DSO32_HP_ODR_DIV_400:
      *val = LSM6DSO32_HP_ODR_DIV_400;
      break;
    case LSM6DSO32_HP_ODR_DIV_800:
      *val = LSM6DSO32_HP_ODR_DIV_800;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_10:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_10;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_20:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_20;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_45:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_45;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_100:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_100;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_200:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_200;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_400:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_400;
      break;
    case LSM6DSO32_HP_REF_MD_ODR_DIV_800:
      *val = LSM6DSO32_HP_REF_MD_ODR_DIV_800;
      break;
    case LSM6DSO32_LP_ODR_DIV_10:
      *val = LSM6DSO32_LP_ODR_DIV_10;
      break;
    case LSM6DSO32_LP_ODR_DIV_20:
      *val = LSM6DSO32_LP_ODR_DIV_20;
      break;
    case LSM6DSO32_LP_ODR_DIV_45:
      *val = LSM6DSO32_LP_ODR_DIV_45;
      break;
    case LSM6DSO32_LP_ODR_DIV_100:
      *val = LSM6DSO32_LP_ODR_DIV_100;
      break;
    case LSM6DSO32_LP_ODR_DIV_200:
      *val = LSM6DSO32_LP_ODR_DIV_200;
      break;
    case LSM6DSO32_LP_ODR_DIV_400:
      *val = LSM6DSO32_LP_ODR_DIV_400;
      break;
    case LSM6DSO32_LP_ODR_DIV_800:
      *val = LSM6DSO32_LP_ODR_DIV_800;
      break;
    default:
      *val = LSM6DSO32_HP_PATH_DISABLE_ON_OUT;
      break;
  }
  return ret;
}
References lsm6dso32_ctrl8_xl_t::hp_ref_mode_xl, lsm6dso32_ctrl8_xl_t::hp_slope_xl_en, lsm6dso32_ctrl8_xl_t::hpcf_xl, LSM6DSO32_CTRL8_XL, LSM6DSO32_HP_ODR_DIV_10, LSM6DSO32_HP_ODR_DIV_100, LSM6DSO32_HP_ODR_DIV_20, LSM6DSO32_HP_ODR_DIV_200, LSM6DSO32_HP_ODR_DIV_400, LSM6DSO32_HP_ODR_DIV_45, LSM6DSO32_HP_ODR_DIV_800, LSM6DSO32_HP_PATH_DISABLE_ON_OUT, LSM6DSO32_HP_REF_MD_ODR_DIV_10, LSM6DSO32_HP_REF_MD_ODR_DIV_100, LSM6DSO32_HP_REF_MD_ODR_DIV_20, LSM6DSO32_HP_REF_MD_ODR_DIV_200, LSM6DSO32_HP_REF_MD_ODR_DIV_400, LSM6DSO32_HP_REF_MD_ODR_DIV_45, LSM6DSO32_HP_REF_MD_ODR_DIV_800, LSM6DSO32_LP_ODR_DIV_10, LSM6DSO32_LP_ODR_DIV_100, LSM6DSO32_LP_ODR_DIV_20, LSM6DSO32_LP_ODR_DIV_200, LSM6DSO32_LP_ODR_DIV_400, LSM6DSO32_LP_ODR_DIV_45, LSM6DSO32_LP_ODR_DIV_800, lsm6dso32_read_reg(), and LSM6DSO32_SLOPE_ODR_DIV_4.
lsm6dso32_xl_hp_path_on_out_set()
int32_t lsm6dso32_xl_hp_path_on_out_set (stmdev_ctx_t * ctx, lsm6dso32_hp_slope_xl_en_t val)
Accelerometer slope filter / high-pass filter selection on output.[set].
Parameters
ctx read / write interface definitions
val change the values of hp_slope_xl_en in reg CTRL8_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2420 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl8_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.hp_slope_xl_en = ((uint8_t)val & 0x10U) >> 4;
    reg.hp_ref_mode_xl = ((uint8_t)val & 0x20U) >> 5;
    reg.hpcf_xl = (uint8_t)val & 0x07U;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl8_xl_t::hp_ref_mode_xl, lsm6dso32_ctrl8_xl_t::hp_slope_xl_en, lsm6dso32_ctrl8_xl_t::hpcf_xl, LSM6DSO32_CTRL8_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_xl_lp2_on_6d_get()
int32_t lsm6dso32_xl_lp2_on_6d_get (stmdev_ctx_t * ctx, uint8_t * val)
Low pass filter 2 on 6D function selection.[get].
Parameters
ctx read / write interface definitions
val change the values of low_pass_on_6d in reg CTRL8_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2399 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl8_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  *val = reg.low_pass_on_6d;
  return ret;
}
References lsm6dso32_ctrl8_xl_t::low_pass_on_6d, LSM6DSO32_CTRL8_XL, and lsm6dso32_read_reg().
lsm6dso32_xl_lp2_on_6d_set()
int32_t lsm6dso32_xl_lp2_on_6d_set (stmdev_ctx_t * ctx, uint8_t val)
Low pass filter 2 on 6D function selection.[set].
Parameters
ctx read / write interface definitions
val change the values of low_pass_on_6d in reg CTRL8_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 2375 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl8_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.low_pass_on_6d = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL8_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl8_xl_t::low_pass_on_6d, LSM6DSO32_CTRL8_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().