Da Vinci Firmware: Buzzer Driver
Buzzer Driver
Peripheral Drivers
Low-level driver for the PWM buzzer.
Modules
Musical Note and Tempo Definitions
Files
file buzzer.h
Provides a driver for playing musical notes on a PWM-driven buzzer.
Data Structures
struct note_t
Represents a single musical note with a frequency and duration.
struct buzzer_t
Represents the buzzer device handle.
Functions
void buzzer_init (buzzer_t *bz, TIM_HandleTypeDef *htim, uint32_t channel)
Initializes the buzzer object and its associated timer hardware.
void musica_maestro (buzzer_t *bz, const note_t *partition, uint16_t melody_length)
Plays a melody by iterating through an array of notes.
Variables
buzzer_t buzzer
Global instance of the buzzer object.
Detailed Description
Low-level driver for the PWM buzzer.
Function Documentation
buzzer_init()
void buzzer_init (buzzer_t * bz, TIM_HandleTypeDef * htim, uint32_t channel)
Initializes the buzzer object and its associated timer hardware.
Initializes the buzzer object.
This function should be called once at startup to associate the buzzer object with its hardware timer.
Parameters
[in,out] bz Pointer to the global buzzer_t object.
[in] htim Pointer to the initialized TIM_HandleTypeDef for the buzzer.
[in] channel The TIM_CHANNEL_x that the buzzer is connected to.
Returns
None
Definition at line 23 of file buzzer.c.
{
    // Assert that the provided pointers are valid.
    if (bz == NULL || htim == NULL) {
        Error_Handler();
    }
    bz->htim = htim;
    bz->tim_channel = channel;
}
References bz, Error_Handler(), buzzer_t::htim, NULL, and buzzer_t::tim_channel.
Referenced by main().
musica_maestro()
void musica_maestro (buzzer_t * bz, const note_t * partition, uint16_t melody_length)
Plays a melody by iterating through an array of notes.
Plays a melody from an array of notes.
Iterates through the provided array of note_t structures, playing each note for its specified duration.
Parameters
[in] bz Pointer to the initialized buzzer_t object.
[in] partition An array of note_t objects representing the melody.
[in] melody_length The number of notes in the partition array.
Returns
None
Definition at line 38 of file buzzer.c.
{
    if (bz == NULL || bz->htim == NULL || partition == NULL) {
        return; // Safety check
    }
    // Start the PWM signal. The duty cycle is set to 50% by configuring ARR/2.
    HAL_TIM_PWM_Start(bz->htim, bz->tim_channel);
    for (uint16_t i = 0; i < melody_length; i++) {
        uint16_t freq = partition[i].frequency;
        uint16_t duration = partition[i].duration_ms;
        if (freq == REST || duration == 0) {
            // Silence for a rest note
            __HAL_TIM_SET_COMPARE(bz->htim, bz->tim_channel, 0); // Set duty cycle to 0% for silence
            if (duration > 0) {
                HAL_Delay(duration);
            }
        } else {
            // Play a tone
            // Calculate the Auto-Reload Register (ARR) value for the desired frequency
            uint32_t arr_value = (TIMER_CLOCK_FREQ / (TIMER_PRESCALER * freq)) - 1;
            // Clamp the ARR value to the 16-bit timer limit
            if (arr_value > 0xFFFF) {
                arr_value = 0xFFFF;
            }
            // Set the timer period (determines frequency)
            __HAL_TIM_SET_AUTORELOAD(bz->htim, arr_value);
            // Set the duty cycle to 50% for a standard tone
            __HAL_TIM_SET_COMPARE(bz->htim, bz->tim_channel, arr_value / 2);
            // Hold the note for its duration
            HAL_Delay(duration);
        }
    }
    // Stop the PWM signal after the melody is finished
    HAL_TIM_PWM_Stop(bz->htim, bz->tim_channel);
}
References bz, note_t::duration_ms, note_t::frequency, buzzer_t::htim, NULL, REST, buzzer_t::tim_channel, TIMER_CLOCK_FREQ, and TIMER_PRESCALER.
Referenced by main().
Variable Documentation
buzzer
buzzer_t buzzer extern
Global instance of the buzzer object.
Definition at line 17 of file buzzer.c.