Da Vinci Firmware: Non-Finite Value Check Functions
Non-Finite Value Check Functions
Functions
boolean_T rtIsInf (real_T value)
Checks if a double-precision value is positive or negative infinity.
boolean_T rtIsInfF (real32_T value)
Checks if a single-precision value is positive or negative infinity.
boolean_T rtIsNaN (real_T value)
Checks if a double-precision value is Not-a-Number (NaN).
boolean_T rtIsNaNF (real32_T value)
Checks if a single-precision value is Not-a-Number (NaN).
Detailed Description
Function Documentation
rtIsInf()
boolean_T rtIsInf (real_T value)
Checks if a double-precision value is positive or negative infinity.
This is a wrapper around the standard C library function isinf().
Parameters
[in] value The real_T (double) value to check.
Returns
true if the value is infinite, false otherwise.
Definition at line 40 of file rt_nonfinite.c.
{
  return (isinf(value) != 0U);
}
Referenced by rt_powd_snf(), and rt_powd_snf().
rtIsInfF()
boolean_T rtIsInfF (real32_T value)
Checks if a single-precision value is positive or negative infinity.
This is a wrapper around the standard C library function isinf().
Parameters
[in] value The real32_T (float) value to check.
Returns
true if the value is infinite, false otherwise.
Definition at line 50 of file rt_nonfinite.c.
{
  return (isinf((real_T)value) != 0U);
}
rtIsNaN()
boolean_T rtIsNaN (real_T value)
Checks if a double-precision value is Not-a-Number (NaN).
This is a wrapper around the standard C library function isnan().
Parameters
[in] value The real_T (double) value to check.
Returns
true if the value is NaN, false otherwise.
Definition at line 60 of file rt_nonfinite.c.
{
  return (isnan(value) != 0U);
}
Referenced by optimalAngle(), rt_powd_snf(), and rt_powd_snf().
rtIsNaNF()
boolean_T rtIsNaNF (real32_T value)
Checks if a single-precision value is Not-a-Number (NaN).
This is a wrapper around the standard C library function isnan().
Parameters
[in] value The real32_T (float) value to check.
Returns
true if the value is NaN, false otherwise.
Definition at line 70 of file rt_nonfinite.c.
{
  return (isnan((real_T)value) != 0U);
}