Da Vinci Firmware: LSM6DSO32_free_fall
LSM6DSO32_free_fall
Peripheral Drivers » "LSM6DSO32 6-Axis IMU Driver"
This section group all the functions concerning the free fall detection.
Functions
int32_t lsm6dso32_ff_threshold_set (stmdev_ctx_t *ctx, lsm6dso32_ff_ths_t val)
Free fall threshold setting.[set].
int32_t lsm6dso32_ff_threshold_get (stmdev_ctx_t *ctx, lsm6dso32_ff_ths_t *val)
Free fall threshold setting.[get].
int32_t lsm6dso32_ff_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Free-fall duration event.[set] 1LSb = 1 / ODR.
int32_t lsm6dso32_ff_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Free-fall duration event.[get] 1LSb = 1 / ODR.
Detailed Description
This section group all the functions concerning the free fall detection.
Function Documentation
lsm6dso32_ff_dur_get()
int32_t lsm6dso32_ff_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Free-fall duration event.[get] 1LSb = 1 / ODR.
Parameters
ctx read / write interface definitions
val change the values of ff_dur in reg FREE_FALL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 5043 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_dur_t wake_up_dur;
  lsm6dso32_free_fall_t free_fall;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_DUR,
                           (uint8_t *)&wake_up_dur, 1);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FREE_FALL,
                             (uint8_t *)&free_fall, 1);
    *val = (wake_up_dur.ff_dur << 5) + free_fall.ff_dur;
  }
  return ret;
}
References lsm6dso32_wake_up_dur_t::ff_dur, LSM6DSO32_FREE_FALL, lsm6dso32_read_reg(), and LSM6DSO32_WAKE_UP_DUR.
lsm6dso32_ff_dur_set()
int32_t lsm6dso32_ff_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Free-fall duration event.[set] 1LSb = 1 / ODR.
Parameters
ctx read / write interface definitions
val change the values of ff_dur in reg FREE_FALL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 5002 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_dur_t wake_up_dur;
  lsm6dso32_free_fall_t free_fall;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_DUR,
                           (uint8_t *)&wake_up_dur, 1);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FREE_FALL,
                             (uint8_t *)&free_fall, 1);
  }
  if (ret == 0)
  {
    wake_up_dur.ff_dur = ((uint8_t)val & 0x20U) >> 5;
    free_fall.ff_dur = (uint8_t)val & 0x1FU;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_WAKE_UP_DUR,
                              (uint8_t *)&wake_up_dur, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_FREE_FALL,
                              (uint8_t *)&free_fall, 1);
  }
  return ret;
}
References lsm6dso32_wake_up_dur_t::ff_dur, lsm6dso32_free_fall_t::ff_dur, LSM6DSO32_FREE_FALL, lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_DUR, and lsm6dso32_write_reg().
lsm6dso32_ff_threshold_get()
int32_t lsm6dso32_ff_threshold_get (stmdev_ctx_t * ctx, lsm6dso32_ff_ths_t * val)
Free fall threshold setting.[get].
Parameters
ctx read / write interface definitions
val Get the values of ff_ths in reg FREE_FALL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 4963 of file lsm6dso32_reg.c.
{
  lsm6dso32_free_fall_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FREE_FALL, (uint8_t *)&reg, 1);
  switch (reg.ff_ths)
  {
    case LSM6DSO32_FF_TSH_312mg:
      *val = LSM6DSO32_FF_TSH_312mg;
      break;
    case LSM6DSO32_FF_TSH_438mg:
      *val = LSM6DSO32_FF_TSH_438mg;
      break;
    case LSM6DSO32_FF_TSH_500mg:
      *val = LSM6DSO32_FF_TSH_500mg;
      break;
    default:
      *val = LSM6DSO32_FF_TSH_312mg;
      break;
  }
  return ret;
}
References lsm6dso32_free_fall_t::ff_ths, LSM6DSO32_FF_TSH_312mg, LSM6DSO32_FF_TSH_438mg, LSM6DSO32_FF_TSH_500mg, LSM6DSO32_FREE_FALL, and lsm6dso32_read_reg().
lsm6dso32_ff_threshold_set()
int32_t lsm6dso32_ff_threshold_set (stmdev_ctx_t * ctx, lsm6dso32_ff_ths_t val)
Free fall threshold setting.[set].
Parameters
ctx read / write interface definitions
val change the values of ff_ths in reg FREE_FALL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 4938 of file lsm6dso32_reg.c.
{
  lsm6dso32_free_fall_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FREE_FALL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.ff_ths = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_FREE_FALL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_free_fall_t::ff_ths, LSM6DSO32_FREE_FALL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().