Da Vinci Firmware: "BMP3"
"BMP3"
Peripheral Drivers
Modules
Initialization
Initialize the sensor and device structure.
Soft reset
Perform soft reset of the sensor.
Sensor settings
Get / Set sensor settings.
Power mode
Set / Get power mode of the sensor.
Sensor Data
Get Sensor data.
Registers
Read / Write data to the given register address.
FIFO
FIFO operations of the sensor.
Sensor Status
Read status of the sensor.
Data Structures
struct bmp3_reg_calib_data
Register Trim Variables.
struct bmp3_adv_settings
bmp3 advance settings
struct bmp3_odr_filter_settings
bmp3 odr and filter settings
struct bmp3_sens_status
bmp3 sensor status flags
struct bmp3_int_status
bmp3 interrupt status flags
struct bmp3_err_status
bmp3 error status flags
struct bmp3_status
bmp3 status flags
struct bmp3_int_ctrl_settings
bmp3 interrupt pin settings
struct bmp3_settings
bmp3 device settings
struct bmp3_fifo_data
bmp3 fifo frame
struct bmp3_fifo_settings
bmp3 fifo configuration
struct bmp3_quantized_calib_data
Quantized Trim Variables.
struct bmp3_calib_data
Calibration data.
struct bmp3_data
bmp3 sensor structure which comprises of temperature and pressure data.
struct bmp3_uncomp_data
bmp3 sensor structure which comprises of un-compensated temperature and pressure data.
struct bmp3_dev
bmp3 device structure
Functions
int8_t bmp390_P_write (uint8_t reg_addr, const uint8_t *buf, uint32_t len, void *intf_ptr)
SPI write function for the primary Barometer (bmp390).
int8_t bmp390_P_read (uint8_t reg_addr, uint8_t *buf, uint32_t len, void *intf_ptr)
SPI read function for the primary Barometer (bmp390).
int8_t bmp390_B_write (uint8_t reg_addr, const uint8_t *buf, uint32_t len, void *intf_ptr)
SPI write function for the backup Barometer (bmp390).
int8_t bmp390_B_read (uint8_t reg_addr, uint8_t *buf, uint32_t len, void *intf_ptr)
SPI read function for the backup Barometer (bmp390).
int8_t init_bmp390_p (struct bmp3_dev *bmp390)
Initializes the primary barometer (BMP390).
int8_t init_bmp390_B (struct bmp3_dev *bmp390)
Initializes the backup barometer (BMP390).
Detailed Description
bmp3_fifo_flush
// * int8_t bmp3_fifo_flush(const struct bmp3_dev *dev);
// *
This API performs fifo flush
Parameters
[in] dev : Structure instance of bmp3_dev.
Returns
Result of API execution status
Return values
0 -> Success
>0 -> Warning
<0 -> Error ‍/ int8_t bmp3_fifo_flush(struct bmp3_dev *dev);
/**
Function Documentation
bmp390_B_read()
int8_t bmp390_B_read (uint8_t reg_addr, uint8_t * buf, uint32_t len, void * intf_ptr)
SPI read function for the backup Barometer (bmp390).
This function is designed to be passed as a function pointer to the STMicroelectronics barometer driver library. It handles SPI bus transactions.
Parameters
[in] reg_addr The 7-bit register address to read from. The read bit is set automatically.
[out] buf Pointer to the buffer where read data will be stored.
[in] len The number of bytes to read.
Returns
int32_t HAL_OK on success, HAL_ERROR on failure.
Definition at line 623 of file utilities.c.
{
    int8_t result = HAL_ERROR;
    if(HAL_GPIO_ReadPin(IMU_CS_GPIO_Port,IMU_CS_Pin)!=GPIO_PIN_SET){IMU_CS_HIGH;}
    if(HAL_GPIO_ReadPin(MAG_CS_GPIO_Port,MAG_CS_Pin)!=GPIO_PIN_SET){MAG_CS_HIGH;}
    BMP390_CS_LOW;
    if (HAL_SPI_Transmit(&hspi3, &reg_addr, 1, 100) == HAL_OK) {
        if (HAL_SPI_Receive(&hspi3, buf, len, 100) == HAL_OK) {
            result = HAL_OK;
        }
    }
    BMP390_CS_HIGH;
    return result;
}
References HAL_ERROR, HAL_OK, and hspi3.
Referenced by bmp3_B_spi_init().
bmp390_B_write()
int8_t bmp390_B_write (uint8_t reg_addr, const uint8_t * buf, uint32_t len, void * intf_ptr)
SPI write function for the backup Barometer (bmp390).
This function is designed to be passed as a function pointer to the STMicroelectronics barometer driver library. It handles SPI bus transactions.
Parameters
[in] reg_addr The 7-bit register address to write to.
[in] buf Pointer to the data buffer to be written.
[in] len The number of bytes to write.
Returns
int32_t HAL_OK on success, HAL_ERROR on failure.
Definition at line 603 of file utilities.c.
{
    int8_t result = HAL_ERROR;
    if(HAL_GPIO_ReadPin(IMU_CS_GPIO_Port,IMU_CS_Pin)!=GPIO_PIN_SET){IMU_CS_HIGH;}
    if(HAL_GPIO_ReadPin(MAG_CS_GPIO_Port,MAG_CS_Pin)!=GPIO_PIN_SET){MAG_CS_HIGH;}
    BMP390_CS_LOW;
    if (HAL_SPI_Transmit(&hspi3, &reg_addr, 1, 100) == HAL_OK) {
        if (HAL_SPI_Transmit(&hspi3, (uint8_t *)buf, len, 100) == HAL_OK) {
            result = HAL_OK;
        }
    }
    BMP390_CS_HIGH;
    return result;
}
References HAL_ERROR, HAL_OK, and hspi3.
Referenced by bmp3_B_spi_init().
bmp390_P_read()
int8_t bmp390_P_read (uint8_t reg_addr, uint8_t * buf, uint32_t len, void * intf_ptr)
SPI read function for the primary Barometer (bmp390).
This function is designed to be passed as a function pointer to the STMicroelectronics barometer driver library. It handles SPI bus transactions.
Parameters
[in] reg_addr The 7-bit register address to read from. The read bit is set automatically.
[out] buf Pointer to the buffer where read data will be stored.
[in] len The number of bytes to read.
Returns
int32_t HAL_OK on success, HAL_ERROR on failure.
Definition at line 122 of file utilities.c.
{
    int8_t result = HAL_ERROR;
        uint8_t tx_buffer[len + 1]; // Buffer for address + dummy bytes
        uint8_t rx_buffer[len + 1]; // Buffer for received dummy byte + data
        reg_addr |= 0x80; // Crucial: Set the MSB for a read operation (check datasheet if different)
        tx_buffer[0] = reg_addr;
        // Fill the rest of the transmit buffer with dummy bytes
        for (uint32_t i = 1; i <= len; i++) {
            tx_buffer[i] = 0xFF; // Or any dummy value
        }
        // Ensure other sensors are deselected
        if(HAL_GPIO_ReadPin(IMU_CS_GPIO_Port,IMU_CS_Pin)!=GPIO_PIN_SET){IMU_CS_HIGH;}
        if(HAL_GPIO_ReadPin(MAG_CS_GPIO_Port,MAG_CS_Pin)!=GPIO_PIN_SET){MAG_CS_HIGH;}
        if(HAL_GPIO_ReadPin(BARO_CS_GPIO_Port,BARO_CS_Pin)!=GPIO_PIN_RESET){BMP390_CS_LOW;}
        if (HAL_SPI_TransmitReceive(&hspi2, tx_buffer, rx_buffer, len + 1, 100) == HAL_OK) {
            // Data from the sensor starts at rx_buffer[1]
            for (uint32_t i = 0; i < len; i++) {
                buf[i] = rx_buffer[i + 1];
            }
            result = HAL_OK;
        }
        if(HAL_GPIO_ReadPin(BARO_CS_GPIO_Port,BARO_CS_Pin)!=GPIO_PIN_SET){BMP390_CS_HIGH;}
        return result;
}
References HAL_ERROR, HAL_OK, and hspi2.
Referenced by bmp3_P_spi_init().
bmp390_P_write()
int8_t bmp390_P_write (uint8_t reg_addr, const uint8_t * buf, uint32_t len, void * intf_ptr)
SPI write function for the primary Barometer (bmp390).
This function is designed to be passed as a function pointer to the STMicroelectronics barometer driver library. It handles SPI bus transactions.
Parameters
[in] reg_addr The 7-bit register address to write to.
[in] buf Pointer to the data buffer to be written.
[in] len The number of bytes to write.
Returns
int32_t HAL_OK on success, HAL_ERROR on failure.
Definition at line 103 of file utilities.c.
{
    int8_t result = HAL_ERROR;
    if(HAL_GPIO_ReadPin(IMU_CS_GPIO_Port,IMU_CS_Pin)!=GPIO_PIN_SET){IMU_CS_HIGH;}
    if(HAL_GPIO_ReadPin(MAG_CS_GPIO_Port,MAG_CS_Pin)!=GPIO_PIN_SET){MAG_CS_HIGH;}
    if(HAL_GPIO_ReadPin(BARO_CS_GPIO_Port,BARO_CS_Pin)!=GPIO_PIN_RESET){BMP390_CS_LOW;}
    if (HAL_SPI_Transmit(&hspi2, &reg_addr, 1, 100) == HAL_OK) {
        if (HAL_SPI_Transmit(&hspi2, (uint8_t *)buf, len, 100) == HAL_OK) {
            result = HAL_OK;
        }
    }
    if(HAL_GPIO_ReadPin(BARO_CS_GPIO_Port,BARO_CS_Pin)!=GPIO_PIN_SET){BMP390_CS_HIGH;}
    return result;
}
References HAL_ERROR, HAL_OK, and hspi2.
Referenced by bmp3_P_spi_init().
init_bmp390_B()
int8_t init_bmp390_B (struct bmp3_dev * bmp390)
Initializes the backup barometer (BMP390).
Configures the barometer for normal operation with specified oversampling and data rate settings.
Parameters
[in,out] bmp390 Pointer to the bmp3_dev driver context structure.
Returns
int8_t HAL_OK on successful initialization, HAL_ERROR otherwise.
Definition at line 723 of file utilities.c.
{
    int8_t result = HAL_ERROR;
    uint8_t settings_sel = 0;
    struct bmp3_settings settings = { 0 };
    result = bmp3_B_spi_init(bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    result = bmp3_init(bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    /* enabling both pressure and temperature reading */
    settings.press_en = BMP3_ENABLE;
    settings.temp_en = BMP3_ENABLE;
    /* interrupt disabling */
    settings.int_settings.drdy_en = BMP3_DISABLE;
    /* pressure and temperature oversampling */
    settings.odr_filter.press_os = BMP3_NO_OVERSAMPLING;
    settings.odr_filter.temp_os = BMP3_NO_OVERSAMPLING;
    /* output data rate */
    settings.odr_filter.odr = BMP3_ODR_200_HZ;
    /* IIR filter disabling */
    settings.odr_filter.iir_filter = BMP3_IIR_FILTER_DISABLE;
    /* specifying all the settings we want to modify using the bmp3_settings struct */
    settings_sel = BMP3_SEL_PRESS_EN | BMP3_SEL_TEMP_EN |
                   BMP3_SEL_PRESS_OS | BMP3_SEL_TEMP_OS |
                   BMP3_SEL_IIR_FILTER | BMP3_SEL_ODR;
    /* setting the previously specified settings */
    result = bmp3_set_sensor_settings(settings_sel, &settings, bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    /* setting the operating mode of the sensor */
    settings.op_mode = BMP3_MODE_NORMAL;
    result = bmp3_set_op_mode(&settings, bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    return HAL_OK;
}
References bmp3_B_spi_init(), BMP3_DISABLE, BMP3_ENABLE, BMP3_IIR_FILTER_DISABLE, bmp3_init(), BMP3_MODE_NORMAL, BMP3_NO_OVERSAMPLING, BMP3_ODR_200_HZ, BMP3_OK, BMP3_SEL_IIR_FILTER, BMP3_SEL_ODR, BMP3_SEL_PRESS_EN, BMP3_SEL_PRESS_OS, BMP3_SEL_TEMP_EN, BMP3_SEL_TEMP_OS, bmp3_set_op_mode(), bmp3_set_sensor_settings(), bmp3_int_ctrl_settings::drdy_en, HAL_ERROR, HAL_OK, bmp3_odr_filter_settings::iir_filter, bmp3_settings::int_settings, bmp3_odr_filter_settings::odr, bmp3_settings::odr_filter, bmp3_settings::op_mode, bmp3_settings::press_en, bmp3_odr_filter_settings::press_os, bmp3_settings::temp_en, and bmp3_odr_filter_settings::temp_os.
Referenced by main().
init_bmp390_p()
int8_t init_bmp390_p (struct bmp3_dev * bmp390)
Initializes the primary barometer (BMP390).
Configures the barometer for normal operation with specified oversampling and data rate settings.
Parameters
[in,out] bmp390 Pointer to the bmp3_dev driver context structure.
Returns
int8_t HAL_OK on successful initialization, HAL_ERROR otherwise.
Definition at line 252 of file utilities.c.
{
    int8_t result = HAL_ERROR;
    uint8_t settings_sel = 0;
    struct bmp3_settings settings = { 0 };
    //IMU_CS_HIGH;
    //MAG_CS_HIGH;
    result = bmp3_P_spi_init(bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    //BMP390_CS_LOW;
    result = bmp3_init(bmp390);
    //BMP390_CS_HIGH;
    if (result != BMP3_OK)
        return HAL_ERROR;
    /* enabling both pressure and temperature reading */
    settings.press_en = BMP3_ENABLE;
    settings.temp_en = BMP3_ENABLE;
    /* interrupt disabling */
    settings.int_settings.drdy_en = BMP3_DISABLE;
    /* pressure and temperature oversampling */
    settings.odr_filter.press_os = BMP3_NO_OVERSAMPLING;
    settings.odr_filter.temp_os = BMP3_NO_OVERSAMPLING;
    /* output data rate */
    settings.odr_filter.odr = BMP3_ODR_200_HZ;
    /* IIR filter disabling */
    settings.odr_filter.iir_filter = BMP3_IIR_FILTER_DISABLE;
    /* specifying all the settings we want to modify using the bmp3_settings struct */
    settings_sel = BMP3_SEL_PRESS_EN | BMP3_SEL_TEMP_EN |
                   BMP3_SEL_PRESS_OS | BMP3_SEL_TEMP_OS |
                   BMP3_SEL_IIR_FILTER | BMP3_SEL_ODR;
    /* setting the previously specified settings */
    result = bmp3_set_sensor_settings(settings_sel, &settings, bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    /* setting the operating mode of the sensor */
    settings.op_mode = BMP3_MODE_NORMAL;
    result = bmp3_set_op_mode(&settings, bmp390);
    if (result != BMP3_OK)
        return HAL_ERROR;
    return HAL_OK;
}
References BMP3_DISABLE, BMP3_ENABLE, BMP3_IIR_FILTER_DISABLE, bmp3_init(), BMP3_MODE_NORMAL, BMP3_NO_OVERSAMPLING, BMP3_ODR_200_HZ, BMP3_OK, bmp3_P_spi_init(), BMP3_SEL_IIR_FILTER, BMP3_SEL_ODR, BMP3_SEL_PRESS_EN, BMP3_SEL_PRESS_OS, BMP3_SEL_TEMP_EN, BMP3_SEL_TEMP_OS, bmp3_set_op_mode(), bmp3_set_sensor_settings(), bmp3_int_ctrl_settings::drdy_en, HAL_ERROR, HAL_OK, bmp3_odr_filter_settings::iir_filter, bmp3_settings::int_settings, bmp3_odr_filter_settings::odr, bmp3_settings::odr_filter, bmp3_settings::op_mode, bmp3_settings::press_en, bmp3_odr_filter_settings::press_os, bmp3_settings::temp_en, and bmp3_odr_filter_settings::temp_os.
Referenced by main().