Da Vinci Firmware: LSM6DSO32_Pedometer
LSM6DSO32_Pedometer
Peripheral Drivers » "LSM6DSO32 IMU Driver"
This section groups all the functions that manage pedometer.
Functions
int32_t lsm6dso32_pedo_sens_set (stmdev_ctx_t *ctx, lsm6dso32_pedo_md_t val)
Enable pedometer algorithm.[set].
int32_t lsm6dso32_pedo_sens_get (stmdev_ctx_t *ctx, lsm6dso32_pedo_md_t *val)
Enable pedometer algorithm.[get].
int32_t lsm6dso32_pedo_step_detect_get (stmdev_ctx_t *ctx, uint8_t *val)
Interrupt status bit for step detection.[get].
int32_t lsm6dso32_pedo_debounce_steps_set (stmdev_ctx_t *ctx, uint8_t *buff)
Pedometer debounce configuration register (r/w).[set].
int32_t lsm6dso32_pedo_debounce_steps_get (stmdev_ctx_t *ctx, uint8_t *buff)
Pedometer debounce configuration register (r/w).[get].
int32_t lsm6dso32_pedo_steps_period_set (stmdev_ctx_t *ctx, uint16_t val)
Time period register for step detection on delta time (r/w).[set].
int32_t lsm6dso32_pedo_steps_period_get (stmdev_ctx_t *ctx, uint16_t *val)
Time period register for step detection on delta time (r/w).[get].
int32_t lsm6dso32_pedo_int_mode_set (stmdev_ctx_t *ctx, lsm6dso32_carry_count_en_t val)
Set when user wants to generate interrupt on count overflow event/every step.[set].
int32_t lsm6dso32_pedo_int_mode_get (stmdev_ctx_t *ctx, lsm6dso32_carry_count_en_t *val)
Set when user wants to generate interrupt on count overflow event/every step.[get].
Detailed Description
This section groups all the functions that manage pedometer.
Function Documentation
lsm6dso32_pedo_debounce_steps_get()
int32_t lsm6dso32_pedo_debounce_steps_get (stmdev_ctx_t * ctx, uint8_t * buff)
Pedometer debounce configuration register (r/w).[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7131 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_DEB_STEPS_CONF,
                                  buff);
  return ret;
}
References lsm6dso32_ln_pg_read_byte(), and LSM6DSO32_PEDO_DEB_STEPS_CONF.
lsm6dso32_pedo_debounce_steps_set()
int32_t lsm6dso32_pedo_debounce_steps_set (stmdev_ctx_t * ctx, uint8_t * buff)
Pedometer debounce configuration register (r/w).[set].
Parameters
ctx read / write interface definitions
buff buffer that contains data to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7112 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_PEDO_DEB_STEPS_CONF,
                                   buff);
  return ret;
}
References lsm6dso32_ln_pg_write_byte(), and LSM6DSO32_PEDO_DEB_STEPS_CONF.
lsm6dso32_pedo_int_mode_get()
int32_t lsm6dso32_pedo_int_mode_get (stmdev_ctx_t * ctx, lsm6dso32_carry_count_en_t * val)
Set when user wants to generate interrupt on count overflow event/every step.[get].
Parameters
ctx read / write interface definitions
val Get the values of carry_count_en in reg PEDO_CMD_REG
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7235 of file lsm6dso32_reg.c.
{
  lsm6dso32_pedo_cmd_reg_t reg;
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_CMD_REG,
                                  (uint8_t *)&reg);
  switch (reg.carry_count_en)
  {
    case LSM6DSO32_EVERY_STEP:
      *val = LSM6DSO32_EVERY_STEP;
      break;
    case LSM6DSO32_COUNT_OVERFLOW:
      *val = LSM6DSO32_COUNT_OVERFLOW;
      break;
    default:
      *val = LSM6DSO32_EVERY_STEP;
      break;
  }
  return ret;
}
References lsm6dso32_pedo_cmd_reg_t::carry_count_en, LSM6DSO32_COUNT_OVERFLOW, LSM6DSO32_EVERY_STEP, lsm6dso32_ln_pg_read_byte(), and LSM6DSO32_PEDO_CMD_REG.
lsm6dso32_pedo_int_mode_set()
int32_t lsm6dso32_pedo_int_mode_set (stmdev_ctx_t * ctx, lsm6dso32_carry_count_en_t val)
Set when user wants to generate interrupt on count overflow event/every step.[set].
Parameters
ctx read / write interface definitions
val change the values of carry_count_en in reg PEDO_CMD_REG
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7207 of file lsm6dso32_reg.c.
{
  lsm6dso32_pedo_cmd_reg_t reg;
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_CMD_REG,
                                  (uint8_t *)&reg);
  if (ret == 0)
  {
    reg.carry_count_en = (uint8_t)val;
    ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_PEDO_CMD_REG,
                                     (uint8_t *)&reg);
  }
  return ret;
}
References lsm6dso32_pedo_cmd_reg_t::carry_count_en, lsm6dso32_ln_pg_read_byte(), lsm6dso32_ln_pg_write_byte(), and LSM6DSO32_PEDO_CMD_REG.
lsm6dso32_pedo_sens_get()
int32_t lsm6dso32_pedo_sens_get (stmdev_ctx_t * ctx, lsm6dso32_pedo_md_t * val)
Enable pedometer algorithm.[get].
Parameters
ctx read / write interface definitions
val turn on and configure pedometer
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7008 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_en_a_t emb_func_en_a;
  lsm6dso32_emb_func_en_b_t emb_func_en_b;
  lsm6dso32_pedo_cmd_reg_t pedo_cmd_reg;
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_CMD_REG,
                                  (uint8_t *)&pedo_cmd_reg);
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                             (uint8_t *)&emb_func_en_a, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                             (uint8_t *)&emb_func_en_b, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  switch ((pedo_cmd_reg.ad_det_en << 5) | (pedo_cmd_reg.fp_rejection_en
                                           << 4) |
          (emb_func_en_b.pedo_adv_en << 1) | emb_func_en_a.pedo_en)
  {
    case LSM6DSO32_PEDO_DISABLE:
      *val = LSM6DSO32_PEDO_DISABLE;
      break;
    case LSM6DSO32_PEDO_BASE_MODE:
      *val = LSM6DSO32_PEDO_BASE_MODE;
      break;
    case LSM6DSO32_PEDO_ADV_MODE:
      *val = LSM6DSO32_PEDO_ADV_MODE;
      break;
    case LSM6DSO32_FALSE_STEP_REJ:
      *val = LSM6DSO32_FALSE_STEP_REJ;
      break;
    case LSM6DSO32_FALSE_STEP_REJ_ADV_MODE:
      *val = LSM6DSO32_FALSE_STEP_REJ_ADV_MODE;
      break;
    default:
      *val = LSM6DSO32_PEDO_DISABLE;
      break;
  }
  return ret;
}
References lsm6dso32_pedo_cmd_reg_t::ad_det_en, lsm6dso32_pedo_cmd_reg_t::fp_rejection_en, LSM6DSO32_EMB_FUNC_EN_A, LSM6DSO32_EMB_FUNC_EN_B, LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FALSE_STEP_REJ, LSM6DSO32_FALSE_STEP_REJ_ADV_MODE, lsm6dso32_ln_pg_read_byte(), lsm6dso32_mem_bank_set(), LSM6DSO32_PEDO_ADV_MODE, LSM6DSO32_PEDO_BASE_MODE, LSM6DSO32_PEDO_CMD_REG, LSM6DSO32_PEDO_DISABLE, lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_emb_func_en_b_t::pedo_adv_en, and lsm6dso32_emb_func_en_a_t::pedo_en.
lsm6dso32_pedo_sens_set()
int32_t lsm6dso32_pedo_sens_set (stmdev_ctx_t * ctx, lsm6dso32_pedo_md_t val)
Enable pedometer algorithm.[set].
Parameters
ctx read / write interface definitions
val turn on and configure pedometer
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6942 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_en_a_t emb_func_en_a;
  lsm6dso32_emb_func_en_b_t emb_func_en_b;
  lsm6dso32_pedo_cmd_reg_t pedo_cmd_reg;
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_CMD_REG,
                                  (uint8_t *)&pedo_cmd_reg);
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                             (uint8_t *)&emb_func_en_a, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                             (uint8_t *)&emb_func_en_b, 1);
    emb_func_en_a.pedo_en = (uint8_t)val & 0x01U;
    emb_func_en_b.pedo_adv_en = ((uint8_t)val & 0x02U) >> 1;
    pedo_cmd_reg.fp_rejection_en = ((uint8_t)val & 0x10U) >> 4;
    pedo_cmd_reg.ad_det_en = ((uint8_t)val & 0x20U) >> 5;
  }
  if (ret == 0)
  {
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_A,
                              (uint8_t *)&emb_func_en_a, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                              (uint8_t *)&emb_func_en_b, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_PEDO_CMD_REG,
                                     (uint8_t *)&pedo_cmd_reg);
  }
  return ret;
}
References lsm6dso32_pedo_cmd_reg_t::ad_det_en, lsm6dso32_pedo_cmd_reg_t::fp_rejection_en, LSM6DSO32_EMB_FUNC_EN_A, LSM6DSO32_EMB_FUNC_EN_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_ln_pg_read_byte(), lsm6dso32_ln_pg_write_byte(), lsm6dso32_mem_bank_set(), LSM6DSO32_PEDO_CMD_REG, lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_write_reg(), and lsm6dso32_emb_func_en_a_t::pedo_en.
lsm6dso32_pedo_step_detect_get()
int32_t lsm6dso32_pedo_step_detect_get (stmdev_ctx_t * ctx, uint8_t * val)
Interrupt status bit for step detection.[get].
Parameters
ctx read / write interface definitions
val change the values of is_step_det in reg EMB_FUNC_STATUS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7081 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_status_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_STATUS,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.is_step_det;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_status_t::is_step_det, LSM6DSO32_EMB_FUNC_STATUS, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_pedo_steps_period_get()
int32_t lsm6dso32_pedo_steps_period_get (stmdev_ctx_t * ctx, uint16_t * val)
Time period register for step detection on delta time (r/w).[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7178 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_SC_DELTAT_L,
                                  &buff[0]);
  if (ret == 0)
  {
    ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_PEDO_SC_DELTAT_H,
                                    &buff[1]);
    *val = buff[1];
    *val = (*val * 256U) +  buff[0];
  }
  return ret;
}
References lsm6dso32_ln_pg_read_byte(), LSM6DSO32_PEDO_SC_DELTAT_H, and LSM6DSO32_PEDO_SC_DELTAT_L.
lsm6dso32_pedo_steps_period_set()
int32_t lsm6dso32_pedo_steps_period_set (stmdev_ctx_t * ctx, uint16_t val)
Time period register for step detection on delta time (r/w).[set].
Parameters
ctx read / write interface definitions
buff buffer that contains data to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 7150 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  buff[1] = (uint8_t)(val / 256U);
  buff[0] = (uint8_t)(val - (buff[1] * 256U));
  ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_PEDO_SC_DELTAT_L,
                                   &buff[0]);
  if (ret == 0)
  {
    ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_PEDO_SC_DELTAT_H,
                                     &buff[1]);
  }
  return ret;
}
References lsm6dso32_ln_pg_write_byte(), LSM6DSO32_PEDO_SC_DELTAT_H, and LSM6DSO32_PEDO_SC_DELTAT_L.