Da Vinci Firmware: "output"
"output"
Peripheral Drivers » "LSM6DSO32 6-Axis IMU Driver"
This section groups all the data output functions.
Functions
int32_t lsm6dso32_rounding_mode_set (stmdev_ctx_t *ctx, lsm6dso32_rounding_t val)
Circular burst-mode (rounding) read of the output registers.[set].
int32_t lsm6dso32_rounding_mode_get (stmdev_ctx_t *ctx, lsm6dso32_rounding_t *val)
Gyroscope UI chain full-scale selection.[get].
int32_t lsm6dso32_temperature_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Temperature data output register (r). L and H registers together express a 16-bit word in two’s complement.[get].
int32_t lsm6dso32_angular_rate_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dso32_acceleration_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Linear acceleration output register. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dso32_fifo_out_raw_get (stmdev_ctx_t *ctx, uint8_t *buff)
FIFO data output [get].
int32_t lsm6dso32_number_of_steps_get (stmdev_ctx_t *ctx, uint16_t *val)
Step counter output register.[get].
int32_t lsm6dso32_steps_reset (stmdev_ctx_t *ctx)
Reset step counter register.[get].
Detailed Description
This section groups all the data output functions.
Function Documentation
lsm6dso32_acceleration_raw_get()
int32_t lsm6dso32_acceleration_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Linear acceleration output register. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1299 of file lsm6dso32_reg.c.
{
  uint8_t buff[6];
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_OUTX_L_A, buff, 6);
  val[0] = (int16_t)buff[1];
  val[0] = (val[0] * 256) + (int16_t)buff[0];
  val[1] = (int16_t)buff[3];
  val[1] = (val[1] * 256) + (int16_t)buff[2];
  val[2] = (int16_t)buff[5];
  val[2] = (val[2] * 256) + (int16_t)buff[4];
  return ret;
}
References LSM6DSO32_OUTX_L_A, and lsm6dso32_read_reg().
Referenced by calibrateIMU(), and StartSensor_Task().
lsm6dso32_angular_rate_raw_get()
int32_t lsm6dso32_angular_rate_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1273 of file lsm6dso32_reg.c.
{
  uint8_t buff[6];
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_OUTX_L_G, buff, 6);
  val[0] = (int16_t)buff[1];
  val[0] = (val[0] * 256) + (int16_t)buff[0];
  val[1] = (int16_t)buff[3];
  val[1] = (val[1] * 256) + (int16_t)buff[2];
  val[2] = (int16_t)buff[5];
  val[2] = (val[2] * 256) + (int16_t)buff[4];
  return ret;
}
References LSM6DSO32_OUTX_L_G, and lsm6dso32_read_reg().
Referenced by calibrateIMU(), and StartSensor_Task().
lsm6dso32_fifo_out_raw_get()
int32_t lsm6dso32_fifo_out_raw_get (stmdev_ctx_t * ctx, uint8_t * buff)
FIFO data output [get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1324 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FIFO_DATA_OUT_X_L, buff, 6);
  return ret;
}
References LSM6DSO32_FIFO_DATA_OUT_X_L, and lsm6dso32_read_reg().
lsm6dso32_number_of_steps_get()
int32_t lsm6dso32_number_of_steps_get (stmdev_ctx_t * ctx, uint16_t * val)
Step counter output register.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1341 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_STEP_COUNTER_L, buff, 2);
  }
  if (ret == 0)
  {
    *val = buff[1];
    *val = (*val * 256U) +  buff[0];
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_STEP_COUNTER_L, and LSM6DSO32_USER_BANK.
lsm6dso32_rounding_mode_get()
int32_t lsm6dso32_rounding_mode_get (stmdev_ctx_t * ctx, lsm6dso32_rounding_t * val)
Gyroscope UI chain full-scale selection.[get].
Parameters
ctx read / write interface definitions
val Get the values of rounding in reg CTRL5_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1208 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl5_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL5_C, (uint8_t *)&reg, 1);
  switch (reg.rounding)
  {
    case LSM6DSO32_NO_ROUND:
      *val = LSM6DSO32_NO_ROUND;
      break;
    case LSM6DSO32_ROUND_XL:
      *val = LSM6DSO32_ROUND_XL;
      break;
    case LSM6DSO32_ROUND_GY:
      *val = LSM6DSO32_ROUND_GY;
      break;
    case LSM6DSO32_ROUND_GY_XL:
      *val = LSM6DSO32_ROUND_GY_XL;
      break;
    default:
      *val = LSM6DSO32_NO_ROUND;
      break;
  }
  return ret;
}
References LSM6DSO32_CTRL5_C, LSM6DSO32_NO_ROUND, lsm6dso32_read_reg(), LSM6DSO32_ROUND_GY, LSM6DSO32_ROUND_GY_XL, LSM6DSO32_ROUND_XL, and lsm6dso32_ctrl5_c_t::rounding.
lsm6dso32_rounding_mode_set()
int32_t lsm6dso32_rounding_mode_set (stmdev_ctx_t * ctx, lsm6dso32_rounding_t val)
Circular burst-mode (rounding) read of the output registers.[set].
Parameters
ctx read / write interface definitions
val change the values of rounding in reg CTRL5_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1183 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl5_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL5_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.rounding = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL5_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LSM6DSO32_CTRL5_C, lsm6dso32_read_reg(), lsm6dso32_write_reg(), and lsm6dso32_ctrl5_c_t::rounding.
lsm6dso32_steps_reset()
int32_t lsm6dso32_steps_reset (stmdev_ctx_t * ctx)
Reset step counter register.[get].
Parameters
ctx read / write interface definitions
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1371 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_src_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_SRC, (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg.pedo_rst_step = PROPERTY_ENABLE;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_SRC,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMB_FUNC_SRC, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_write_reg(), lsm6dso32_emb_func_src_t::pedo_rst_step, and PROPERTY_ENABLE.
lsm6dso32_temperature_raw_get()
int32_t lsm6dso32_temperature_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Temperature data output register (r). L and H registers together express a 16-bit word in two’s complement.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1252 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_OUT_TEMP_L, buff, 2);
  val[0] = (int16_t)buff[1];
  val[0] = (val[0] * 256) + (int16_t)buff[0];
  return ret;
}
References LSM6DSO32_OUT_TEMP_L, and lsm6dso32_read_reg().
Referenced by calibrateIMU().