Da Vinci Firmware: Davinci_2/Core/Src/stm32h7xx_hal_msp.c File Reference
stm32h7xx_hal_msp.c File Reference
This file provides code for the MSP Initialization and de-Initialization codes.
#include "main.h"
Functions
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
void HAL_MspInit (void)
void HAL_ADC_MspInit (ADC_HandleTypeDef *hadc)
ADC MSP Initialization This function configures the hardware resources used in this example.
void HAL_ADC_MspDeInit (ADC_HandleTypeDef *hadc)
ADC MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_FDCAN_MspInit (FDCAN_HandleTypeDef *hfdcan)
FDCAN MSP Initialization This function configures the hardware resources used in this example.
void HAL_FDCAN_MspDeInit (FDCAN_HandleTypeDef *hfdcan)
FDCAN MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_QSPI_MspInit (QSPI_HandleTypeDef *hqspi)
QSPI MSP Initialization This function configures the hardware resources used in this example.
void HAL_QSPI_MspDeInit (QSPI_HandleTypeDef *hqspi)
QSPI MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_SPI_MspInit (SPI_HandleTypeDef *hspi)
SPI MSP Initialization This function configures the hardware resources used in this example.
void HAL_SPI_MspDeInit (SPI_HandleTypeDef *hspi)
SPI MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_TIM_PWM_MspInit (TIM_HandleTypeDef *htim_pwm)
TIM_PWM MSP Initialization This function configures the hardware resources used in this example.
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef *htim_base)
TIM_Base MSP Initialization This function configures the hardware resources used in this example.
void HAL_TIM_PWM_MspDeInit (TIM_HandleTypeDef *htim_pwm)
TIM_PWM MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef *htim_base)
TIM_Base MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_UART_MspInit (UART_HandleTypeDef *huart)
UART MSP Initialization This function configures the hardware resources used in this example.
void HAL_UART_MspDeInit (UART_HandleTypeDef *huart)
UART MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_PCD_MspInit (PCD_HandleTypeDef *hpcd)
PCD MSP Initialization This function configures the hardware resources used in this example.
void HAL_PCD_MspDeInit (PCD_HandleTypeDef *hpcd)
PCD MSP De-Initialization This function freeze the hardware resources used in this example.
Variables
MDMA_HandleTypeDef hmdma_quadspi_fifo_th
DMA_HandleTypeDef hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_tx
static uint32_t HAL_RCC_ADC12_CLK_ENABLED =0
Detailed Description
This file provides code for the MSP Initialization and de-Initialization codes.
Attention
Copyright (c) 2025 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file stm32h7xx_hal_msp.c.
Function Documentation
HAL_ADC_MspDeInit()
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * hadc)
ADC MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hadc ADC handle pointer
Return values
None
ADC1 GPIO Configuration PC1 ---—> ADC1_INP11 PC5 ---—> ADC1_INP8
ADC2 GPIO Configuration PB0 ---—> ADC2_INP9
ADC3 GPIO Configuration PC1 ---—> ADC3_INP11
Definition at line 178 of file stm32h7xx_hal_msp.c.
{
  if(hadc->Instance==ADC1)
  {
    /* USER CODE BEGIN ADC1_MspDeInit 0 */
    /* USER CODE END ADC1_MspDeInit 0 */
    /* Peripheral clock disable */
    HAL_RCC_ADC12_CLK_ENABLED--;
    if(HAL_RCC_ADC12_CLK_ENABLED==0){
      __HAL_RCC_ADC12_CLK_DISABLE();
    }
    HAL_GPIO_DeInit(GPIOC, ADC3_BATTERY_Pin|ADC1_Pyrocheck1_Pin);
    /* USER CODE BEGIN ADC1_MspDeInit 1 */
    /* USER CODE END ADC1_MspDeInit 1 */
  }
  else if(hadc->Instance==ADC2)
  {
    /* USER CODE BEGIN ADC2_MspDeInit 0 */
    /* USER CODE END ADC2_MspDeInit 0 */
    /* Peripheral clock disable */
    HAL_RCC_ADC12_CLK_ENABLED--;
    if(HAL_RCC_ADC12_CLK_ENABLED==0){
      __HAL_RCC_ADC12_CLK_DISABLE();
    }
    HAL_GPIO_DeInit(ADC2_Pyrocheck2_GPIO_Port, ADC2_Pyrocheck2_Pin);
    /* USER CODE BEGIN ADC2_MspDeInit 1 */
    /* USER CODE END ADC2_MspDeInit 1 */
  }
  else if(hadc->Instance==ADC3)
  {
    /* USER CODE BEGIN ADC3_MspDeInit 0 */
    /* USER CODE END ADC3_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_ADC3_CLK_DISABLE();
    HAL_GPIO_DeInit(ADC3_BATTERY_GPIO_Port, ADC3_BATTERY_Pin);
    /* USER CODE BEGIN ADC3_MspDeInit 1 */
    /* USER CODE END ADC3_MspDeInit 1 */
  }
}
References HAL_RCC_ADC12_CLK_ENABLED.
HAL_ADC_MspInit()
void HAL_ADC_MspInit (ADC_HandleTypeDef * hadc)
ADC MSP Initialization This function configures the hardware resources used in this example.
Parameters
hadc ADC handle pointer
Return values
None
ADC1 GPIO Configuration PC1 ---—> ADC1_INP11 PC5 ---—> ADC1_INP8
ADC2 GPIO Configuration PB0 ---—> ADC2_INP9
ADC3 GPIO Configuration PC1 ---—> ADC3_INP11
Definition at line 96 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(hadc->Instance==ADC1)
  {
    /* USER CODE BEGIN ADC1_MspInit 0 */
    /* USER CODE END ADC1_MspInit 0 */
    /* Peripheral clock enable */
    HAL_RCC_ADC12_CLK_ENABLED++;
    if(HAL_RCC_ADC12_CLK_ENABLED==1){
      __HAL_RCC_ADC12_CLK_ENABLE();
    }
    __HAL_RCC_GPIOC_CLK_ENABLE();
    GPIO_InitStruct.Pin = ADC3_BATTERY_Pin|ADC1_Pyrocheck1_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
    /* USER CODE BEGIN ADC1_MspInit 1 */
    /* USER CODE END ADC1_MspInit 1 */
  }
  else if(hadc->Instance==ADC2)
  {
    /* USER CODE BEGIN ADC2_MspInit 0 */
    /* USER CODE END ADC2_MspInit 0 */
    /* Peripheral clock enable */
    HAL_RCC_ADC12_CLK_ENABLED++;
    if(HAL_RCC_ADC12_CLK_ENABLED==1){
      __HAL_RCC_ADC12_CLK_ENABLE();
    }
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitStruct.Pin = ADC2_Pyrocheck2_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(ADC2_Pyrocheck2_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN ADC2_MspInit 1 */
    /* USER CODE END ADC2_MspInit 1 */
  }
  else if(hadc->Instance==ADC3)
  {
    /* USER CODE BEGIN ADC3_MspInit 0 */
    /* USER CODE END ADC3_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_ADC3_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    GPIO_InitStruct.Pin = ADC3_BATTERY_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(ADC3_BATTERY_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN ADC3_MspInit 1 */
    /* USER CODE END ADC3_MspInit 1 */
  }
}
References HAL_RCC_ADC12_CLK_ENABLED.
HAL_FDCAN_MspDeInit()
void HAL_FDCAN_MspDeInit (FDCAN_HandleTypeDef * hfdcan)
FDCAN MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hfdcan FDCAN handle pointer
Return values
None
FDCAN1 GPIO Configuration PB8 ---—> FDCAN1_RX PB9 ---—> FDCAN1_TX
Definition at line 295 of file stm32h7xx_hal_msp.c.
{
  if(hfdcan->Instance==FDCAN1)
  {
    /* USER CODE BEGIN FDCAN1_MspDeInit 0 */
    /* USER CODE END FDCAN1_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_FDCAN_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOB, GPIO_PIN_8|GPIO_PIN_9);
    /* USER CODE BEGIN FDCAN1_MspDeInit 1 */
    /* USER CODE END FDCAN1_MspDeInit 1 */
  }
}
HAL_FDCAN_MspInit()
void HAL_FDCAN_MspInit (FDCAN_HandleTypeDef * hfdcan)
FDCAN MSP Initialization This function configures the hardware resources used in this example.
Parameters
hfdcan FDCAN handle pointer
Return values
None
Initializes the peripherals clock
FDCAN1 GPIO Configuration PB8 ---—> FDCAN1_RX PB9 ---—> FDCAN1_TX
Definition at line 247 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
  if(hfdcan->Instance==FDCAN1)
  {
    /* USER CODE BEGIN FDCAN1_MspInit 0 */
    /* USER CODE END FDCAN1_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_FDCAN;
    PeriphClkInitStruct.FdcanClockSelection = RCC_FDCANCLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_FDCAN_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_8|GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF9_FDCAN1;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    /* USER CODE BEGIN FDCAN1_MspInit 1 */
    /* USER CODE END FDCAN1_MspInit 1 */
  }
}
References Error_Handler(), and HAL_OK.
HAL_MspInit()
void HAL_MspInit (void)
Initializes the Global MSP.
Definition at line 70 of file stm32h7xx_hal_msp.c.
{
  /* USER CODE BEGIN MspInit 0 */
  /* USER CODE END MspInit 0 */
  __HAL_RCC_SYSCFG_CLK_ENABLE();
  /* System interrupt init*/
  /* PendSV_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(PendSV_IRQn, 15, 0);
  /* USER CODE BEGIN MspInit 1 */
  /* USER CODE END MspInit 1 */
}
HAL_PCD_MspDeInit()
void HAL_PCD_MspDeInit (PCD_HandleTypeDef * hpcd)
PCD MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hpcd PCD handle pointer
Return values
None
USB_OTG_FS GPIO Configuration PA11 ---—> USB_OTG_FS_DM PA12 ---—> USB_OTG_FS_DP
Definition at line 1114 of file stm32h7xx_hal_msp.c.
{
  if(hpcd->Instance==USB_OTG_FS)
  {
    /* USER CODE BEGIN USB_OTG_FS_MspDeInit 0 */
    /* USER CODE END USB_OTG_FS_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_USB_OTG_FS_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOA, GPIO_PIN_11|GPIO_PIN_12);
    /* USER CODE BEGIN USB_OTG_FS_MspDeInit 1 */
    /* USER CODE END USB_OTG_FS_MspDeInit 1 */
  }
}
HAL_PCD_MspInit()
void HAL_PCD_MspInit (PCD_HandleTypeDef * hpcd)
PCD MSP Initialization This function configures the hardware resources used in this example.
Parameters
hpcd PCD handle pointer
Return values
None
Initializes the peripherals clock
Enable USB Voltage detector
USB_OTG_FS GPIO Configuration PA11 ---—> USB_OTG_FS_DM PA12 ---—> USB_OTG_FS_DP
Definition at line 1063 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
  if(hpcd->Instance==USB_OTG_FS)
  {
    /* USER CODE BEGIN USB_OTG_FS_MspInit 0 */
    /* USER CODE END USB_OTG_FS_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_USB;
    PeriphClkInitStruct.UsbClockSelection = RCC_USBCLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    HAL_PWREx_EnableUSBVoltageDetector();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_11|GPIO_PIN_12;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF10_OTG1_FS;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    /* Peripheral clock enable */
    __HAL_RCC_USB_OTG_FS_CLK_ENABLE();
    /* USER CODE BEGIN USB_OTG_FS_MspInit 1 */
    /* USER CODE END USB_OTG_FS_MspInit 1 */
  }
}
References Error_Handler(), and HAL_OK.
HAL_QSPI_MspDeInit()
void HAL_QSPI_MspDeInit (QSPI_HandleTypeDef * hqspi)
QSPI MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hqspi QSPI handle pointer
Return values
None
QUADSPI GPIO Configuration PB2 ---—> QUADSPI_CLK PE7 ---—> QUADSPI_BK2_IO0 PE8 ---—> QUADSPI_BK2_IO1 PE9 ---—> QUADSPI_BK2_IO2 PE10 ---—> QUADSPI_BK2_IO3 PC11 ---—> QUADSPI_BK2_NCS
Definition at line 424 of file stm32h7xx_hal_msp.c.
{
  if(hqspi->Instance==QUADSPI)
  {
    /* USER CODE BEGIN QUADSPI_MspDeInit 0 */
    /* USER CODE END QUADSPI_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_QSPI_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOB, GPIO_PIN_2);
    HAL_GPIO_DeInit(GPIOE, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10);
    HAL_GPIO_DeInit(GPIOC, GPIO_PIN_11);
    /* QUADSPI MDMA DeInit */
    HAL_MDMA_DeInit(hqspi->hmdma);
    /* QUADSPI interrupt DeInit */
    HAL_NVIC_DisableIRQ(QUADSPI_IRQn);
    /* USER CODE BEGIN QUADSPI_MspDeInit 1 */
    /* USER CODE END QUADSPI_MspDeInit 1 */
  }
}
References hqspi.
HAL_QSPI_MspInit()
void HAL_QSPI_MspInit (QSPI_HandleTypeDef * hqspi)
QSPI MSP Initialization This function configures the hardware resources used in this example.
Parameters
hqspi QSPI handle pointer
Return values
None
Initializes the peripherals clock
QUADSPI GPIO Configuration PB2 ---—> QUADSPI_CLK PE7 ---—> QUADSPI_BK2_IO0 PE8 ---—> QUADSPI_BK2_IO1 PE9 ---—> QUADSPI_BK2_IO2 PE10 ---—> QUADSPI_BK2_IO3 PC11 ---—> QUADSPI_BK2_NCS
Definition at line 324 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
  if(hqspi->Instance==QUADSPI)
  {
    /* USER CODE BEGIN QUADSPI_MspInit 0 */
    /* USER CODE END QUADSPI_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_QSPI;
    PeriphClkInitStruct.QspiClockSelection = RCC_QSPICLKSOURCE_D1HCLK;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_QSPI_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOE_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_2;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF9_QUADSPI;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    GPIO_InitStruct.Pin = GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF10_QUADSPI;
    HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);
    GPIO_InitStruct.Pin = GPIO_PIN_11;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF9_QUADSPI;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
    /* QUADSPI MDMA Init */
    /* QUADSPI_FIFO_TH Init */
    hmdma_quadspi_fifo_th.Instance = MDMA_Channel0;
    hmdma_quadspi_fifo_th.Init.Request = MDMA_REQUEST_QUADSPI_FIFO_TH;
    hmdma_quadspi_fifo_th.Init.TransferTriggerMode = MDMA_BUFFER_TRANSFER;
    hmdma_quadspi_fifo_th.Init.Priority = MDMA_PRIORITY_HIGH;
    hmdma_quadspi_fifo_th.Init.Endianness = MDMA_LITTLE_ENDIANNESS_PRESERVE;
    hmdma_quadspi_fifo_th.Init.SourceInc = MDMA_SRC_INC_BYTE;
    hmdma_quadspi_fifo_th.Init.DestinationInc = MDMA_DEST_INC_DISABLE;
    hmdma_quadspi_fifo_th.Init.SourceDataSize = MDMA_SRC_DATASIZE_BYTE;
    hmdma_quadspi_fifo_th.Init.DestDataSize = MDMA_DEST_DATASIZE_BYTE;
    hmdma_quadspi_fifo_th.Init.DataAlignment = MDMA_DATAALIGN_PACKENABLE;
    hmdma_quadspi_fifo_th.Init.BufferTransferLength = 480;
    hmdma_quadspi_fifo_th.Init.SourceBurst = MDMA_SOURCE_BURST_SINGLE;
    hmdma_quadspi_fifo_th.Init.DestBurst = MDMA_DEST_BURST_SINGLE;
    hmdma_quadspi_fifo_th.Init.SourceBlockAddressOffset = 0;
    hmdma_quadspi_fifo_th.Init.DestBlockAddressOffset = 0;
    if (HAL_MDMA_Init(&hmdma_quadspi_fifo_th) != HAL_OK)
    {
      Error_Handler();
    }
    if (HAL_MDMA_ConfigPostRequestMask(&hmdma_quadspi_fifo_th, 0, 0) != HAL_OK)
    {
      Error_Handler();
    }
    __HAL_LINKDMA(hqspi,hmdma,hmdma_quadspi_fifo_th);
    /* QUADSPI interrupt Init */
    HAL_NVIC_SetPriority(QUADSPI_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(QUADSPI_IRQn);
    /* USER CODE BEGIN QUADSPI_MspInit 1 */
    /* USER CODE END QUADSPI_MspInit 1 */
  }
}
References Error_Handler(), HAL_OK, hmdma_quadspi_fifo_th, and hqspi.
HAL_SPI_MspDeInit()
void HAL_SPI_MspDeInit (SPI_HandleTypeDef * hspi)
SPI MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hspi SPI handle pointer
Return values
None
SPI1 GPIO Configuration PA5 ---—> SPI1_SCK PA6 ---—> SPI1_MISO PA7 ---—> SPI1_MOSI
SPI2 GPIO Configuration PB13 ---—> SPI2_SCK PB14 ---—> SPI2_MISO PB15 ---—> SPI2_MOSI
SPI3 GPIO Configuration PB3 (JTDO/TRACESWO) ---—> SPI3_SCK PB4 (NJTRST) ---—> SPI3_MISO PB5 ---—> SPI3_MOSI
Definition at line 591 of file stm32h7xx_hal_msp.c.
{
  if(hspi->Instance==SPI1)
  {
    /* USER CODE BEGIN SPI1_MspDeInit 0 */
    /* USER CODE END SPI1_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_SPI1_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOA, GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7);
    /* USER CODE BEGIN SPI1_MspDeInit 1 */
    /* USER CODE END SPI1_MspDeInit 1 */
  }
  else if(hspi->Instance==SPI2)
  {
    /* USER CODE BEGIN SPI2_MspDeInit 0 */
    /* USER CODE END SPI2_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_SPI2_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOB, GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15);
    /* USER CODE BEGIN SPI2_MspDeInit 1 */
    /* USER CODE END SPI2_MspDeInit 1 */
  }
  else if(hspi->Instance==SPI3)
  {
    /* USER CODE BEGIN SPI3_MspDeInit 0 */
    /* USER CODE END SPI3_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_SPI3_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOB, GPIO_PIN_3|GPIO_PIN_4|SPI3_MOSI_SENSEB_Pin);
    /* USER CODE BEGIN SPI3_MspDeInit 1 */
    /* USER CODE END SPI3_MspDeInit 1 */
  }
}
HAL_SPI_MspInit()
void HAL_SPI_MspInit (SPI_HandleTypeDef * hspi)
SPI MSP Initialization This function configures the hardware resources used in this example.
Parameters
hspi SPI handle pointer
Return values
None
Initializes the peripherals clock
SPI1 GPIO Configuration PA5 ---—> SPI1_SCK PA6 ---—> SPI1_MISO PA7 ---—> SPI1_MOSI
Initializes the peripherals clock
SPI2 GPIO Configuration PB13 ---—> SPI2_SCK PB14 ---—> SPI2_MISO PB15 ---—> SPI2_MOSI
Initializes the peripherals clock
SPI3 GPIO Configuration PB3 (JTDO/TRACESWO) ---—> SPI3_SCK PB4 (NJTRST) ---—> SPI3_MISO PB5 ---—> SPI3_MOSI
Definition at line 466 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
  if(hspi->Instance==SPI1)
  {
    /* USER CODE BEGIN SPI1_MspInit 0 */
    /* USER CODE END SPI1_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_SPI1;
    PeriphClkInitStruct.Spi123ClockSelection = RCC_SPI123CLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_SPI1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF5_SPI1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    /* USER CODE BEGIN SPI1_MspInit 1 */
    /* USER CODE END SPI1_MspInit 1 */
  }
  else if(hspi->Instance==SPI2)
  {
    /* USER CODE BEGIN SPI2_MspInit 0 */
    /* USER CODE END SPI2_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_SPI2;
    PeriphClkInitStruct.Spi123ClockSelection = RCC_SPI123CLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_SPI2_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF5_SPI2;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    /* USER CODE BEGIN SPI2_MspInit 1 */
    /* USER CODE END SPI2_MspInit 1 */
  }
  else if(hspi->Instance==SPI3)
  {
    /* USER CODE BEGIN SPI3_MspInit 0 */
    /* USER CODE END SPI3_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_SPI3;
    PeriphClkInitStruct.Spi123ClockSelection = RCC_SPI123CLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_SPI3_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_3|GPIO_PIN_4;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF6_SPI3;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    GPIO_InitStruct.Pin = SPI3_MOSI_SENSEB_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF7_SPI3;
    HAL_GPIO_Init(SPI3_MOSI_SENSEB_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN SPI3_MspInit 1 */
    /* USER CODE END SPI3_MspInit 1 */
  }
}
References Error_Handler(), and HAL_OK.
HAL_TIM_Base_MspDeInit()
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * htim_base)
TIM_Base MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
htim_base TIM_Base handle pointer
Return values
None
Definition at line 824 of file stm32h7xx_hal_msp.c.
{
  if(htim_base->Instance==TIM6)
  {
    /* USER CODE BEGIN TIM6_MspDeInit 0 */
    /* USER CODE END TIM6_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_TIM6_CLK_DISABLE();
    /* TIM6 interrupt DeInit */
    HAL_NVIC_DisableIRQ(TIM6_DAC_IRQn);
    /* USER CODE BEGIN TIM6_MspDeInit 1 */
    /* USER CODE END TIM6_MspDeInit 1 */
  }
  else if(htim_base->Instance==TIM7)
  {
    /* USER CODE BEGIN TIM7_MspDeInit 0 */
    /* USER CODE END TIM7_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_TIM7_CLK_DISABLE();
    /* TIM7 interrupt DeInit */
    HAL_NVIC_DisableIRQ(TIM7_IRQn);
    /* USER CODE BEGIN TIM7_MspDeInit 1 */
    /* USER CODE END TIM7_MspDeInit 1 */
  }
  else if(htim_base->Instance==TIM13)
  {
    /* USER CODE BEGIN TIM13_MspDeInit 0 */
    /* USER CODE END TIM13_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_TIM13_CLK_DISABLE();
    /* TIM13 interrupt DeInit */
    HAL_NVIC_DisableIRQ(TIM8_UP_TIM13_IRQn);
    /* USER CODE BEGIN TIM13_MspDeInit 1 */
    /* USER CODE END TIM13_MspDeInit 1 */
  }
}
HAL_TIM_Base_MspInit()
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * htim_base)
TIM_Base MSP Initialization This function configures the hardware resources used in this example.
Parameters
htim_base TIM_Base handle pointer
Return values
None
Definition at line 692 of file stm32h7xx_hal_msp.c.
{
  if(htim_base->Instance==TIM6)
  {
    /* USER CODE BEGIN TIM6_MspInit 0 */
    /* USER CODE END TIM6_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_TIM6_CLK_ENABLE();
    /* TIM6 interrupt Init */
    HAL_NVIC_SetPriority(TIM6_DAC_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(TIM6_DAC_IRQn);
    /* USER CODE BEGIN TIM6_MspInit 1 */
    /* USER CODE END TIM6_MspInit 1 */
  }
  else if(htim_base->Instance==TIM7)
  {
    /* USER CODE BEGIN TIM7_MspInit 0 */
    /* USER CODE END TIM7_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_TIM7_CLK_ENABLE();
    /* TIM7 interrupt Init */
    HAL_NVIC_SetPriority(TIM7_IRQn, 15, 0);
    HAL_NVIC_EnableIRQ(TIM7_IRQn);
    /* USER CODE BEGIN TIM7_MspInit 1 */
    /* USER CODE END TIM7_MspInit 1 */
  }
  else if(htim_base->Instance==TIM13)
  {
    /* USER CODE BEGIN TIM13_MspInit 0 */
    /* USER CODE END TIM13_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_TIM13_CLK_ENABLE();
    /* TIM13 interrupt Init */
    HAL_NVIC_SetPriority(TIM8_UP_TIM13_IRQn, 14, 0);
    HAL_NVIC_EnableIRQ(TIM8_UP_TIM13_IRQn);
    /* USER CODE BEGIN TIM13_MspInit 1 */
    /* USER CODE END TIM13_MspInit 1 */
  }
}
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM2 GPIO Configuration PA2 ---—> TIM2_CH3
TIM15 GPIO Configuration PE6 ---—> TIM15_CH2
Definition at line 739 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim->Instance==TIM2)
  {
    /* USER CODE BEGIN TIM2_MspPostInit 0 */
    /* USER CODE END TIM2_MspPostInit 0 */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = TIM2_CH3_PWM_AIRBRAKES_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM2;
    HAL_GPIO_Init(TIM2_CH3_PWM_AIRBRAKES_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN TIM2_MspPostInit 1 */
    /* USER CODE END TIM2_MspPostInit 1 */
  }
  else if(htim->Instance==TIM15)
  {
    /* USER CODE BEGIN TIM15_MspPostInit 0 */
    /* USER CODE END TIM15_MspPostInit 0 */
    __HAL_RCC_GPIOE_CLK_ENABLE();
    GPIO_InitStruct.Pin = TIM15_CH2_BUZZER_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF4_TIM15;
    HAL_GPIO_Init(TIM15_CH2_BUZZER_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN TIM15_MspPostInit 1 */
    /* USER CODE END TIM15_MspPostInit 1 */
  }
}
Referenced by MX_TIM15_Init(), and MX_TIM2_Init().
HAL_TIM_PWM_MspDeInit()
void HAL_TIM_PWM_MspDeInit (TIM_HandleTypeDef * htim_pwm)
TIM_PWM MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
htim_pwm TIM_PWM handle pointer
Return values
None
Definition at line 791 of file stm32h7xx_hal_msp.c.
{
  if(htim_pwm->Instance==TIM2)
  {
    /* USER CODE BEGIN TIM2_MspDeInit 0 */
    /* USER CODE END TIM2_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_TIM2_CLK_DISABLE();
    /* USER CODE BEGIN TIM2_MspDeInit 1 */
    /* USER CODE END TIM2_MspDeInit 1 */
  }
  else if(htim_pwm->Instance==TIM15)
  {
    /* USER CODE BEGIN TIM15_MspDeInit 0 */
    /* USER CODE END TIM15_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_TIM15_CLK_DISABLE();
    /* USER CODE BEGIN TIM15_MspDeInit 1 */
    /* USER CODE END TIM15_MspDeInit 1 */
  }
}
HAL_TIM_PWM_MspInit()
void HAL_TIM_PWM_MspInit (TIM_HandleTypeDef * htim_pwm)
TIM_PWM MSP Initialization This function configures the hardware resources used in this example.
Parameters
htim_pwm TIM_PWM handle pointer
Return values
None
Definition at line 659 of file stm32h7xx_hal_msp.c.
{
  if(htim_pwm->Instance==TIM2)
  {
    /* USER CODE BEGIN TIM2_MspInit 0 */
    /* USER CODE END TIM2_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_TIM2_CLK_ENABLE();
    /* USER CODE BEGIN TIM2_MspInit 1 */
    /* USER CODE END TIM2_MspInit 1 */
  }
  else if(htim_pwm->Instance==TIM15)
  {
    /* USER CODE BEGIN TIM15_MspInit 0 */
    /* USER CODE END TIM15_MspInit 0 */
    /* Peripheral clock enable */
    __HAL_RCC_TIM15_CLK_ENABLE();
    /* USER CODE BEGIN TIM15_MspInit 1 */
    /* USER CODE END TIM15_MspInit 1 */
  }
}
HAL_UART_MspDeInit()
void HAL_UART_MspDeInit (UART_HandleTypeDef * huart)
UART MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
huart UART handle pointer
Return values
None
UART4 GPIO Configuration PD0 ---—> UART4_RX PD1 ---—> UART4_TX
USART1 GPIO Configuration PA8 ---—> USART1_CK PA9 ---—> USART1_TX PA10 ---—> USART1_RX
Definition at line 1009 of file stm32h7xx_hal_msp.c.
{
  if(huart->Instance==UART4)
  {
    /* USER CODE BEGIN UART4_MspDeInit 0 */
    /* USER CODE END UART4_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_UART4_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOD, UART4_RX_DEBUG_Pin|UART4_TX_DEBUG_Pin);
    /* USER CODE BEGIN UART4_MspDeInit 1 */
    /* USER CODE END UART4_MspDeInit 1 */
  }
  else if(huart->Instance==USART1)
  {
    /* USER CODE BEGIN USART1_MspDeInit 0 */
    /* USER CODE END USART1_MspDeInit 0 */
    /* Peripheral clock disable */
    __HAL_RCC_USART1_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOA, GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10);
    /* USART1 DMA DeInit */
    HAL_DMA_DeInit(huart->hdmarx);
    HAL_DMA_DeInit(huart->hdmatx);
    /* USART1 interrupt DeInit */
    HAL_NVIC_DisableIRQ(USART1_IRQn);
    /* USER CODE BEGIN USART1_MspDeInit 1 */
    /* USER CODE END USART1_MspDeInit 1 */
  }
}
HAL_UART_MspInit()
void HAL_UART_MspInit (UART_HandleTypeDef * huart)
UART MSP Initialization This function configures the hardware resources used in this example.
Parameters
huart UART handle pointer
Return values
None
Initializes the peripherals clock
UART4 GPIO Configuration PD0 ---—> UART4_RX PD1 ---—> UART4_TX
Initializes the peripherals clock
USART1 GPIO Configuration PA8 ---—> USART1_CK PA9 ---—> USART1_TX PA10 ---—> USART1_RX
Definition at line 877 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
  if(huart->Instance==UART4)
  {
    /* USER CODE BEGIN UART4_MspInit 0 */
    /* USER CODE END UART4_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_UART4;
    PeriphClkInitStruct.Usart234578ClockSelection = RCC_USART234578CLKSOURCE_D2PCLK1;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_UART4_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    GPIO_InitStruct.Pin = UART4_RX_DEBUG_Pin|UART4_TX_DEBUG_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF8_UART4;
    HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);
    /* USER CODE BEGIN UART4_MspInit 1 */
    /* USER CODE END UART4_MspInit 1 */
  }
  else if(huart->Instance==USART1)
  {
    /* USER CODE BEGIN USART1_MspInit 0 */
    /* USER CODE END USART1_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_USART1;
    PeriphClkInitStruct.Usart16ClockSelection = RCC_USART16CLKSOURCE_D2PCLK2;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* Peripheral clock enable */
    __HAL_RCC_USART1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF7_USART1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    GPIO_InitStruct.Pin = GPIO_PIN_9|GPIO_PIN_10;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF7_USART1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    /* USART1 DMA Init */
    /* USART1_RX Init */
    hdma_usart1_rx.Instance = DMA1_Stream0;
    hdma_usart1_rx.Init.Request = DMA_REQUEST_USART1_RX;
    hdma_usart1_rx.Init.Direction = DMA_PERIPH_TO_MEMORY;
    hdma_usart1_rx.Init.PeriphInc = DMA_PINC_DISABLE;
    hdma_usart1_rx.Init.MemInc = DMA_MINC_ENABLE;
    hdma_usart1_rx.Init.PeriphDataAlignment = DMA_PDATAALIGN_BYTE;
    hdma_usart1_rx.Init.MemDataAlignment = DMA_MDATAALIGN_BYTE;
    hdma_usart1_rx.Init.Mode = DMA_NORMAL;
    hdma_usart1_rx.Init.Priority = DMA_PRIORITY_HIGH;
    hdma_usart1_rx.Init.FIFOMode = DMA_FIFOMODE_ENABLE;
    hdma_usart1_rx.Init.FIFOThreshold = DMA_FIFO_THRESHOLD_FULL;
    hdma_usart1_rx.Init.MemBurst = DMA_MBURST_SINGLE;
    hdma_usart1_rx.Init.PeriphBurst = DMA_PBURST_SINGLE;
    if (HAL_DMA_Init(&hdma_usart1_rx) != HAL_OK)
    {
      Error_Handler();
    }
    __HAL_LINKDMA(huart,hdmarx,hdma_usart1_rx);
    /* USART1_TX Init */
    hdma_usart1_tx.Instance = DMA1_Stream1;
    hdma_usart1_tx.Init.Request = DMA_REQUEST_USART1_TX;
    hdma_usart1_tx.Init.Direction = DMA_MEMORY_TO_PERIPH;
    hdma_usart1_tx.Init.PeriphInc = DMA_PINC_DISABLE;
    hdma_usart1_tx.Init.MemInc = DMA_MINC_ENABLE;
    hdma_usart1_tx.Init.PeriphDataAlignment = DMA_PDATAALIGN_BYTE;
    hdma_usart1_tx.Init.MemDataAlignment = DMA_MDATAALIGN_BYTE;
    hdma_usart1_tx.Init.Mode = DMA_NORMAL;
    hdma_usart1_tx.Init.Priority = DMA_PRIORITY_HIGH;
    hdma_usart1_tx.Init.FIFOMode = DMA_FIFOMODE_DISABLE;
    if (HAL_DMA_Init(&hdma_usart1_tx) != HAL_OK)
    {
      Error_Handler();
    }
    __HAL_LINKDMA(huart,hdmatx,hdma_usart1_tx);
    /* USART1 interrupt Init */
    HAL_NVIC_SetPriority(USART1_IRQn, 10, 0);
    HAL_NVIC_EnableIRQ(USART1_IRQn);
    /* USER CODE BEGIN USART1_MspInit 1 */
    /* USER CODE END USART1_MspInit 1 */
  }
}
References Error_Handler(), HAL_OK, hdma_usart1_rx, and hdma_usart1_tx.
Variable Documentation
HAL_RCC_ADC12_CLK_ENABLED
uint32_t HAL_RCC_ADC12_CLK_ENABLED =0 static
Definition at line 88 of file stm32h7xx_hal_msp.c.
Referenced by HAL_ADC_MspDeInit(), and HAL_ADC_MspInit().
hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_rx extern
Definition at line 73 of file main.c.
Referenced by HAL_UART_MspInit().
hdma_usart1_tx
DMA_HandleTypeDef hdma_usart1_tx extern
Definition at line 74 of file main.c.
Referenced by HAL_UART_MspInit().
hmdma_quadspi_fifo_th
MDMA_HandleTypeDef hmdma_quadspi_fifo_th extern
Definition at line 59 of file main.c.
Referenced by HAL_QSPI_MspInit().