Da Vinci Firmware: Davinci_2/Core/Inc/cdEvaluation.h File Reference
cdEvaluation.h File Reference
Core Flight Logic » Control Algorithms
Performs 2D bilinear interpolation to estimate the coefficient of drag (Cd).
#include "rtwtypes.h"
#include <stddef.h>
#include <stdlib.h>
Functions
double cdEvaluation (const double dep_states[6], const double mach_states[5], const double cd_table[30], double dep, double mach)
Estimates the coefficient of drag (Cd) via 2D bilinear interpolation.
Detailed Description
Performs 2D bilinear interpolation to estimate the coefficient of drag (Cd).
Author
Francesco Abate, MSA (Originally generated by MATLAB Coder)
Version
24.2 (MATLAB Coder version)
Date
2025-05-06
This header declares the cdEvaluation function, which calculates the rocket's coefficient of drag (Cd) based on its current Mach number and airbrake deployment angle.
The function implements a 2D bilinear interpolation algorithm using a pre-defined lookup table of Cd values. It finds the four nearest points in the table surrounding the current state and interpolates between them to produce a smooth Cd estimate.
This functionality is a core component of the MPC controller, called by the optimalAngle function to predict the rocket's aerodynamic behavior. The implementation was provided by the MSA subteam.
Definition in file cdEvaluation.h.
Function Documentation
cdEvaluation()
double cdEvaluation (const double dep_states[6], const double mach_states[5], const double cd_table[30], double dep, double mach)
Estimates the coefficient of drag (Cd) via 2D bilinear interpolation.
Parameters
[in] dep_states An array of 6 discrete airbrake deployment angles (the "y-axis" of the lookup table).
[in] mach_states An array of 5 discrete Mach numbers (the "x-axis" of the lookup table).
[in] cd_table A 1D array of 30 Cd values, representing the 6x5 lookup grid. The data must be ordered row-major (all Mach values for the first dep_state, etc.).
[in] dep The current, continuous airbrake deployment angle to interpolate at.
[in] mach The current, continuous speed expressed as a Mach number to interpolate at.
Returns
The interpolated coefficient of drag (Cd), a dimensionless value.
Definition at line 30 of file cdEvaluation.c.
{
  double b_b_tmp_data;
  double b_tmp_data;
  double c_b_tmp_data;
  double cd;
  double cd_table_data;
  double d_b_tmp_data;
  double tmp_data;
  double x1_data;
  double x2_data;
  double y1_data;
  double y2_data;
  double y2_idx_data;
  int cd_table_size[2];
  int tmp_size[2];
  int i;
  int i1;
  int loop_ub;
  int x1_idx_data;
  int y1_idx_data;
  int y1_size;
  int y2_size;
  bool b_dep_states[6];
  bool b_mach_states[5];
  for (i = 0; i < 6; i++) {
    b_dep_states[i] = (dep_states[i] <= dep);
  }
  i1 = eml_find(b_dep_states, (int *)&y1_idx_data);
  loop_ub = i1;
  for (i = 0; i < i1; i++) {
    x1_idx_data = y1_idx_data;
  }
  for (i = 0; i < i1; i++) {
    cd = (double)x1_idx_data + 1.0;
  }
  /*  Find indices of the surrounding y-coordinates */
  for (i = 0; i < 5; i++) {
    b_mach_states[i] = (mach_states[i] <= mach);
  }
  i1 = b_eml_find(b_mach_states, (int *)&y1_idx_data);
  for (i = 0; i < i1; i++) {
    y2_idx_data = (double)y1_idx_data + 1.0;
  }
  /*  Extract the surrounding x and y coordinates */
  for (i = 0; i < loop_ub; i++) {
    x1_data = dep_states[x1_idx_data - 1];
    x2_data = dep_states[(int)cd - 1];
  }
  for (i = 0; i < i1; i++) {
    y1_data = mach_states[y1_idx_data - 1];
    y2_data = mach_states[(int)y2_idx_data - 1];
  }
  /*  Extract the corresponding z-values */
  /*  Perform bilinear interpolation */
  for (i = 0; i < loop_ub; i++) {
    b_tmp_data = x2_data - dep;
  }
  for (i = 0; i < i1; i++) {
    b_b_tmp_data = y2_data - mach;
  }
  for (i = 0; i < loop_ub; i++) {
    c_b_tmp_data = dep - x1_data;
  }
  for (i = 0; i < i1; i++) {
    d_b_tmp_data = mach - y1_data;
    y2_data -= y1_data;
  }
  cd_table_size[0] = i1;
  cd_table_size[1] = loop_ub;
  if (loop_ub - 1 >= 0) {
    for (i = 0; i < i1; i++) {
      cd_table_data = cd_table[(y1_idx_data + 5 * (x1_idx_data - 1)) - 1];
    }
  }
  for (i = 0; i < loop_ub; i++) {
    x2_data = (x2_data - x1_data) * y2_data;
  }
  mrdiv_2((double *)&x2_data, loop_ub, (double *)&tmp_data, tmp_size);
  y2_size = mtimes((double *)&cd_table_data, cd_table_size,
                   (double *)&b_tmp_data, (double *)&y2_data);
  if (loop_ub - 1 >= 0) {
    for (i = 0; i < i1; i++) {
      cd_table_data = cd_table[(y1_idx_data + 5 * ((int)cd - 1)) - 1];
    }
  }
  y1_size = mtimes((double *)&cd_table_data, cd_table_size,
                   (double *)&c_b_tmp_data, (double *)&y1_data);
  if (loop_ub - 1 >= 0) {
    for (i = 0; i < i1; i++) {
      cd_table_data = cd_table[((int)y2_idx_data + 5 * (x1_idx_data - 1)) - 1];
    }
  }
  x1_idx_data = mtimes((double *)&cd_table_data, cd_table_size,
                       (double *)&b_tmp_data, (double *)&x2_data);
  if (loop_ub - 1 >= 0) {
    for (i = 0; i < i1; i++) {
      cd_table_data = cd_table[((int)y2_idx_data + 5 * ((int)cd - 1)) - 1];
    }
  }
  y1_idx_data = mtimes((double *)&cd_table_data, cd_table_size,
                       (double *)&c_b_tmp_data, (double *)&x1_data);
  if (y2_size == 1) {
    i = y1_size;
  } else {
    i = y2_size;
  }
  if (i == 1) {
    i1 = x1_idx_data;
  } else {
    i1 = i;
  }
  if ((y2_size == y1_size) && (i == x1_idx_data) && (i1 == y1_idx_data)) {
    cd = 0.0;
    loop_ub = tmp_size[1];
    for (i = 0; i < loop_ub; i++) {
      cd += tmp_data * (((y2_data * b_b_tmp_data + y1_data * b_b_tmp_data) +
                         x2_data * d_b_tmp_data) +
                        x1_data * d_b_tmp_data);
    }
  } else {
    cd = binary_expand_op((double *)&tmp_data, tmp_size, (double *)&y2_data,
                          &y2_size, (double *)&b_b_tmp_data, (double *)&y1_data,
                          &y1_size, (double *)&x2_data, &x1_idx_data,
                          (double *)&d_b_tmp_data, (double *)&x1_data,
                          &y1_idx_data);
  }
  return cd;
}
References b_eml_find(), binary_expand_op(), cd_table, eml_find(), mach_states, mrdiv_2(), and mtimes().
Referenced by optimalAngle().