Da Vinci Firmware: "Data Generation"
"Data Generation"
Peripheral Drivers » "LIS2MDL Magnetometer Driver"
This section group all the functions concerning data generation.
Functions
int32_t lis2mdl_mag_user_offset_set (const stmdev_ctx_t *ctx, int16_t *val)
These registers comprise a 3 group of 16-bit number and represent hard-iron offset in order to compensate environmental effects. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG. These values act on the magnetic output data value in order to delete the environmental offset.[set].
int32_t lis2mdl_mag_user_offset_get (const stmdev_ctx_t *ctx, int16_t *val)
These registers comprise a 3 group of 16-bit number and represent hard-iron offset in order to compensate environmental effects. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG. These values act on the magnetic output data value in order to delete the environmental offset.[get].
int32_t lis2mdl_operating_mode_set (const stmdev_ctx_t *ctx, lis2mdl_md_t val)
Operating mode selection.[set].
int32_t lis2mdl_operating_mode_get (const stmdev_ctx_t *ctx, lis2mdl_md_t *val)
Operating mode selection.[get].
int32_t lis2mdl_data_rate_set (const stmdev_ctx_t *ctx, lis2mdl_odr_t val)
Output data rate selection.[set].
int32_t lis2mdl_data_rate_get (const stmdev_ctx_t *ctx, lis2mdl_odr_t *val)
Output data rate selection.[get].
int32_t lis2mdl_power_mode_set (const stmdev_ctx_t *ctx, lis2mdl_lp_t val)
Enables high-resolution/low-power mode.[set].
int32_t lis2mdl_power_mode_get (const stmdev_ctx_t *ctx, lis2mdl_lp_t *val)
Enables high-resolution/low-power mode.[get].
int32_t lis2mdl_offset_temp_comp_set (const stmdev_ctx_t *ctx, uint8_t val)
Enables the magnetometer temperature compensation.[set].
int32_t lis2mdl_offset_temp_comp_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enables the magnetometer temperature compensation.[get].
int32_t lis2mdl_low_pass_bandwidth_set (const stmdev_ctx_t *ctx, lis2mdl_lpf_t val)
Low-pass bandwidth selection.[set].
int32_t lis2mdl_low_pass_bandwidth_get (const stmdev_ctx_t *ctx, lis2mdl_lpf_t *val)
Low-pass bandwidth selection.[get].
int32_t lis2mdl_set_rst_mode_set (const stmdev_ctx_t *ctx, lis2mdl_set_rst_t val)
Reset mode.[set].
int32_t lis2mdl_set_rst_mode_get (const stmdev_ctx_t *ctx, lis2mdl_set_rst_t *val)
Reset mode.[get].
int32_t lis2mdl_set_rst_sensor_single_set (const stmdev_ctx_t *ctx, uint8_t val)
Enables offset cancellation in single measurement mode. The OFF_CANC bit must be set to 1 when enabling offset cancellation in single measurement mode this means a call function: set_rst_mode(SENS_OFF_CANC_EVERY_ODR) is need.[set].
int32_t lis2mdl_set_rst_sensor_single_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enables offset cancellation in single measurement mode. The OFF_CANC bit must be set to 1 when enabling offset cancellation in single measurement mode this means a call function: set_rst_mode(SENS_OFF_CANC_EVERY_ODR) is need.[get].
int32_t lis2mdl_block_data_update_set (const stmdev_ctx_t *ctx, uint8_t val)
Blockdataupdate.[set].
int32_t lis2mdl_block_data_update_get (const stmdev_ctx_t *ctx, uint8_t *val)
Blockdataupdate.[get].
int32_t lis2mdl_mag_data_ready_get (const stmdev_ctx_t *ctx, uint8_t *val)
Magnetic set of data available.[get].
int32_t lis2mdl_mag_data_ovr_get (const stmdev_ctx_t *ctx, uint8_t *val)
Magnetic set of data overrun.[get].
int32_t lis2mdl_magnetic_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Magnetic output value.[get].
int32_t lis2mdl_temperature_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Temperature output value.[get].
Detailed Description
This section group all the functions concerning data generation.
Function Documentation
lis2mdl_block_data_update_get()
int32_t lis2mdl_block_data_update_get (const stmdev_ctx_t * ctx, uint8_t * val)
Blockdataupdate.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of bdu in reg CFG_REG_C.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 646 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  *val = reg.bdu;
  return ret;
}
References lis2mdl_cfg_reg_c_t::bdu, LIS2MDL_CFG_REG_C, and lis2mdl_read_reg().
lis2mdl_block_data_update_set()
int32_t lis2mdl_block_data_update_set (const stmdev_ctx_t * ctx, uint8_t val)
Blockdataupdate.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of bdu in reg CFG_REG_C
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 622 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.bdu = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::bdu, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_write_reg().
lis2mdl_data_rate_get()
int32_t lis2mdl_data_rate_get (const stmdev_ctx_t * ctx, lis2mdl_odr_t * val)
Output data rate selection.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of odr in reg CFG_REG_A.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 306 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  switch (reg.odr)
  {
    case LIS2MDL_ODR_10Hz:
      *val = LIS2MDL_ODR_10Hz;
      break;
    case LIS2MDL_ODR_20Hz:
      *val = LIS2MDL_ODR_20Hz;
      break;
    case LIS2MDL_ODR_50Hz:
      *val = LIS2MDL_ODR_50Hz;
      break;
    case LIS2MDL_ODR_100Hz:
      *val = LIS2MDL_ODR_100Hz;
      break;
    default:
      *val = LIS2MDL_ODR_10Hz;
      break;
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, LIS2MDL_ODR_100Hz, LIS2MDL_ODR_10Hz, LIS2MDL_ODR_20Hz, LIS2MDL_ODR_50Hz, lis2mdl_read_reg(), and lis2mdl_cfg_reg_a_t::odr.
lis2mdl_data_rate_set()
int32_t lis2mdl_data_rate_set (const stmdev_ctx_t * ctx, lis2mdl_odr_t val)
Output data rate selection.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of odr in reg CFG_REG_A
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 282 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.odr = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_a_t::odr.
lis2mdl_low_pass_bandwidth_get()
int32_t lis2mdl_low_pass_bandwidth_get (const stmdev_ctx_t * ctx, lis2mdl_lpf_t * val)
Low-pass bandwidth selection.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of lpf in reg CFG_REG_B.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 472 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  switch (reg.lpf)
  {
    case LIS2MDL_ODR_DIV_2:
      *val = LIS2MDL_ODR_DIV_2;
      break;
    case LIS2MDL_ODR_DIV_4:
      *val = LIS2MDL_ODR_DIV_4;
      break;
    default:
      *val = LIS2MDL_ODR_DIV_2;
      break;
  }
  return ret;
}
References LIS2MDL_CFG_REG_B, LIS2MDL_ODR_DIV_2, LIS2MDL_ODR_DIV_4, lis2mdl_read_reg(), and lis2mdl_cfg_reg_b_t::lpf.
lis2mdl_low_pass_bandwidth_set()
int32_t lis2mdl_low_pass_bandwidth_set (const stmdev_ctx_t * ctx, lis2mdl_lpf_t val)
Low-pass bandwidth selection.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of lpf in reg CFG_REG_B
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 447 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.lpf = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_B, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_b_t::lpf.
lis2mdl_mag_data_ovr_get()
int32_t lis2mdl_mag_data_ovr_get (const stmdev_ctx_t * ctx, uint8_t * val)
Magnetic set of data overrun.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of zyxor in reg STATUS_REG.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 684 of file lis2mdl_reg.c.
{
  lis2mdl_status_reg_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_STATUS_REG, (uint8_t *)&reg, 1);
  *val = reg.zyxor;
  return ret;
}
References lis2mdl_read_reg(), LIS2MDL_STATUS_REG, and lis2mdl_status_reg_t::zyxor.
lis2mdl_mag_data_ready_get()
int32_t lis2mdl_mag_data_ready_get (const stmdev_ctx_t * ctx, uint8_t * val)
Magnetic set of data available.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of zyxda in reg STATUS_REG.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 665 of file lis2mdl_reg.c.
{
  lis2mdl_status_reg_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_STATUS_REG, (uint8_t *)&reg, 1);
  *val = reg.zyxda;
  return ret;
}
References lis2mdl_read_reg(), LIS2MDL_STATUS_REG, and lis2mdl_status_reg_t::zyxda.
lis2mdl_mag_user_offset_get()
int32_t lis2mdl_mag_user_offset_get (const stmdev_ctx_t * ctx, int16_t * val)
These registers comprise a 3 group of 16-bit number and represent hard-iron offset in order to compensate environmental effects. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG. These values act on the magnetic output data value in order to delete the environmental offset.[get].
Parameters
ctx read / write interface definitions.(ptr)
buff that stores data read
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 195 of file lis2mdl_reg.c.
{
  uint8_t buff[6];
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_OFFSET_X_REG_L, buff, 6);
  val[0] = (int16_t)buff[1];
  val[0] = (val[0] * 256) + (int16_t)buff[0];
  val[1] = (int16_t)buff[3];
  val[1] = (val[1] * 256) + (int16_t)buff[2];
  val[2] = (int16_t)buff[5];
  val[2] = (val[2] * 256) + (int16_t)buff[4];
  return ret;
}
References LIS2MDL_OFFSET_X_REG_L, and lis2mdl_read_reg().
lis2mdl_mag_user_offset_set()
int32_t lis2mdl_mag_user_offset_set (const stmdev_ctx_t * ctx, int16_t * val)
These registers comprise a 3 group of 16-bit number and represent hard-iron offset in order to compensate environmental effects. Data format is the same of output data raw: two’s complement with 1LSb = 1.5mG. These values act on the magnetic output data value in order to delete the environmental offset.[set].
Parameters
ctx read / write interface definitions.(ptr)
buff buffer that contains data to write
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 167 of file lis2mdl_reg.c.
{
  uint8_t buff[6];
  int32_t ret;
  buff[1] = (uint8_t)((uint16_t)val[0] / 256U);
  buff[0] = (uint8_t)((uint16_t)val[0] - (buff[1] * 256U));
  buff[3] = (uint8_t)((uint16_t)val[1] / 256U);
  buff[2] = (uint8_t)((uint16_t)val[1] - (buff[3] * 256U));
  buff[5] = (uint8_t)((uint16_t)val[2] / 256U);
  buff[4] = (uint8_t)((uint16_t)val[2] - (buff[5] * 256U));
  ret = lis2mdl_write_reg(ctx, LIS2MDL_OFFSET_X_REG_L, buff, 6);
  return ret;
}
References LIS2MDL_OFFSET_X_REG_L, and lis2mdl_write_reg().
lis2mdl_magnetic_raw_get()
int32_t lis2mdl_magnetic_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Magnetic output value.[get].
Parameters
ctx read / write interface definitions.(ptr)
buff that stores data read
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 703 of file lis2mdl_reg.c.
{
  uint8_t buff[6];
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_OUTX_L_REG, buff, 6);
  val[0] = (int16_t)buff[1];
  val[0] = (val[0] * 256) + (int16_t)buff[0];
  val[1] = (int16_t)buff[3];
  val[1] = (val[1] * 256) + (int16_t)buff[2];
  val[2] = (int16_t)buff[5];
  val[2] = (val[2] * 256) + (int16_t)buff[4];
  return ret;
}
References LIS2MDL_OUTX_L_REG, and lis2mdl_read_reg().
lis2mdl_offset_temp_comp_get()
int32_t lis2mdl_offset_temp_comp_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enables the magnetometer temperature compensation.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of comp_temp_en in reg CFG_REG_A.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 428 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  *val = reg.comp_temp_en;
  return ret;
}
References lis2mdl_cfg_reg_a_t::comp_temp_en, LIS2MDL_CFG_REG_A, and lis2mdl_read_reg().
lis2mdl_offset_temp_comp_set()
int32_t lis2mdl_offset_temp_comp_set (const stmdev_ctx_t * ctx, uint8_t val)
Enables the magnetometer temperature compensation.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of comp_temp_en in reg CFG_REG_A
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 404 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.comp_temp_en = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_a_t::comp_temp_en, LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), and lis2mdl_write_reg().
lis2mdl_operating_mode_get()
int32_t lis2mdl_operating_mode_get (const stmdev_ctx_t * ctx, lis2mdl_md_t * val)
Operating mode selection.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of md in reg CFG_REG_A.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 244 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  switch (reg.md)
  {
    case LIS2MDL_POWER_DOWN:
      *val = LIS2MDL_POWER_DOWN;
      break;
    case LIS2MDL_CONTINUOUS_MODE:
      *val = LIS2MDL_CONTINUOUS_MODE;
      break;
    case LIS2MDL_SINGLE_TRIGGER:
      *val = LIS2MDL_SINGLE_TRIGGER;
      break;
    default:
      *val = LIS2MDL_POWER_DOWN;
      break;
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, LIS2MDL_CONTINUOUS_MODE, LIS2MDL_POWER_DOWN, lis2mdl_read_reg(), LIS2MDL_SINGLE_TRIGGER, and lis2mdl_cfg_reg_a_t::md.
lis2mdl_operating_mode_set()
int32_t lis2mdl_operating_mode_set (const stmdev_ctx_t * ctx, lis2mdl_md_t val)
Operating mode selection.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of md in reg CFG_REG_A
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 219 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.md = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_a_t::md.
lis2mdl_power_mode_get()
int32_t lis2mdl_power_mode_get (const stmdev_ctx_t * ctx, lis2mdl_lp_t * val)
Enables high-resolution/low-power mode.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of lp in reg CFG_REG_A.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 371 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  switch (reg.lp)
  {
    case LIS2MDL_HIGH_RESOLUTION:
      *val = LIS2MDL_HIGH_RESOLUTION;
      break;
    case LIS2MDL_LOW_POWER:
      *val = LIS2MDL_LOW_POWER;
      break;
    default:
      *val = LIS2MDL_HIGH_RESOLUTION;
      break;
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, LIS2MDL_HIGH_RESOLUTION, LIS2MDL_LOW_POWER, lis2mdl_read_reg(), and lis2mdl_cfg_reg_a_t::lp.
lis2mdl_power_mode_set()
int32_t lis2mdl_power_mode_set (const stmdev_ctx_t * ctx, lis2mdl_lp_t val)
Enables high-resolution/low-power mode.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of lp in reg CFG_REG_A
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 347 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_a_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.lp = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_A, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_a_t::lp.
lis2mdl_set_rst_mode_get()
int32_t lis2mdl_set_rst_mode_get (const stmdev_ctx_t * ctx, lis2mdl_set_rst_t * val)
Reset mode.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of set_rst in reg CFG_REG_B.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 531 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  switch (reg.set_rst)
  {
    case LIS2MDL_SET_SENS_ODR_DIV_63:
      *val = LIS2MDL_SET_SENS_ODR_DIV_63;
      break;
    case LIS2MDL_SENS_OFF_CANC_EVERY_ODR:
      *val = LIS2MDL_SENS_OFF_CANC_EVERY_ODR;
      break;
    case LIS2MDL_SET_SENS_ONLY_AT_POWER_ON:
      *val = LIS2MDL_SET_SENS_ONLY_AT_POWER_ON;
      break;
    default:
      *val = LIS2MDL_SET_SENS_ODR_DIV_63;
      break;
  }
  return ret;
}
References LIS2MDL_CFG_REG_B, lis2mdl_read_reg(), LIS2MDL_SENS_OFF_CANC_EVERY_ODR, LIS2MDL_SET_SENS_ODR_DIV_63, LIS2MDL_SET_SENS_ONLY_AT_POWER_ON, and lis2mdl_cfg_reg_b_t::set_rst.
lis2mdl_set_rst_mode_set()
int32_t lis2mdl_set_rst_mode_set (const stmdev_ctx_t * ctx, lis2mdl_set_rst_t val)
Reset mode.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of set_rst in reg CFG_REG_B
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 506 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.set_rst = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_B, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_b_t::set_rst.
lis2mdl_set_rst_sensor_single_get()
int32_t lis2mdl_set_rst_sensor_single_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enables offset cancellation in single measurement mode. The OFF_CANC bit must be set to 1 when enabling offset cancellation in single measurement mode this means a call function: set_rst_mode(SENS_OFF_CANC_EVERY_ODR) is need.[get].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of off_canc_one_shot in reg CFG_REG_B.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 602 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  *val = reg.off_canc_one_shot;
  return ret;
}
References LIS2MDL_CFG_REG_B, lis2mdl_read_reg(), and lis2mdl_cfg_reg_b_t::off_canc_one_shot.
lis2mdl_set_rst_sensor_single_set()
int32_t lis2mdl_set_rst_sensor_single_set (const stmdev_ctx_t * ctx, uint8_t val)
Enables offset cancellation in single measurement mode. The OFF_CANC bit must be set to 1 when enabling offset cancellation in single measurement mode this means a call function: set_rst_mode(SENS_OFF_CANC_EVERY_ODR) is need.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of off_canc_one_shot in reg CFG_REG_B
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 573 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_b_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.off_canc_one_shot = val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_B, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LIS2MDL_CFG_REG_B, lis2mdl_read_reg(), lis2mdl_write_reg(), and lis2mdl_cfg_reg_b_t::off_canc_one_shot.
lis2mdl_temperature_raw_get()
int32_t lis2mdl_temperature_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Temperature output value.[get].
Parameters
ctx read / write interface definitions.(ptr)
buff that stores data read
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 727 of file lis2mdl_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_TEMP_OUT_L_REG, buff, 2);
  *val = (int16_t)buff[1];
  *val = (*val * 256) + (int16_t)buff[0];
  return ret;
}
References lis2mdl_read_reg(), and LIS2MDL_TEMP_OUT_L_REG.