Da Vinci Firmware: LSM6DSO32_Timestamp
LSM6DSO32_Timestamp
Peripheral Drivers » "LSM6DSO32 6-Axis IMU Driver"
This section groups all the functions that manage the timestamp generation.
Functions
int32_t lsm6dso32_timestamp_set (stmdev_ctx_t *ctx, uint8_t val)
Enables timestamp counter.[set].
int32_t lsm6dso32_timestamp_get (stmdev_ctx_t *ctx, uint8_t *val)
Enables timestamp counter.[get].
int32_t lsm6dso32_timestamp_raw_get (stmdev_ctx_t *ctx, uint32_t *val)
Timestamp first data output register (r). The value is expressed as a 32-bit word and the bit resolution is 25 μs.[get].
Detailed Description
This section groups all the functions that manage the timestamp generation.
Function Documentation
lsm6dso32_timestamp_get()
int32_t lsm6dso32_timestamp_get (stmdev_ctx_t * ctx, uint8_t * val)
Enables timestamp counter.[get].
Parameters
ctx read / write interface definitions
val change the values of timestamp_en in reg CTRL10_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1127 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl10_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL10_C, (uint8_t *)&reg, 1);
  *val = reg.timestamp_en;
  return ret;
}
References LSM6DSO32_CTRL10_C, lsm6dso32_read_reg(), and lsm6dso32_ctrl10_c_t::timestamp_en.
lsm6dso32_timestamp_raw_get()
int32_t lsm6dso32_timestamp_raw_get (stmdev_ctx_t * ctx, uint32_t * val)
Timestamp first data output register (r). The value is expressed as a 32-bit word and the bit resolution is 25 μs.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1148 of file lsm6dso32_reg.c.
{
  uint8_t buff[4];
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_TIMESTAMP0, buff, 4);
  *val = buff[3];
  *val = (*val * 256U) +  buff[2];
  *val = (*val * 256U) +  buff[1];
  *val = (*val * 256U) +  buff[0];
  return ret;
}
References lsm6dso32_read_reg(), and LSM6DSO32_TIMESTAMP0.
lsm6dso32_timestamp_set()
int32_t lsm6dso32_timestamp_set (stmdev_ctx_t * ctx, uint8_t val)
Enables timestamp counter.[set].
Parameters
ctx read / write interface definitions
val change the values of timestamp_en in reg CTRL10_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1103 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl10_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL10_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.timestamp_en = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL10_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References LSM6DSO32_CTRL10_C, lsm6dso32_read_reg(), lsm6dso32_write_reg(), and lsm6dso32_ctrl10_c_t::timestamp_en.