Da Vinci Firmware: "Serial Interface"
"Serial Interface"
Peripheral Drivers » "LIS2MDL Magnetometer Driver"
This section group all the functions concerning serial interface management.
Modules
STM32H7xx SPI Platform Specific Functions
Functions to connect LIS2MDL driver to STM32H7xx SPI HAL.
Functions
int32_t lis2mdl_spi_mode_set (const stmdev_ctx_t *ctx, lis2mdl_sim_t val)
SPI Serial Interface Mode selection.[set].
int32_t lis2mdl_spi_mode_get (const stmdev_ctx_t *ctx, lis2mdl_sim_t *val)
SPI Serial Interface Mode selection.[get].
int32_t lis2mdl_i2c_interface_set (const stmdev_ctx_t *ctx, lis2mdl_i2c_dis_t val)
Enable/Disable I2C interface.[set].
int32_t lis2mdl_i2c_interface_get (const stmdev_ctx_t *ctx, lis2mdl_i2c_dis_t *val)
Enable/Disable I2C interface.[get].
Detailed Description
This section group all the functions concerning serial interface management.
Function Documentation
lis2mdl_i2c_interface_get()
int32_t lis2mdl_i2c_interface_get (const stmdev_ctx_t * ctx, lis2mdl_i2c_dis_t * val)
Enable/Disable I2C interface.[get].
Parameters
ctx read / write interface definitions.(ptr)
val Get the values of i2c_dis in reg CFG_REG_C.(ptr)
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1332 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  switch (reg.i2c_dis)
  {
    case LIS2MDL_I2C_ENABLE:
      *val = LIS2MDL_I2C_ENABLE;
      break;
    case LIS2MDL_I2C_DISABLE:
      *val = LIS2MDL_I2C_DISABLE;
      break;
    default:
      *val = LIS2MDL_I2C_ENABLE;
      break;
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::i2c_dis, LIS2MDL_CFG_REG_C, LIS2MDL_I2C_DISABLE, LIS2MDL_I2C_ENABLE, and lis2mdl_read_reg().
lis2mdl_i2c_interface_set()
int32_t lis2mdl_i2c_interface_set (const stmdev_ctx_t * ctx, lis2mdl_i2c_dis_t val)
Enable/Disable I2C interface.[set].
Parameters
ctx read / write interface definitions.(ptr)
val change the values of i2c_dis in reg CFG_REG_C
Return values
interface status.(MANDATORY: return 0 -> no Error)
Definition at line 1307 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.i2c_dis = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::i2c_dis, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_write_reg().
lis2mdl_spi_mode_get()
int32_t lis2mdl_spi_mode_get (const stmdev_ctx_t * ctx, lis2mdl_sim_t * val)
SPI Serial Interface Mode selection.[get].
Parameters
ctx read / write interface definitions
val Get the values of 4wspi in reg CFG_REG_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1274 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  switch (reg._4wspi)
  {
    case LIS2MDL_SPI_4_WIRE:
      *val = LIS2MDL_SPI_4_WIRE;
      break;
    case LIS2MDL_SPI_3_WIRE:
      *val = LIS2MDL_SPI_3_WIRE;
      break;
    default:
      *val = LIS2MDL_SPI_3_WIRE;
      break;
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::_4wspi, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), LIS2MDL_SPI_3_WIRE, and LIS2MDL_SPI_4_WIRE.
lis2mdl_spi_mode_set()
int32_t lis2mdl_spi_mode_set (const stmdev_ctx_t * ctx, lis2mdl_sim_t val)
SPI Serial Interface Mode selection.[set].
Parameters
ctx read / write interface definitions
val change the values of 4wspi in reg CFG_REG_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 1250 of file lis2mdl_reg.c.
{
  lis2mdl_cfg_reg_c_t reg;
  int32_t ret;
  ret = lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg._4wspi = (uint8_t)val;
    ret = lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lis2mdl_cfg_reg_c_t::_4wspi, LIS2MDL_CFG_REG_C, lis2mdl_read_reg(), and lis2mdl_write_reg().
Referenced by lis2mdl_init(), and lis2mdl_init_2().