Da Vinci Firmware: Memory Access Functions
Memory Access Functions
Peripheral Drivers » W25Qxxx QSPI Flash Driver
Core functions for reading, writing, and erasing the flash memory.
Functions
HAL_StatusTypeDef QFlash_Read (uint32_t address, uint8_t *buffer, uint32_t dataSize)
HAL_StatusTypeDef QFlash_Write (uint32_t addr, uint8_t *data, uint32_t dataSize)
HAL_StatusTypeDef QFlash_SErase4k (uint32_t addr)
HAL_StatusTypeDef QFlash_BErase32k (uint32_t addr)
HAL_StatusTypeDef QFlash_BErase64k (uint32_t addr)
HAL_StatusTypeDef QFlash_ChipErase (void)
Detailed Description
Core functions for reading, writing, and erasing the flash memory.
Function Documentation
QFlash_BErase32k()
HAL_StatusTypeDef QFlash_BErase32k (uint32_t addr)
Definition at line 968 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    sCommand.Instruction    = W25_B_ERASE32K;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_1_LINE;
    sCommand.NbData         = 0;
    sCommand.Address        = addr;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, and W25_B_ERASE32K.
QFlash_BErase64k()
HAL_StatusTypeDef QFlash_BErase64k (uint32_t addr)
Definition at line 1008 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    sCommand.Instruction    = W25_B_ERASE64K_4B;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_1_LINE;
    sCommand.NbData         = 0;
    sCommand.Address        = addr;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, and W25_B_ERASE64K_4B.
QFlash_ChipErase()
HAL_StatusTypeDef QFlash_ChipErase (void)
Definition at line 1045 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    sCommand.Instruction    = W25_CH_ERASE;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, and W25_CH_ERASE.
Referenced by main().
QFlash_Read()
HAL_StatusTypeDef QFlash_Read (uint32_t address, uint8_t * buffer, uint32_t dataSize)
Definition at line 379 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    if (dataSize==0)
        return HAL_OK;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction        = QFLASH_READ_COMMAND;
    sCommand.Address            = address;
    sCommand.NbData             = dataSize;
    sCommand.DummyCycles        = QFLASH_READ_DUMMYC;
    sCommand.AlternateBytes     = QFLASH_ALT_BYTES;
    sCommand.AlternateBytesSize = QFLASH_ALT_BYTES_S;
    sCommand.AlternateByteMode  = QFLASH_ALT_BYTES_M;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, buffer) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#ifdef FLASH_QSPI_WAIT_FOR_READING_COMPLETE
    QFlash_WaitForDataAvailable(0);
#endif //FLASH_QSPI_WAIT_FOR_READING_COMPLETED
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, buffer, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_ALT_BYTES, QFLASH_ALT_BYTES_M, QFLASH_ALT_BYTES_S, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFLASH_READ_COMMAND, QFLASH_READ_DUMMYC, QFlash_WaitForDataAvailable(), QSpiAvailable, and QSpiReadDataAvailable.
Referenced by DataReader_ReadData(), DataReader_StartDMAReadData(), and main().
QFlash_SErase4k()
HAL_StatusTypeDef QFlash_SErase4k (uint32_t addr)
Definition at line 930 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    sCommand.Instruction    = W25_S_ERASE4K_4B;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_1_LINE;
    sCommand.NbData         = 0;
    sCommand.Address        = addr;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, and W25_S_ERASE4K_4B.
QFlash_Write()
HAL_StatusTypeDef QFlash_Write (uint32_t addr, uint8_t * data, uint32_t dataSize)
Definition at line 875 of file z_qflash_W25QXXX.c.
{
uint32_t quota;
uint32_t inpage_addr;
    if (dataSize==0)
        return HAL_OK;
    // quota is the data size transferred until now
    quota=0;
    // define the starting write position inside the first Flash page to write...
    inpage_addr=addr & (EXT_FLASH_PAGE_SIZE-1);
    // ... so I can detect if more than 1 Flash page has still to be written
    while ((dataSize-quota+inpage_addr)>EXT_FLASH_PAGE_SIZE){
    //loop here, writing separate flash pages...
        if (QFlash_WriteEnable())
            return HAL_ERROR;
        if (QFlash_WriteASinglePage(addr+quota,data+quota,EXT_FLASH_PAGE_SIZE-inpage_addr))
            return HAL_ERROR;
        quota+=(EXT_FLASH_PAGE_SIZE-inpage_addr);
        if(quota>=67108864 - 211200){
            __asm("nop");
        }
        // having aligned data to page border on the first writing
        // next writings start from 0 position inside a page
        inpage_addr=0;
        QFlash_WaitForWritingComplete();
    }
                            // now just write the last Flash page...
    if (dataSize-quota) {   // ... if any
        if (QFlash_WriteEnable())
            return HAL_ERROR;
        if (QFlash_WriteASinglePage(addr+quota,data+quota,dataSize-quota))
            return HAL_ERROR;
        QFlash_WaitForWritingComplete();
    }
    return HAL_OK;
}
References EXT_FLASH_PAGE_SIZE, HAL_ERROR, HAL_OK, QFlash_WaitForWritingComplete(), QFlash_WriteASinglePage(), and QFlash_WriteEnable().
Referenced by check_Calibrating_phase(), and StartKalman_mkf().