Da Vinci Firmware: STM32H7xx SPI Platform Specific Functions
STM32H7xx SPI Platform Specific Functions
Peripheral Drivers » "LIS2MDL Magnetometer Driver" » "Serial Interface"
Functions to connect LIS2MDL driver to STM32H7xx SPI HAL.
Functions
static int32_t platform_spi_write (void *handle, uint8_t reg, const uint8_t *bufp, uint16_t len)
Write data to LIS2MDL sensor via SPI.
static int32_t platform_spi_read (void *handle, uint8_t reg, uint8_t *bufp, uint16_t len)
Read data from LIS2MDL sensor via SPI.
int32_t lis2mdl_init (stmdev_ctx_t *ctx)
Initialize the LIS2MDL sensor.
int32_t lis2mdl_init_2 (stmdev_ctx_t *ctx)
Detailed Description
Functions to connect LIS2MDL driver to STM32H7xx SPI HAL.
Function Documentation
lis2mdl_init()
int32_t lis2mdl_init (stmdev_ctx_t * ctx)
Initialize the LIS2MDL sensor.
Parameters
ctx Sensor context with SPI handle and platform functions
Return values
0 if OK, -1 if error or WHO_AM_I mismatch
Definition at line 1461 of file lis2mdl_reg.c.
{
  uint8_t who_am_i = 0;
  uint8_t val = 0; // Temporary variable for get functions
  lis2mdl_cfg_reg_a_t cfg_a;
  lis2mdl_cfg_reg_c_t cfg_c;
  if (ctx == NULL) return -1;
  ctx->write_reg = platform_spi_write;
  ctx->read_reg = platform_spi_read;
  ctx->handle = &hspi2; // Your SPI_HandleTypeDef
  // Check WHO_AM_I register
  if (lis2mdl_device_id_get(ctx, &who_am_i) != 0) return -1; // Error reading WHO_AM_I
  if (who_am_i != LIS2MDL_ID){
      return -1;
  }  // WHO_AM_I mismatch (LIS2MDL_ID should be 0x40 as per datasheet)
  // Perform a software reset
  if (lis2mdl_reset_set(ctx, 1) != 0) return -1;
  platform_delay(5); // Wait for reset to complete (datasheet doesn't specify, 5ms is a guess)
  do {
    if (lis2mdl_reset_get(ctx, &val) != 0) return -1;
  } while (val); // Poll SOFT_RST bit until it is cleared
  // Reboot memory content to reload calibration parameters
  if (lis2mdl_boot_set(ctx, 1) != 0) return -1;
  platform_delay(5); // Wait for boot to complete
   do {
    if (lis2mdl_boot_get(ctx, &val) != 0) return -1;
  } while (val); // Poll REBOOT bit until it is cleared
  // Configure for 4-wire SPI mode
  // Note: The LIS2MDL CS pin (pin 3) must be tied LOW to enable SPI mode.
  // This function configures the 4WSPI bit in CFG_REG_C for the SDO line.
  if (lis2mdl_spi_mode_set(ctx, LIS2MDL_SPI_4_WIRE) != 0) return -1;
  // Configure CFG_REG_A for:
  // - Temperature compensation enabled
  // - Continuous mode
  // - ODR 10 Hz
  // - High-resolution mode
  // This matches the datasheet startup example (CFG_REG_A = 0x80)
  // Method 1: Using individual set functions (less efficient due to multiple R-M-W)
  // if (lis2mdl_offset_temp_comp_set(ctx, 1) != 0) return -1;
  // if (lis2mdl_operating_mode_set(ctx, LIS2MDL_CONTINUOUS_MODE) != 0) return -1;
  // if (lis2mdl_data_rate_set(ctx, LIS2MDL_ODR_10HZ) != 0) return -1; // Assuming LIS2MDL_ODR_10HZ is defined
  // if (lis2mdl_power_mode_set(ctx, LIS2MDL_HIGH_RESOLUTION) != 0) return -1;
  // Method 2: Direct write to CFG_REG_A (more efficient)
  cfg_a.comp_temp_en = 1;
  cfg_a.reboot = 0;
  cfg_a.soft_rst = 0;
  cfg_a.lp = (uint8_t)LIS2MDL_HIGH_RESOLUTION; // Assuming LIS2MDL_HIGH_RESOLUTION = 0
  cfg_a.odr = (uint8_t)LIS2MDL_ODR_10Hz;       // Assuming LIS2MDL_ODR_10Hz = 0
  cfg_a.md = (uint8_t)LIS2MDL_CONTINUOUS_MODE; // Assuming LIS2MDL_CONTINUOUS_MODE = 0
  if (lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t*)&cfg_a, 1) != 0) return -1;
  // Configure CFG_REG_C for:
  // - Block Data Update (BDU) enabled
  // - Data Ready signal on INT/DRDY pin enabled (optional, as per datasheet startup example)
  // - 4-wire SPI is already set by lis2mdl_spi_mode_set above.
  // Method 1: Using individual set functions
  // if (lis2mdl_block_data_update_set(ctx, 1) != 0) return -1;
  // if (lis2mdl_drdy_on_pin_set(ctx, 1) != 0) return -1; // Optional: enable DRDY on pin
  // Method 2: Direct write to CFG_REG_C (more efficient, considers 4WSPI already set)
  if (lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t*)&cfg_c, 1) != 0) return -1;
  cfg_c.bdu = 1;
  cfg_c.drdy_on_pin = 1; // Enable DRDY on pin as per datasheet example
  // cfg_c._4wspi is already set by lis2mdl_spi_mode_set, no need to change it here
  // unless lis2mdl_spi_mode_set is not called before this.
  // For safety, ensure it's set if not using the dedicated function earlier:
  // cfg_c._4wspi = 1; // If LIS2MDL_SPI_4_WIRE is desired
  cfg_c.i2c_dis = 1; // Disable I2C if exclusively using SPI
  cfg_c.int_on_pin = 0; // Disable interrupt on pin unless specifically needed
  cfg_c.self_test = 0; // Disable self-test
  cfg_c.ble = (uint8_t)LIS2MDL_LSB_AT_LOW_ADD; // Default data format
  if (lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t*)&cfg_c, 1) != 0) return -1;
  // Sensor is now initialized with basic settings.
  // Further configuration (e.g., interrupts, thresholds) can be done as needed.
  return 0; // Success
}
References lis2mdl_cfg_reg_c_t::bdu, lis2mdl_cfg_reg_c_t::ble, lis2mdl_cfg_reg_a_t::comp_temp_en, lis2mdl_cfg_reg_c_t::drdy_on_pin, stmdev_ctx_t::handle, hspi2, lis2mdl_cfg_reg_c_t::i2c_dis, lis2mdl_cfg_reg_c_t::int_on_pin, lis2mdl_boot_get(), lis2mdl_boot_set(), LIS2MDL_CFG_REG_A, LIS2MDL_CFG_REG_C, LIS2MDL_CONTINUOUS_MODE, lis2mdl_device_id_get(), LIS2MDL_HIGH_RESOLUTION, LIS2MDL_ID, LIS2MDL_LSB_AT_LOW_ADD, LIS2MDL_ODR_10Hz, lis2mdl_read_reg(), lis2mdl_reset_get(), lis2mdl_reset_set(), LIS2MDL_SPI_4_WIRE, lis2mdl_spi_mode_set(), lis2mdl_write_reg(), lis2mdl_cfg_reg_a_t::lp, lis2mdl_cfg_reg_a_t::md, NULL, lis2mdl_cfg_reg_a_t::odr, platform_delay, platform_spi_read(), platform_spi_write(), stmdev_ctx_t::read_reg, lis2mdl_cfg_reg_a_t::reboot, lis2mdl_cfg_reg_c_t::self_test, lis2mdl_cfg_reg_a_t::soft_rst, and stmdev_ctx_t::write_reg.
lis2mdl_init_2()
int32_t lis2mdl_init_2 (stmdev_ctx_t * ctx)
Definition at line 1556 of file lis2mdl_reg.c.
{
  uint8_t who_am_i = 0;
  uint8_t val = 0; // Temporary variable for get functions
  lis2mdl_cfg_reg_a_t cfg_a;
  lis2mdl_cfg_reg_c_t cfg_c;
  if (ctx == NULL) return -1;
  ctx->write_reg = platform_spi_write;
  ctx->read_reg = platform_spi_read;
  ctx->handle = &hspi3; // Your SPI_HandleTypeDef
  // Check WHO_AM_I register
  if (lis2mdl_device_id_get(ctx, &who_am_i) != 0) return -1; // Error reading WHO_AM_I
  if (who_am_i != LIS2MDL_ID) return -1; // WHO_AM_I mismatch (LIS2MDL_ID should be 0x40 as per datasheet)
  // Perform a software reset
  if (lis2mdl_reset_set(ctx, 1) != 0) return -1;
  platform_delay(5); // Wait for reset to complete (datasheet doesn't specify, 5ms is a guess)
  do {
    if (lis2mdl_reset_get(ctx, &val) != 0) return -1;
  } while (val); // Poll SOFT_RST bit until it is cleared
  // Reboot memory content to reload calibration parameters
  if (lis2mdl_boot_set(ctx, 1) != 0) return -1;
  platform_delay(5); // Wait for boot to complete
   do {
    if (lis2mdl_boot_get(ctx, &val) != 0) return -1;
  } while (val); // Poll REBOOT bit until it is cleared
  // Configure for 4-wire SPI mode
  // Note: The LIS2MDL CS pin (pin 3) must be tied LOW to enable SPI mode.
  // This function configures the 4WSPI bit in CFG_REG_C for the SDO line.
  if (lis2mdl_spi_mode_set(ctx, LIS2MDL_SPI_4_WIRE) != 0) return -1;
  // Configure CFG_REG_A for:
  // - Temperature compensation enabled
  // - Continuous mode
  // - ODR 10 Hz
  // - High-resolution mode
  // This matches the datasheet startup example (CFG_REG_A = 0x80)
  // Method 1: Using individual set functions (less efficient due to multiple R-M-W)
  // if (lis2mdl_offset_temp_comp_set(ctx, 1) != 0) return -1;
  // if (lis2mdl_operating_mode_set(ctx, LIS2MDL_CONTINUOUS_MODE) != 0) return -1;
  // if (lis2mdl_data_rate_set(ctx, LIS2MDL_ODR_10HZ) != 0) return -1; // Assuming LIS2MDL_ODR_10HZ is defined
  // if (lis2mdl_power_mode_set(ctx, LIS2MDL_HIGH_RESOLUTION) != 0) return -1;
  // Method 2: Direct write to CFG_REG_A (more efficient)
  cfg_a.comp_temp_en = 1;
  cfg_a.reboot = 0;
  cfg_a.soft_rst = 0;
  cfg_a.lp = (uint8_t)LIS2MDL_HIGH_RESOLUTION; // Assuming LIS2MDL_HIGH_RESOLUTION = 0
  cfg_a.odr = (uint8_t)LIS2MDL_ODR_10Hz;       // Assuming LIS2MDL_ODR_10Hz = 0
  cfg_a.md = (uint8_t)LIS2MDL_CONTINUOUS_MODE; // Assuming LIS2MDL_CONTINUOUS_MODE = 0
  if (lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_A, (uint8_t*)&cfg_a, 1) != 0) return -1;
  // Configure CFG_REG_C for:
  // - Block Data Update (BDU) enabled
  // - Data Ready signal on INT/DRDY pin enabled (optional, as per datasheet startup example)
  // - 4-wire SPI is already set by lis2mdl_spi_mode_set above.
  // Method 1: Using individual set functions
  // if (lis2mdl_block_data_update_set(ctx, 1) != 0) return -1;
  // if (lis2mdl_drdy_on_pin_set(ctx, 1) != 0) return -1; // Optional: enable DRDY on pin
  // Method 2: Direct write to CFG_REG_C (more efficient, considers 4WSPI already set)
  if (lis2mdl_read_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t*)&cfg_c, 1) != 0) return -1;
  cfg_c.bdu = 1;
  cfg_c.drdy_on_pin = 1; // Enable DRDY on pin as per datasheet example
  // cfg_c._4wspi is already set by lis2mdl_spi_mode_set, no need to change it here
  // unless lis2mdl_spi_mode_set is not called before this.
  // For safety, ensure it's set if not using the dedicated function earlier:
  // cfg_c._4wspi = 1; // If LIS2MDL_SPI_4_WIRE is desired
  cfg_c.i2c_dis = 1; // Disable I2C if exclusively using SPI
  cfg_c.int_on_pin = 0; // Disable interrupt on pin unless specifically needed
  cfg_c.self_test = 0; // Disable self-test
  cfg_c.ble = (uint8_t)LIS2MDL_LSB_AT_LOW_ADD; // Default data format
  if (lis2mdl_write_reg(ctx, LIS2MDL_CFG_REG_C, (uint8_t*)&cfg_c, 1) != 0) return -1;
  // Sensor is now initialized with basic settings.
  // Further configuration (e.g., interrupts, thresholds) can be done as needed.
  return 0; // Success
}
References lis2mdl_cfg_reg_c_t::bdu, lis2mdl_cfg_reg_c_t::ble, lis2mdl_cfg_reg_a_t::comp_temp_en, lis2mdl_cfg_reg_c_t::drdy_on_pin, stmdev_ctx_t::handle, hspi3, lis2mdl_cfg_reg_c_t::i2c_dis, lis2mdl_cfg_reg_c_t::int_on_pin, lis2mdl_boot_get(), lis2mdl_boot_set(), LIS2MDL_CFG_REG_A, LIS2MDL_CFG_REG_C, LIS2MDL_CONTINUOUS_MODE, lis2mdl_device_id_get(), LIS2MDL_HIGH_RESOLUTION, LIS2MDL_ID, LIS2MDL_LSB_AT_LOW_ADD, LIS2MDL_ODR_10Hz, lis2mdl_read_reg(), lis2mdl_reset_get(), lis2mdl_reset_set(), LIS2MDL_SPI_4_WIRE, lis2mdl_spi_mode_set(), lis2mdl_write_reg(), lis2mdl_cfg_reg_a_t::lp, lis2mdl_cfg_reg_a_t::md, NULL, lis2mdl_cfg_reg_a_t::odr, platform_delay, platform_spi_read(), platform_spi_write(), stmdev_ctx_t::read_reg, lis2mdl_cfg_reg_a_t::reboot, lis2mdl_cfg_reg_c_t::self_test, lis2mdl_cfg_reg_a_t::soft_rst, and stmdev_ctx_t::write_reg.
platform_spi_read()
static int32_t platform_spi_read (void * handle, uint8_t reg, uint8_t * bufp, uint16_t len) static
Read data from LIS2MDL sensor via SPI.
Parameters
handle Pointer to SPI_HandleTypeDef (passed via stmdev_ctx_t)
reg Register address to read from
bufp Pointer to data buffer to store read data
len Number of bytes to read
Return values
0 if OK, -1 if error
Definition at line 1418 of file lis2mdl_reg.c.
{
  SPI_HandleTypeDef *spi_handle = (SPI_HandleTypeDef *)handle;
  uint8_t cmd_byte;
  if (spi_handle == NULL || bufp == NULL) {
    return -1; // Invalid arguments
  }
  // LIS2MDL SPI read command: MSB=1 for read, followed by 7-bit register address
  cmd_byte = (reg & 0x7F) | 0x80; // Set MSB to 1 for read
  if(HAL_GPIO_ReadPin(IMU_CS_GPIO_Port,IMU_CS_Pin)!=GPIO_PIN_SET){IMU_CS_HIGH;}
  if(HAL_GPIO_ReadPin(BARO_CS_GPIO_Port,BARO_CS_Pin)!=GPIO_PIN_SET){BMP390_CS_HIGH;}
  // Pull CS pin low to select the device
  HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_RESET);
  // Transmit the command byte (register address with read flag)
  if (HAL_SPI_Transmit(spi_handle, &cmd_byte, 1, LIS2MDL_SPI_TIMEOUT) != HAL_OK)
  {
    HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_SET); // Release CS
    return -1; // SPI transmission error
  }
  // Receive the data
  if (HAL_SPI_Receive(spi_handle, bufp, len, LIS2MDL_SPI_TIMEOUT) != HAL_OK)
  {
    HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_SET); // Release CS
    return -1; // SPI reception error
  }
  // Pull CS pin high to deselect the device
  HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_SET);
  return 0; // Success
}
References HAL_OK, LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, LIS2MDL_SPI_TIMEOUT, and NULL.
Referenced by lis2mdl_init(), and lis2mdl_init_2().
platform_spi_write()
static int32_t platform_spi_write (void * handle, uint8_t reg, const uint8_t * bufp, uint16_t len) static
Write data to LIS2MDL sensor via SPI.
Parameters
handle Pointer to SPI_HandleTypeDef (passed via stmdev_ctx_t)
reg Register address to write to
bufp Pointer to data buffer to write
len Number of bytes to write
Return values
0 if OK, -1 if error
Definition at line 1372 of file lis2mdl_reg.c.
{
  SPI_HandleTypeDef *spi_handle = (SPI_HandleTypeDef *)handle;
  uint8_t cmd_byte;
  if (spi_handle == NULL || bufp == NULL) {
    return -1; // Invalid arguments
  }
  // LIS2MDL SPI write command: MSB=0 for write, followed by 7-bit register address
  cmd_byte = reg & 0x7F; // Ensure MSB is 0 for write
  BMP390_CS_HIGH;
  IMU_CS_HIGH;
  // Pull CS pin low to select the device
  HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_RESET);
  // Transmit the command byte (register address with write flag)
  if (HAL_SPI_Transmit(spi_handle, &cmd_byte, 1, LIS2MDL_SPI_TIMEOUT) != HAL_OK)
  {
    HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_SET); // Release CS
    return -1; // SPI transmission error
  }
  // Transmit the data
  if (HAL_SPI_Transmit(spi_handle, (uint8_t*)bufp, len, LIS2MDL_SPI_TIMEOUT) != HAL_OK)
  {
    HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_SET); // Release CS
    return -1; // SPI transmission error
  }
  // Pull CS pin high to deselect the device
  HAL_GPIO_WritePin(LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, GPIO_PIN_SET);
  return 0; // Success
}
References HAL_OK, LIS2MDL_CS_GPIO_Port, LIS2MDL_CS_Pin, LIS2MDL_SPI_TIMEOUT, and NULL.
Referenced by lis2mdl_init(), and lis2mdl_init_2().