Da Vinci Firmware: "Interfaces Functions"
"Interfaces Functions"
Peripheral Drivers » "LIS2MDL Magnetometer Driver"
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Functions
int32_t __weak lis2mdl_read_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t __weak lis2mdl_write_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
Detailed Description
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Function Documentation
lis2mdl_read_reg()
int32_t __weak lis2mdl_read_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 66 of file lis2mdl_reg.c.
{
  int32_t ret;
  if (ctx == NULL)
  {
    return -1;
  }
  ret = ctx->read_reg(ctx->handle, reg, data, len);
  return ret;
}
References stmdev_ctx_t::handle, NULL, and stmdev_ctx_t::read_reg.
Referenced by lis2mdl_block_data_update_get(), lis2mdl_block_data_update_set(), lis2mdl_boot_get(), lis2mdl_boot_set(), lis2mdl_data_format_get(), lis2mdl_data_format_set(), lis2mdl_data_rate_get(), lis2mdl_data_rate_set(), lis2mdl_device_id_get(), lis2mdl_drdy_on_pin_get(), lis2mdl_drdy_on_pin_set(), lis2mdl_i2c_interface_get(), lis2mdl_i2c_interface_set(), lis2mdl_init(), lis2mdl_init_2(), lis2mdl_int_gen_conf_get(), lis2mdl_int_gen_source_get(), lis2mdl_int_gen_threshold_get(), lis2mdl_int_on_pin_get(), lis2mdl_int_on_pin_set(), lis2mdl_low_pass_bandwidth_get(), lis2mdl_low_pass_bandwidth_set(), lis2mdl_mag_data_ovr_get(), lis2mdl_mag_data_ready_get(), lis2mdl_mag_user_offset_get(), lis2mdl_magnetic_raw_get(), lis2mdl_offset_int_conf_get(), lis2mdl_offset_int_conf_set(), lis2mdl_offset_temp_comp_get(), lis2mdl_offset_temp_comp_set(), lis2mdl_operating_mode_get(), lis2mdl_operating_mode_set(), lis2mdl_power_mode_get(), lis2mdl_power_mode_set(), lis2mdl_reset_get(), lis2mdl_reset_set(), lis2mdl_self_test_get(), lis2mdl_self_test_set(), lis2mdl_set_rst_mode_get(), lis2mdl_set_rst_mode_set(), lis2mdl_set_rst_sensor_single_get(), lis2mdl_set_rst_sensor_single_set(), lis2mdl_spi_mode_get(), lis2mdl_spi_mode_set(), lis2mdl_status_get(), and lis2mdl_temperature_raw_get().
lis2mdl_write_reg()
int32_t __weak lis2mdl_write_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 92 of file lis2mdl_reg.c.
{
  int32_t ret;
  if (ctx == NULL)
  {
    return -1;
  }
  ret = ctx->write_reg(ctx->handle, reg, data, len);
  return ret;
}
References stmdev_ctx_t::handle, NULL, and stmdev_ctx_t::write_reg.
Referenced by lis2mdl_block_data_update_set(), lis2mdl_boot_set(), lis2mdl_data_format_set(), lis2mdl_data_rate_set(), lis2mdl_drdy_on_pin_set(), lis2mdl_i2c_interface_set(), lis2mdl_init(), lis2mdl_init_2(), lis2mdl_int_gen_conf_set(), lis2mdl_int_gen_threshold_set(), lis2mdl_int_on_pin_set(), lis2mdl_low_pass_bandwidth_set(), lis2mdl_mag_user_offset_set(), lis2mdl_offset_int_conf_set(), lis2mdl_offset_temp_comp_set(), lis2mdl_operating_mode_set(), lis2mdl_power_mode_set(), lis2mdl_reset_set(), lis2mdl_self_test_set(), lis2mdl_set_rst_mode_set(), lis2mdl_set_rst_sensor_single_set(), and lis2mdl_spi_mode_set().