Da Vinci Firmware: Initialization and ID Functions
Initialization and ID Functions
Peripheral Drivers » W25Qxxx QSPI Flash Driver
Functions
HAL_StatusTypeDef QFlash_ReadManufactutrerAndDevID (uint16_t *dataptr)
read id of the winbond
HAL_StatusTypeDef QFlash_Init (void)
HAL_StatusTypeDef QFlash_ReadJedecID (uint8_t *dataptr)
HAL_StatusTypeDef QFlash_ReadSFDP (uint8_t *dataptr)
HAL_StatusTypeDef QFlash_ReadDevID (uint8_t *dataptr)
Detailed Description
Function Documentation
QFlash_Init()
HAL_StatusTypeDef QFlash_Init (void)
Definition at line 269 of file z_qflash_W25QXXX.c.
{
uint8_t data[256];
    HAL_Delay(6);   // supposing init is called on system startup: 5 ms (tPUW) required after power-up to be fully available
// reset the device (supposing it is a W25Q)
    if (QFlash_Reset()!=HAL_OK)
        return HAL_ERROR;
// testing if an SFPD device is connected and working
    for (uint8_t k=0;k!=3;k++)
          data[k]=0xFF;
    if (QFlash_ReadSFDP(data))
        return HAL_ERROR;
    if (!((data[0]=='S') && (data[1]=='F') && (data[2]=='D') && (data[3]=='P')))
        if (!((data[0]=='S') && (data[2]=='F') && (data[5]=='D') && (data[7]=='P')))  //this is in case of dual flash configuration
            return HAL_ERROR;
//testing if it is a Winbond memory
    if (QFlash_ReadJedecID(data)) //select the memSize byte
        return HAL_ERROR;;
    if (data[0] != 0xEF)  // if ManufacturerID is not Winbond (0xEF)
        return HAL_ERROR;
    QSPI_CommandTypeDef sCmd_4byte = {0};
    QFlash_DefaultCmd(&sCmd_4byte); // To get default instruction mode, etc.
    sCmd_4byte.Instruction    = W25_ENTER_4B_ADDR; // This is 0xB7
    sCmd_4byte.AddressMode    = QSPI_ADDRESS_NONE;   // Correct, 0xB7 takes no address
    sCmd_4byte.DataMode       = QSPI_DATA_NONE;      // Correct, 0xB7 has no data
    sCmd_4byte.InstructionMode= QSPI_INSTRUCTION_1_LINE; // Correct, 0xB7 is a 1-line command
    // DummyCycles, NbData, etc., default to 0 or are not relevant
    // Handle QSpiAvailable if using DMA for this command
    #ifdef EXT_FLASH_QSPI_DMA_MODE
        if (QFlash_WaitForQSPIAvailable(QFLASH_DEF_TIMEOUT) != HAL_OK) return HAL_ERROR;
        // QSpiAvailable = 0; // Not strictly needed for a single HAL_QSPI_Command if it's blocking
                            // and not followed by DMA transmit/receive in THIS sequence.
                            // But good practice if other parts of the system rely on it.
    #endif
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCmd_4byte, QFLASH_DEF_TIMEOUT) != HAL_OK) {
        // #ifdef EXT_FLASH_QSPI_DMA_MODE
        //  QSpiAvailable = 1;
        // #endif
        return HAL_ERROR;
    }
#ifdef FLASH_QSPI_MEMORY_MAPPED
// reset and tests are OK: enable memory mapped mode
    if (QFlash_EnableMemoryMappedMode()==HAL_ERROR)
        return HAL_ERROR;
#endif //FLASH_QSPI_MEMORY_MAPPED
    return HAL_OK;  //return memSize as per table in Flash_ReadJedecID() definition
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_ReadJedecID(), QFlash_ReadSFDP(), QFlash_Reset(), QFlash_WaitForQSPIAvailable(), and W25_ENTER_4B_ADDR.
Referenced by main().
QFlash_ReadDevID()
HAL_StatusTypeDef QFlash_ReadDevID (uint8_t * dataptr)
Definition at line 1141 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_POWERUP_ID;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_1_LINE;
    sCommand.AddressSize    = QSPI_ADDRESS_24_BITS;  // I need to send 3 dummy bytes avter command
    sCommand.Address        = 0;
    sCommand.NbData         = 1; //after 3 dummy bytes I can read the Device ID
    sCommand.DummyCycles    = 0;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_POWERUP_ID.
QFlash_ReadJedecID()
HAL_StatusTypeDef QFlash_ReadJedecID (uint8_t * dataptr)
Definition at line 183 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_JEDEC_ID;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0;
    sCommand.NbData         = 3;
    sCommand.DummyCycles    = 0;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_JEDEC_ID.
Referenced by QFlash_Init().
QFlash_ReadManufactutrerAndDevID()
HAL_StatusTypeDef QFlash_ReadManufactutrerAndDevID (uint16_t * dataptr)
read id of the winbond
Definition at line 1183 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_MAN_DEVICE_ID;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_1_LINE;
    sCommand.AddressSize    = QSPI_ADDRESS_24_BITS;  // I need to send 3 dummy bytes avter command
    sCommand.Address        = 0;
    sCommand.NbData         = 2; //after 3 dummy bytes I can read the Device ID
    sCommand.DummyCycles    = 0;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, (uint8_t *) dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, (uint8_t *) dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_MAN_DEVICE_ID.
QFlash_ReadSFDP()
HAL_StatusTypeDef QFlash_ReadSFDP (uint8_t * dataptr)
Definition at line 225 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_R_SFPD_REG;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_1_LINE;
    sCommand.AddressSize    = QSPI_ADDRESS_24_BITS;
    sCommand.Address        = 0;
    sCommand.NbData         = 256;
    sCommand.DummyCycles    = 8;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data requested unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_R_SFPD_REG.
Referenced by QFlash_Init().