Da Vinci Firmware: LSM6DSO32_Wake_Up_event
LSM6DSO32_Wake_Up_event
Peripheral Drivers » "LSM6DSO32 IMU Driver"
This section groups all the functions that manage the Wake Up event generation.
Functions
int32_t lsm6dso32_wkup_ths_weight_set (stmdev_ctx_t *ctx, lsm6dso32_wake_ths_w_t val)
Weight of 1 LSB of wakeup threshold.[set] 0: 1 LSB =FS_XL / 64 1: 1 LSB = FS_XL / 256.
int32_t lsm6dso32_wkup_ths_weight_get (stmdev_ctx_t *ctx, lsm6dso32_wake_ths_w_t *val)
Weight of 1 LSB of wakeup threshold.[get] 0: 1 LSB =FS_XL / 64 1: 1 LSB = FS_XL / 256.
int32_t lsm6dso32_wkup_threshold_set (stmdev_ctx_t *ctx, uint8_t val)
Threshold for wakeup: 1 LSB weight depends on WAKE_THS_W in WAKE_UP_DUR.[set].
int32_t lsm6dso32_wkup_threshold_get (stmdev_ctx_t *ctx, uint8_t *val)
Threshold for wakeup: 1 LSB weight depends on WAKE_THS_W in WAKE_UP_DUR.[get].
int32_t lsm6dso32_xl_usr_offset_on_wkup_set (stmdev_ctx_t *ctx, uint8_t val)
Wake up duration event.[set] 1LSb = 1 / ODR.
int32_t lsm6dso32_xl_usr_offset_on_wkup_get (stmdev_ctx_t *ctx, uint8_t *val)
Wake up duration event.[get] 1LSb = 1 / ODR.
int32_t lsm6dso32_wkup_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Wake up duration event.[set] 1LSb = 1 / ODR.
int32_t lsm6dso32_wkup_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Wake up duration event.[get] 1LSb = 1 / ODR.
Detailed Description
This section groups all the functions that manage the Wake Up event generation.
Function Documentation
lsm6dso32_wkup_dur_get()
int32_t lsm6dso32_wkup_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Wake up duration event.[get] 1LSb = 1 / ODR.
Parameters
ctx read / write interface definitions
val change the values of wake_dur in reg WAKE_UP_DUR
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3979 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_dur_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_DUR, (uint8_t *)&reg, 1);
  *val = reg.wake_dur;
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_DUR, and lsm6dso32_wake_up_dur_t::wake_dur.
lsm6dso32_wkup_dur_set()
int32_t lsm6dso32_wkup_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Wake up duration event.[set] 1LSb = 1 / ODR.
Parameters
ctx read / write interface definitions
val change the values of wake_dur in reg WAKE_UP_DUR
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3954 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_dur_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_DUR, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.wake_dur = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_WAKE_UP_DUR, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_DUR, lsm6dso32_write_reg(), and lsm6dso32_wake_up_dur_t::wake_dur.
lsm6dso32_wkup_threshold_get()
int32_t lsm6dso32_wkup_threshold_get (stmdev_ctx_t * ctx, uint8_t * val)
Threshold for wakeup: 1 LSB weight depends on WAKE_THS_W in WAKE_UP_DUR.[get].
Parameters
ctx read / write interface definitions
val change the values of wk_ths in reg WAKE_UP_THS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3887 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_ths_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_THS, (uint8_t *)&reg, 1);
  *val = reg.wk_ths;
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_THS, and lsm6dso32_wake_up_ths_t::wk_ths.
lsm6dso32_wkup_threshold_set()
int32_t lsm6dso32_wkup_threshold_set (stmdev_ctx_t * ctx, uint8_t val)
Threshold for wakeup: 1 LSB weight depends on WAKE_THS_W in WAKE_UP_DUR.[set].
Parameters
ctx read / write interface definitions
val change the values of wk_ths in reg WAKE_UP_THS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3862 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_ths_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_THS, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.wk_ths = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_WAKE_UP_THS, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_THS, lsm6dso32_write_reg(), and lsm6dso32_wake_up_ths_t::wk_ths.
lsm6dso32_wkup_ths_weight_get()
int32_t lsm6dso32_wkup_ths_weight_get (stmdev_ctx_t * ctx, lsm6dso32_wake_ths_w_t * val)
Weight of 1 LSB of wakeup threshold.[get] 0: 1 LSB =FS_XL / 64 1: 1 LSB = FS_XL / 256.
Parameters
ctx read / write interface definitions
val Get the values of wake_ths_w in reg WAKE_UP_DUR
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3827 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_dur_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_DUR, (uint8_t *)&reg, 1);
  switch (reg.wake_ths_w)
  {
    case LSM6DSO32_LSb_FS_DIV_64:
      *val = LSM6DSO32_LSb_FS_DIV_64;
      break;
    case LSM6DSO32_LSb_FS_DIV_256:
      *val = LSM6DSO32_LSb_FS_DIV_256;
      break;
    default:
      *val = LSM6DSO32_LSb_FS_DIV_64;
      break;
  }
  return ret;
}
References LSM6DSO32_LSb_FS_DIV_256, LSM6DSO32_LSb_FS_DIV_64, lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_DUR, and lsm6dso32_wake_up_dur_t::wake_ths_w.
lsm6dso32_wkup_ths_weight_set()
int32_t lsm6dso32_wkup_ths_weight_set (stmdev_ctx_t * ctx, lsm6dso32_wake_ths_w_t val)
Weight of 1 LSB of wakeup threshold.[set] 0: 1 LSB =FS_XL / 64 1: 1 LSB = FS_XL / 256.
Parameters
ctx read / write interface definitions
val change the values of wake_ths_w in reg WAKE_UP_DUR
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3799 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_dur_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_DUR, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.wake_ths_w = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_WAKE_UP_DUR, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_DUR, lsm6dso32_write_reg(), and lsm6dso32_wake_up_dur_t::wake_ths_w.
lsm6dso32_xl_usr_offset_on_wkup_get()
int32_t lsm6dso32_xl_usr_offset_on_wkup_get (stmdev_ctx_t * ctx, uint8_t * val)
Wake up duration event.[get] 1LSb = 1 / ODR.
Parameters
ctx read / write interface definitions
val change the values of usr_off_on_wu in reg WAKE_UP_THS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3933 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_ths_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_THS, (uint8_t *)&reg, 1);
  *val = reg.usr_off_on_wu;
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_THS, and lsm6dso32_wake_up_ths_t::usr_off_on_wu.
lsm6dso32_xl_usr_offset_on_wkup_set()
int32_t lsm6dso32_xl_usr_offset_on_wkup_set (stmdev_ctx_t * ctx, uint8_t val)
Wake up duration event.[set] 1LSb = 1 / ODR.
Parameters
ctx read / write interface definitions
val change the values of usr_off_on_wu in reg WAKE_UP_THS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 3907 of file lsm6dso32_reg.c.
{
  lsm6dso32_wake_up_ths_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_WAKE_UP_THS, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.usr_off_on_wu = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_WAKE_UP_THS, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_read_reg(), LSM6DSO32_WAKE_UP_THS, lsm6dso32_write_reg(), and lsm6dso32_wake_up_ths_t::usr_off_on_wu.