Da Vinci Firmware: Driver Status & Helpers
Driver Status & Helpers
Peripheral Drivers » W25Qxxx QSPI Flash Driver
Functions for checking the driver's internal state and managing the QSPI bus.
Functions
HAL_StatusTypeDef QFlash_WriteEnable ()
enables writes
HAL_StatusTypeDef QFlash_WriteDisable ()
disables writes
HAL_StatusTypeDef QFlash_WriteSR2 (uint8_t data)
writes to register 2
HAL_StatusTypeDef QFlash_WriteSR3 (uint8_t data)
writes to register 3
uint8_t QFlash_IsQSPIAvailable (void)
HAL_StatusTypeDef QFlash_WaitForQSPIAvailable (uint32_t timeout)
uint8_t QFlash_IsDataAvailable (void)
HAL_StatusTypeDef QFlash_WaitForDataAvailable (uint32_t timeout)
void QFlash_DefaultCmd (QSPI_CommandTypeDef *sCommand)
Detailed Description
Functions for checking the driver's internal state and managing the QSPI bus.
Function Documentation
QFlash_DefaultCmd()
void QFlash_DefaultCmd (QSPI_CommandTypeDef * sCommand)
Definition at line 105 of file z_qflash_W25QXXX.c.
{
    sCommand->InstructionMode = QFLASH_INSTRUCTION_MODE;
    sCommand->AddressMode = QFLASH_ADDRESS_MODE;
    sCommand->AddressSize = QFLASH_ADDRESS_SIZE;
    sCommand->DataMode = QFLASH_DATA_MODE;
    sCommand->AlternateByteMode = QFLASH_ALTERNATE_BYTE_MODE;
    sCommand->DdrMode = QFLASH_DDR_MODE;
    sCommand->DdrHoldHalfCycle = QFLASH_DDR_HOLD_HALF_CYCLE;
    sCommand->SIOOMode = QFLASH_SIOO_MODE;
    sCommand->DummyCycles = QFLASH_DUMMY_CYCLES;
    return;
}
References QFLASH_ADDRESS_MODE, QFLASH_ADDRESS_SIZE, QFLASH_ALTERNATE_BYTE_MODE, QFLASH_DATA_MODE, QFLASH_DDR_HOLD_HALF_CYCLE, QFLASH_DDR_MODE, QFLASH_DUMMY_CYCLES, QFLASH_INSTRUCTION_MODE, and QFLASH_SIOO_MODE.
Referenced by QFlash_BErase32k(), QFlash_BErase64k(), QFlash_ChipErase(), QFlash_Init(), QFlash_PowerDown(), QFlash_PowerUp(), QFlash_Read(), QFlash_ReadDevID(), QFlash_ReadJedecID(), QFlash_ReadManufactutrerAndDevID(), QFlash_ReadSFDP(), QFlash_ReadSR1(), QFlash_ReadSR2(), QFlash_ReadSR3(), QFlash_Reset(), QFlash_SErase4k(), QFlash_WaitForWritingComplete(), QFlash_WriteASinglePage(), QFlash_WriteDisable(), QFlash_WriteEnable(), QFlash_WriteSR2(), and QFlash_WriteSR3().
QFlash_IsDataAvailable()
uint8_t QFlash_IsDataAvailable (void)
Definition at line 70 of file z_qflash_W25QXXX.c.
{
    return QSpiReadDataAvailable;
}
References QSpiReadDataAvailable.
QFlash_IsQSPIAvailable()
uint8_t QFlash_IsQSPIAvailable (void)
Definition at line 35 of file z_qflash_W25QXXX.c.
{
    return QSpiAvailable;
}
References QSpiAvailable.
QFlash_WaitForDataAvailable()
HAL_StatusTypeDef QFlash_WaitForDataAvailable (uint32_t timeout)
Definition at line 85 of file z_qflash_W25QXXX.c.
{
    uint32_t curtime = HAL_GetTick();
    while ((!QSpiReadDataAvailable) && ((timeout==0) || ((HAL_GetTick()-curtime)<=timeout))) {};
    if (!QSpiReadDataAvailable)
        return HAL_ERROR;
    return HAL_OK;
};
References HAL_ERROR, HAL_OK, and QSpiReadDataAvailable.
Referenced by QFlash_Read(), QFlash_ReadDevID(), QFlash_ReadJedecID(), QFlash_ReadManufactutrerAndDevID(), QFlash_ReadSFDP(), QFlash_ReadSR1(), QFlash_ReadSR2(), and QFlash_ReadSR3().
QFlash_WaitForQSPIAvailable()
HAL_StatusTypeDef QFlash_WaitForQSPIAvailable (uint32_t timeout)
Definition at line 49 of file z_qflash_W25QXXX.c.
{
    uint32_t curtime = HAL_GetTick();
    while ((!QSpiAvailable) && ((timeout==0) || ((HAL_GetTick()-curtime)<=timeout))) {};
    if (!QSpiAvailable)
        return HAL_ERROR;
    return HAL_OK;
};
References HAL_ERROR, HAL_OK, and QSpiAvailable.
Referenced by QFlash_Init().
QFlash_WriteDisable()
HAL_StatusTypeDef QFlash_WriteDisable (void)
disables writes
Definition at line 475 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_DISABLE;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QSpiAvailable, and W25_W_DISABLE.
Referenced by QFlash_CheckSR1().
QFlash_WriteEnable()
HAL_StatusTypeDef QFlash_WriteEnable (void)
enables writes
Definition at line 425 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
//Send a "Write Enable" command
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_ENABLE;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
/*
//Wait for Write Enable bit set
    QSPI_AutoPollingTypeDef sConfig;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction = W25_R_SR1;
    sCommand.DataMode = QSPI_DATA_1_LINE;
    sCommand.AddressMode = QSPI_ADDRESS_NONE;
    sConfig.Mask = SR1_BIT_WEL;
    sConfig.Match = 2;
    sConfig.MatchMode = QSPI_MATCH_MODE_AND;
    sConfig.StatusBytesSize = 1;
    sConfig.Interval = 0x10;
    sConfig.AutomaticStop = QSPI_AUTOMATIC_STOP_ENABLE;
    if (HAL_QSPI_AutoPolling(&FLASH_QSPI_PORT, &sCommand, &sConfig, QFLASH_BSY_TIMEOUT) != HAL_OK) {
        return HAL_ERROR;
    }
*/
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QSpiAvailable, and W25_W_ENABLE.
Referenced by QFlash_BErase32k(), QFlash_BErase64k(), QFlash_ChipErase(), QFlash_SErase4k(), QFlash_Write(), QFlash_WriteSR2(), and QFlash_WriteSR3().
QFlash_WriteSR2()
HAL_StatusTypeDef QFlash_WriteSR2 (uint8_t data)
writes to register 2
Definition at line 631 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_SR2;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit_DMA(&FLASH_QSPI_PORT, &data) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit(&FLASH_QSPI_PORT, &data, QFLASH_DEF_TIMEOUT) != HAL_OK) {
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    QFlash_WaitForWritingComplete();
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, QSpiReadDataAvailable, and W25_W_SR2.
QFlash_WriteSR3()
HAL_StatusTypeDef QFlash_WriteSR3 (uint8_t data)
writes to register 3
Definition at line 676 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_SR3;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_QDMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit_DMA(&FLASH_QSPI_PORT, &data) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit(&FLASH_QSPI_PORT, &data, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    QFlash_WaitForWritingComplete();
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, QSpiReadDataAvailable, and W25_W_SR3.