Da Vinci Firmware: Status and Control Functions
Status and Control Functions
Peripheral Drivers » W25Qxxx QSPI Flash Driver
Functions for controlling chip state (reset, write enable) and reading status registers.
Functions
HAL_StatusTypeDef QFlash_Reset (void)
HAL_StatusTypeDef QFlash_WriteEnable (void)
enables writes
HAL_StatusTypeDef QFlash_WriteDisable (void)
disables writes
HAL_StatusTypeDef QFlash_ReadSR1 (uint8_t *dataptr)
HAL_StatusTypeDef QFlash_ReadSR2 (uint8_t *dataptr)
HAL_StatusTypeDef QFlash_ReadSR3 (uint8_t *dataptr)
HAL_StatusTypeDef QFlash_WriteSR2 (uint8_t data)
writes to register 2
HAL_StatusTypeDef QFlash_WriteSR3 (uint8_t data)
writes to register 3
HAL_StatusTypeDef QFlash_CheckSR1 (void)
HAL_StatusTypeDef QFlash_WaitForWritingComplete (void)
HAL_StatusTypeDef QFlash_PowerDown (void)
HAL_StatusTypeDef QFlash_PowerUp (void)
Detailed Description
Functions for controlling chip state (reset, write enable) and reading status registers.
Function Documentation
QFlash_CheckSR1()
HAL_StatusTypeDef QFlash_CheckSR1 (void)
Definition at line 724 of file z_qflash_W25QXXX.c.
{
    HAL_StatusTypeDef result = HAL_OK;
    uint8_t sr;
    QFlash_ReadSR1(&sr);
//bitwise test of the SR1 content
    if (!((sr & 1)==0)) {  //why flash is busy? It shouldn't
        result=HAL_ERROR;
    } else if (!((sr & 2)==0)) {  //if write_enabled, disable it
        QFlash_WriteDisable();
        HAL_Delay(1);
        QFlash_ReadSR1(&sr);
        if (!((sr & 2)==0)){ //why flash is still writeable? It shouldn't
            result=HAL_ERROR;
        }
    }
    return result;
}
References HAL_ERROR, HAL_OK, QFlash_ReadSR1(), and QFlash_WriteDisable().
QFlash_PowerDown()
HAL_StatusTypeDef QFlash_PowerDown (void)
Definition at line 1081 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    sCommand.Instruction    = W25_POWERDOWN;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QSpiAvailable, and W25_POWERDOWN.
QFlash_PowerUp()
HAL_StatusTypeDef QFlash_PowerUp (void)
Definition at line 1112 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    if (QFlash_WaitForWritingComplete())
        return HAL_ERROR;
    sCommand.Instruction    = W25_POWERUP_ID;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QSpiAvailable, and W25_POWERUP_ID.
QFlash_ReadSR1()
HAL_StatusTypeDef QFlash_ReadSR1 (uint8_t * dataptr)
Definition at line 502 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_R_SR1;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_R_SR1.
Referenced by QFlash_CheckSR1().
QFlash_ReadSR2()
HAL_StatusTypeDef QFlash_ReadSR2 (uint8_t * dataptr)
Definition at line 545 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_R_SR2;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_R_SR2.
QFlash_ReadSR3()
HAL_StatusTypeDef QFlash_ReadSR3 (uint8_t * dataptr)
Definition at line 589 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_R_SR3;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive_DMA(&FLASH_QSPI_PORT, dataptr) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
    QFlash_WaitForDataAvailable(0);
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Receive(&FLASH_QSPI_PORT, dataptr, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForDataAvailable(), QSpiAvailable, QSpiReadDataAvailable, and W25_R_SR3.
QFlash_Reset()
HAL_StatusTypeDef QFlash_Reset (void)
Definition at line 129 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    // send a "reset enable" command
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction = W25_RESET_EN;
    sCommand.AddressMode = QSPI_ADDRESS_NONE;
    sCommand.DataMode = QSPI_DATA_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    HAL_Delay(1);                                   // 30us needed by resetting
    // send a "reset" command
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction = W25_RESET;
    sCommand.AddressMode = QSPI_ADDRESS_NONE;
    sCommand.DataMode = QSPI_DATA_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    HAL_Delay(1);                                   // 30us needed by resetting
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QSpiAvailable, W25_RESET, and W25_RESET_EN.
Referenced by QFlash_Init().
QFlash_WaitForWritingComplete()
HAL_StatusTypeDef QFlash_WaitForWritingComplete (void)
Definition at line 762 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
/* using HAL_QSPI_AutoPolling()*/
QSPI_AutoPollingTypeDef sConfig;
QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction = W25_R_SR1;
    sCommand.AddressMode = QSPI_ADDRESS_NONE;
    sCommand.DataMode = QSPI_DATA_1_LINE;
    sConfig.Mask = SR1_BIT_BSY;
    sConfig.Match = 0;
    sConfig.MatchMode = QSPI_MATCH_MODE_AND;
    sConfig.StatusBytesSize = 1;
    sConfig.Interval = 0x10;
    sConfig.AutomaticStop = QSPI_AUTOMATIC_STOP_ENABLE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_AutoPolling(&FLASH_QSPI_PORT, &sCommand, &sConfig, QFLASH_BSY_TIMEOUT) != HAL_OK) {
        return HAL_ERROR;
    }
/* alternative implementation "SPI style"
 * looping, directly  reading Status Register 1
 * until Busy flag resets
 * (k just count loops)
 */
/*
    uint8_t sr;
    uint32_t k=0;
    do {
        sr=QFlash_ReadSR1();
        sr=(sr & 1);
        k+=1;
    }   while (sr);
*/
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_BSY_TIMEOUT, QFlash_DefaultCmd(), QSpiAvailable, SR1_BIT_BSY, and W25_R_SR1.
Referenced by QFlash_BErase32k(), QFlash_BErase64k(), QFlash_ChipErase(), QFlash_PowerDown(), QFlash_PowerUp(), QFlash_SErase4k(), QFlash_Write(), QFlash_WriteSR2(), and QFlash_WriteSR3().
QFlash_WriteDisable()
HAL_StatusTypeDef QFlash_WriteDisable (void)
disables writes
Definition at line 475 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_DISABLE;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QSpiAvailable, and W25_W_DISABLE.
Referenced by QFlash_CheckSR1().
QFlash_WriteEnable()
HAL_StatusTypeDef QFlash_WriteEnable (void)
enables writes
Definition at line 425 of file z_qflash_W25QXXX.c.
{
QSPI_CommandTypeDef sCommand = {0};
//Send a "Write Enable" command
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_ENABLE;
    sCommand.DataMode       = QSPI_DATA_NONE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
#endif //EXT_FLASH_QSPI_DMA_MODE
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
/*
//Wait for Write Enable bit set
    QSPI_AutoPollingTypeDef sConfig;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction = W25_R_SR1;
    sCommand.DataMode = QSPI_DATA_1_LINE;
    sCommand.AddressMode = QSPI_ADDRESS_NONE;
    sConfig.Mask = SR1_BIT_WEL;
    sConfig.Match = 2;
    sConfig.MatchMode = QSPI_MATCH_MODE_AND;
    sConfig.StatusBytesSize = 1;
    sConfig.Interval = 0x10;
    sConfig.AutomaticStop = QSPI_AUTOMATIC_STOP_ENABLE;
    if (HAL_QSPI_AutoPolling(&FLASH_QSPI_PORT, &sCommand, &sConfig, QFLASH_BSY_TIMEOUT) != HAL_OK) {
        return HAL_ERROR;
    }
*/
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QSpiAvailable, and W25_W_ENABLE.
Referenced by QFlash_BErase32k(), QFlash_BErase64k(), QFlash_ChipErase(), QFlash_SErase4k(), QFlash_Write(), QFlash_WriteSR2(), and QFlash_WriteSR3().
QFlash_WriteSR2()
HAL_StatusTypeDef QFlash_WriteSR2 (uint8_t data)
writes to register 2
Definition at line 631 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_SR2;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_DMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit_DMA(&FLASH_QSPI_PORT, &data) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit(&FLASH_QSPI_PORT, &data, QFLASH_DEF_TIMEOUT) != HAL_OK) {
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    QFlash_WaitForWritingComplete();
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, QSpiReadDataAvailable, and W25_W_SR2.
QFlash_WriteSR3()
HAL_StatusTypeDef QFlash_WriteSR3 (uint8_t data)
writes to register 3
Definition at line 676 of file z_qflash_W25QXXX.c.
{
    QSPI_CommandTypeDef sCommand = {0};
    if (QFlash_WriteEnable())
        return HAL_ERROR;
    QFlash_DefaultCmd(&sCommand);
    sCommand.Instruction    = W25_W_SR3;
    sCommand.DataMode       = QSPI_DATA_1_LINE;
    sCommand.AddressMode    = QSPI_ADDRESS_NONE;
    sCommand.AddressSize    = QSPI_ADDRESS_NONE;
    sCommand.Address        = 0x0;
    sCommand.NbData         = 1;
#ifdef EXT_FLASH_QSPI_QDMA_MODE
    while (!QSpiAvailable) {};  // waiting for a free QSPI port.
    QSpiAvailable=0;            //set QSPI busy
    QSpiReadDataAvailable=0;    //set data read unavailable yet
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit_DMA(&FLASH_QSPI_PORT, &data) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#else
    if (HAL_QSPI_Command(&FLASH_QSPI_PORT, &sCommand, QFLASH_DEF_TIMEOUT) != HAL_OK) {  //Send command
        return HAL_ERROR;
    }
    if (HAL_QSPI_Transmit(&FLASH_QSPI_PORT, &data, QFLASH_DEF_TIMEOUT) != HAL_OK) { // Receive data
        return HAL_ERROR;
    }
#endif //EXT_FLASH_QSPI_DMA_MODE
    QFlash_WaitForWritingComplete();
    return HAL_OK;
}
References FLASH_QSPI_PORT, HAL_ERROR, HAL_OK, QFLASH_DEF_TIMEOUT, QFlash_DefaultCmd(), QFlash_WaitForWritingComplete(), QFlash_WriteEnable(), QSpiAvailable, QSpiReadDataAvailable, and W25_W_SR3.