Da Vinci Firmware: LSM6DSO32_Sensitivity
LSM6DSO32_Sensitivity
Peripheral Drivers » "LSM6DSO32 IMU Driver"
These functions convert raw-data into engineering units.
Functions
float_t lsm6dso32_from_fs4_to_mg (int16_t lsb)
float_t lsm6dso32_from_fs8_to_mg (int16_t lsb)
float_t lsm6dso32_from_fs16_to_mg (int16_t lsb)
float_t lsm6dso32_from_fs32_to_mg (int16_t lsb)
float_t lsm6dso32_from_fs125_to_mdps (int16_t lsb)
float_t lsm6dso32_from_fs250_to_mdps (int16_t lsb)
float_t lsm6dso32_from_fs500_to_mdps (int16_t lsb)
float_t lsm6dso32_from_fs1000_to_mdps (int16_t lsb)
float_t lsm6dso32_from_fs2000_to_mdps (int16_t lsb)
float_t lsm6dso32_from_lsb_to_celsius (int16_t lsb)
float_t lsm6dso32_from_lsb_to_nsec (int16_t lsb)
Detailed Description
These functions convert raw-data into engineering units.
Function Documentation
lsm6dso32_from_fs1000_to_mdps()
float_t lsm6dso32_from_fs1000_to_mdps (int16_t lsb)
Definition at line 132 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 35.0f;
}
lsm6dso32_from_fs125_to_mdps()
float_t lsm6dso32_from_fs125_to_mdps (int16_t lsb)
Definition at line 117 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 4.375f;
}
lsm6dso32_from_fs16_to_mg()
float_t lsm6dso32_from_fs16_to_mg (int16_t lsb)
Definition at line 107 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 0.488f;
}
Referenced by calibrateIMU(), and StartSensor_Task().
lsm6dso32_from_fs2000_to_mdps()
float_t lsm6dso32_from_fs2000_to_mdps (int16_t lsb)
Definition at line 137 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 70.0f;
}
Referenced by calibrateIMU(), and StartSensor_Task().
lsm6dso32_from_fs250_to_mdps()
float_t lsm6dso32_from_fs250_to_mdps (int16_t lsb)
Definition at line 122 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 8.75f;
}
lsm6dso32_from_fs32_to_mg()
float_t lsm6dso32_from_fs32_to_mg (int16_t lsb)
Definition at line 112 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 0.976f;
}
lsm6dso32_from_fs4_to_mg()
float_t lsm6dso32_from_fs4_to_mg (int16_t lsb)
Definition at line 97 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 0.122f;
}
lsm6dso32_from_fs500_to_mdps()
float_t lsm6dso32_from_fs500_to_mdps (int16_t lsb)
Definition at line 127 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 17.50f;
}
lsm6dso32_from_fs8_to_mg()
float_t lsm6dso32_from_fs8_to_mg (int16_t lsb)
Definition at line 102 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb) * 0.244f;
}
lsm6dso32_from_lsb_to_celsius()
float_t lsm6dso32_from_lsb_to_celsius (int16_t lsb)
Definition at line 142 of file lsm6dso32_reg.c.
{
  return (((float_t)lsb / 256.0f) + 25.0f);
}
Referenced by calibrateIMU().
lsm6dso32_from_lsb_to_nsec()
float_t lsm6dso32_from_lsb_to_nsec (int16_t lsb)
Definition at line 147 of file lsm6dso32_reg.c.
{
  return ((float_t)lsb * 25000.0f);
}