Da Vinci Firmware: LSM6DSO32_DEN_functionality
LSM6DSO32_DEN_functionality
Peripheral Drivers » "LSM6DSO32 IMU Driver"
This section groups all the functions concerning DEN functionality.
Functions
int32_t lsm6dso32_den_mode_set (stmdev_ctx_t *ctx, lsm6dso32_den_mode_t val)
DEN functionality marking mode.[set].
int32_t lsm6dso32_den_mode_get (stmdev_ctx_t *ctx, lsm6dso32_den_mode_t *val)
DEN functionality marking mode.[get].
int32_t lsm6dso32_den_polarity_set (stmdev_ctx_t *ctx, lsm6dso32_den_lh_t val)
DEN active level configuration.[set].
int32_t lsm6dso32_den_polarity_get (stmdev_ctx_t *ctx, lsm6dso32_den_lh_t *val)
DEN active level configuration.[get].
int32_t lsm6dso32_den_enable_set (stmdev_ctx_t *ctx, lsm6dso32_den_xl_g_t val)
DEN enable.[set].
int32_t lsm6dso32_den_enable_get (stmdev_ctx_t *ctx, lsm6dso32_den_xl_g_t *val)
DEN enable.[get].
int32_t lsm6dso32_den_mark_axis_x_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of X-axis.[set].
int32_t lsm6dso32_den_mark_axis_x_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of X-axis.[get].
int32_t lsm6dso32_den_mark_axis_y_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of Y-axis.[set].
int32_t lsm6dso32_den_mark_axis_y_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of Y-axis.[get].
int32_t lsm6dso32_den_mark_axis_z_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of Z-axis.[set].
int32_t lsm6dso32_den_mark_axis_z_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of Z-axis.[get].
Detailed Description
This section groups all the functions concerning DEN functionality.
Function Documentation
lsm6dso32_den_enable_get()
int32_t lsm6dso32_den_enable_get (stmdev_ctx_t * ctx, lsm6dso32_den_xl_g_t * val)
DEN enable.[get].
Parameters
ctx read / write interface definitions
val Get the values of den_xl_g in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6762 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  switch (reg.den_xl_g)
  {
    case LSM6DSO32_STAMP_IN_GY_DATA:
      *val = LSM6DSO32_STAMP_IN_GY_DATA;
      break;
    case LSM6DSO32_STAMP_IN_XL_DATA:
      *val = LSM6DSO32_STAMP_IN_XL_DATA;
      break;
    case LSM6DSO32_STAMP_IN_GY_XL_DATA:
      *val = LSM6DSO32_STAMP_IN_GY_XL_DATA;
      break;
    default:
      *val = LSM6DSO32_STAMP_IN_GY_DATA;
      break;
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_xl_g, LSM6DSO32_CTRL9_XL, lsm6dso32_read_reg(), LSM6DSO32_STAMP_IN_GY_DATA, LSM6DSO32_STAMP_IN_GY_XL_DATA, and LSM6DSO32_STAMP_IN_XL_DATA.
lsm6dso32_den_enable_set()
int32_t lsm6dso32_den_enable_set (stmdev_ctx_t * ctx, lsm6dso32_den_xl_g_t val)
DEN enable.[set].
Parameters
ctx read / write interface definitions
val change the values of den_xl_g in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6737 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.den_xl_g = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_xl_g, LSM6DSO32_CTRL9_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_den_mark_axis_x_get()
int32_t lsm6dso32_den_mark_axis_x_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of X-axis.[get].
Parameters
ctx read / write interface definitions
val change the values of den_z in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6824 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  *val = reg.den_z;
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_z, LSM6DSO32_CTRL9_XL, and lsm6dso32_read_reg().
lsm6dso32_den_mark_axis_x_set()
int32_t lsm6dso32_den_mark_axis_x_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of X-axis.[set].
Parameters
ctx read / write interface definitions
val change the values of den_z in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6800 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.den_z = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_z, LSM6DSO32_CTRL9_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_den_mark_axis_y_get()
int32_t lsm6dso32_den_mark_axis_y_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of Y-axis.[get].
Parameters
ctx read / write interface definitions
val change the values of den_y in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6867 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  *val = reg.den_y;
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_y, LSM6DSO32_CTRL9_XL, and lsm6dso32_read_reg().
lsm6dso32_den_mark_axis_y_set()
int32_t lsm6dso32_den_mark_axis_y_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of Y-axis.[set].
Parameters
ctx read / write interface definitions
val change the values of den_y in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6843 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.den_y = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_y, LSM6DSO32_CTRL9_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_den_mark_axis_z_get()
int32_t lsm6dso32_den_mark_axis_z_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of Z-axis.[get].
Parameters
ctx read / write interface definitions
val change the values of den_x in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6910 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  *val = reg.den_x;
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_x, LSM6DSO32_CTRL9_XL, and lsm6dso32_read_reg().
lsm6dso32_den_mark_axis_z_set()
int32_t lsm6dso32_den_mark_axis_z_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of Z-axis.[set].
Parameters
ctx read / write interface definitions
val change the values of den_x in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6886 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.den_x = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_x, LSM6DSO32_CTRL9_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_den_mode_get()
int32_t lsm6dso32_den_mode_get (stmdev_ctx_t * ctx, lsm6dso32_den_mode_t * val)
DEN functionality marking mode.[get].
Parameters
ctx read / write interface definitions
val Get the values of den_mode in reg CTRL6_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6632 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl6_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL6_C, (uint8_t *)&reg, 1);
  switch (reg.den_mode)
  {
    case LSM6DSO32_DEN_DISABLE:
      *val = LSM6DSO32_DEN_DISABLE;
      break;
    case LSM6DSO32_LEVEL_FIFO:
      *val = LSM6DSO32_LEVEL_FIFO;
      break;
    case LSM6DSO32_LEVEL_LETCHED:
      *val = LSM6DSO32_LEVEL_LETCHED;
      break;
    case LSM6DSO32_LEVEL_TRIGGER:
      *val = LSM6DSO32_LEVEL_TRIGGER;
      break;
    case LSM6DSO32_EDGE_TRIGGER:
      *val = LSM6DSO32_EDGE_TRIGGER;
      break;
    default:
      *val = LSM6DSO32_DEN_DISABLE;
      break;
  }
  return ret;
}
References lsm6dso32_ctrl6_c_t::den_mode, LSM6DSO32_CTRL6_C, LSM6DSO32_DEN_DISABLE, LSM6DSO32_EDGE_TRIGGER, LSM6DSO32_LEVEL_FIFO, LSM6DSO32_LEVEL_LETCHED, LSM6DSO32_LEVEL_TRIGGER, and lsm6dso32_read_reg().
lsm6dso32_den_mode_set()
int32_t lsm6dso32_den_mode_set (stmdev_ctx_t * ctx, lsm6dso32_den_mode_t val)
DEN functionality marking mode.[set].
Parameters
ctx read / write interface definitions
val change the values of den_mode in reg CTRL6_C
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6607 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl6_c_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL6_C, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.den_mode = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL6_C, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl6_c_t::den_mode, LSM6DSO32_CTRL6_C, lsm6dso32_read_reg(), and lsm6dso32_write_reg().
lsm6dso32_den_polarity_get()
int32_t lsm6dso32_den_polarity_get (stmdev_ctx_t * ctx, lsm6dso32_den_lh_t * val)
DEN active level configuration.[get].
Parameters
ctx read / write interface definitions
val Get the values of den_lh in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6703 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  switch (reg.den_lh)
  {
    case LSM6DSO32_DEN_ACT_LOW:
      *val = LSM6DSO32_DEN_ACT_LOW;
      break;
    case LSM6DSO32_DEN_ACT_HIGH:
      *val = LSM6DSO32_DEN_ACT_HIGH;
      break;
    default:
      *val = LSM6DSO32_DEN_ACT_LOW;
      break;
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_lh, LSM6DSO32_CTRL9_XL, LSM6DSO32_DEN_ACT_HIGH, LSM6DSO32_DEN_ACT_LOW, and lsm6dso32_read_reg().
lsm6dso32_den_polarity_set()
int32_t lsm6dso32_den_polarity_set (stmdev_ctx_t * ctx, lsm6dso32_den_lh_t val)
DEN active level configuration.[set].
Parameters
ctx read / write interface definitions
val change the values of den_lh in reg CTRL9_XL
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 6678 of file lsm6dso32_reg.c.
{
  lsm6dso32_ctrl9_xl_t reg;
  int32_t ret;
  ret = lsm6dso32_read_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  if (ret == 0)
  {
    reg.den_lh = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_CTRL9_XL, (uint8_t *)&reg, 1);
  }
  return ret;
}
References lsm6dso32_ctrl9_xl_t::den_lh, LSM6DSO32_CTRL9_XL, lsm6dso32_read_reg(), and lsm6dso32_write_reg().