Da Vinci Firmware: LSM6DSO32_finite_state_machine
LSM6DSO32_finite_state_machine
Peripheral Drivers » "LSM6DSO32 6-Axis IMU Driver"
This section groups all the functions that manage the state_machine.
Data Structures
struct lsm6dso32_emb_fsm_enable_t
struct lsm6dso32_fsm_out_t
Enumerations
enum lsm6dso32_fsm_lc_clr_t { LSM6DSO32_LC_NORMAL = 0 , LSM6DSO32_LC_CLEAR = 1 , LSM6DSO32_LC_CLEAR_DONE = 2 }
enum lsm6dso32_fsm_odr_t { LSM6DSO32_ODR_FSM_12Hz5 = 0 , LSM6DSO32_ODR_FSM_26Hz = 1 , LSM6DSO32_ODR_FSM_52Hz = 2 , LSM6DSO32_ODR_FSM_104Hz = 3 }
Functions
int32_t lsm6dso32_long_cnt_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Interrupt status bit for FSM long counter timeout interrupt event.[get].
int32_t lsm6dso32_emb_fsm_en_set (stmdev_ctx_t *ctx, uint8_t val)
Final State Machine global enable.[set].
int32_t lsm6dso32_emb_fsm_en_get (stmdev_ctx_t *ctx, uint8_t *val)
Final State Machine global enable.[get].
int32_t lsm6dso32_fsm_enable_set (stmdev_ctx_t *ctx, lsm6dso32_emb_fsm_enable_t *val)
Final State Machine enable.[set].
int32_t lsm6dso32_fsm_enable_get (stmdev_ctx_t *ctx, lsm6dso32_emb_fsm_enable_t *val)
Final State Machine enable.[get].
int32_t lsm6dso32_long_cnt_set (stmdev_ctx_t *ctx, uint16_t val)
FSM long counter status register. Long counter value is an unsigned integer value (16-bit format).[set].
int32_t lsm6dso32_long_cnt_get (stmdev_ctx_t *ctx, uint16_t *val)
FSM long counter status register. Long counter value is an unsigned integer value (16-bit format).[get].
int32_t lsm6dso32_long_clr_set (stmdev_ctx_t *ctx, lsm6dso32_fsm_lc_clr_t val)
Clear FSM long counter value.[set].
int32_t lsm6dso32_long_clr_get (stmdev_ctx_t *ctx, lsm6dso32_fsm_lc_clr_t *val)
Clear FSM long counter value.[get].
int32_t lsm6dso32_fsm_out_get (stmdev_ctx_t *ctx, lsm6dso32_fsm_out_t *val)
FSM output registers[get].
int32_t lsm6dso32_fsm_data_rate_set (stmdev_ctx_t *ctx, lsm6dso32_fsm_odr_t val)
Finite State Machine ODR configuration.[set].
int32_t lsm6dso32_fsm_data_rate_get (stmdev_ctx_t *ctx, lsm6dso32_fsm_odr_t *val)
Finite State Machine ODR configuration.[get].
int32_t lsm6dso32_fsm_init_set (stmdev_ctx_t *ctx, uint8_t val)
FSM initialization request.[set].
int32_t lsm6dso32_fsm_init_get (stmdev_ctx_t *ctx, uint8_t *val)
FSM initialization request.[get].
int32_t lsm6dso32_long_cnt_int_value_set (stmdev_ctx_t *ctx, uint16_t val)
FSM long counter timeout register (r/w). The long counter timeout value is an unsigned integer value (16-bit format). When the long counter value reached this value, the FSM generates an interrupt.[set].
int32_t lsm6dso32_long_cnt_int_value_get (stmdev_ctx_t *ctx, uint16_t *val)
FSM long counter timeout register (r/w). The long counter timeout value is an unsigned integer value (16-bit format). When the long counter value reached this value, the FSM generates an interrupt.[get].
int32_t lsm6dso32_fsm_number_of_programs_set (stmdev_ctx_t *ctx, uint8_t *buff)
FSM number of programs register.[set].
int32_t lsm6dso32_fsm_number_of_programs_get (stmdev_ctx_t *ctx, uint8_t *buff)
FSM number of programs register.[get].
int32_t lsm6dso32_fsm_start_address_set (stmdev_ctx_t *ctx, uint16_t val)
FSM start address register (r/w). First available address is 0x033C.[set].
int32_t lsm6dso32_fsm_start_address_get (stmdev_ctx_t *ctx, uint16_t *val)
FSM start address register (r/w). First available address is 0x033C.[get].
Detailed Description
This section groups all the functions that manage the state_machine.
Enumeration Type Documentation
lsm6dso32_fsm_lc_clr_t
enum lsm6dso32_fsm_lc_clr_t
Enumerator
LSM6DSO32_LC_NORMAL
LSM6DSO32_LC_CLEAR
LSM6DSO32_LC_CLEAR_DONE
Definition at line 3686 of file lsm6dso32_reg.h.
{
  LSM6DSO32_LC_NORMAL     = 0,
  LSM6DSO32_LC_CLEAR      = 1,
  LSM6DSO32_LC_CLEAR_DONE = 2,
} lsm6dso32_fsm_lc_clr_t;
lsm6dso32_fsm_odr_t
enum lsm6dso32_fsm_odr_t
Enumerator
LSM6DSO32_ODR_FSM_12Hz5
LSM6DSO32_ODR_FSM_26Hz
LSM6DSO32_ODR_FSM_52Hz
LSM6DSO32_ODR_FSM_104Hz
Definition at line 3719 of file lsm6dso32_reg.h.
{
  LSM6DSO32_ODR_FSM_12Hz5 = 0,
  LSM6DSO32_ODR_FSM_26Hz  = 1,
  LSM6DSO32_ODR_FSM_52Hz  = 2,
  LSM6DSO32_ODR_FSM_104Hz = 3,
} lsm6dso32_fsm_odr_t;
Function Documentation
lsm6dso32_emb_fsm_en_get()
int32_t lsm6dso32_emb_fsm_en_get (stmdev_ctx_t * ctx, uint8_t * val)
Final State Machine global enable.[get].
Parameters
ctx read / write interface definitions
uint8_t *: return the values of fsm_en in reg EMB_FUNC_EN_B
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8238 of file lsm6dso32_reg.c.
{
  int32_t ret;
  lsm6dso32_emb_func_en_b_t reg;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.fsm_en;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_en_b_t::fsm_en, LSM6DSO32_EMB_FUNC_EN_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, and lsm6dso32_write_reg().
lsm6dso32_emb_fsm_en_set()
int32_t lsm6dso32_emb_fsm_en_set (stmdev_ctx_t * ctx, uint8_t val)
Final State Machine global enable.[set].
Parameters
ctx read / write interface definitions
val change the values of fsm_en in reg EMB_FUNC_EN_B
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8202 of file lsm6dso32_reg.c.
{
  int32_t ret;
  lsm6dso32_emb_func_en_b_t reg;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg.fsm_en = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_en_b_t::fsm_en, LSM6DSO32_EMB_FUNC_EN_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, and lsm6dso32_write_reg().
lsm6dso32_fsm_data_rate_get()
int32_t lsm6dso32_fsm_data_rate_get (stmdev_ctx_t * ctx, lsm6dso32_fsm_odr_t * val)
Finite State Machine ODR configuration.[get].
Parameters
ctx read / write interface definitions
val Get the values of fsm_odr in reg EMB_FUNC_ODR_CFG_B
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8598 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_odr_cfg_b_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_ODR_CFG_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    switch (reg.fsm_odr)
    {
      case LSM6DSO32_ODR_FSM_12Hz5:
        *val = LSM6DSO32_ODR_FSM_12Hz5;
        break;
      case LSM6DSO32_ODR_FSM_26Hz:
        *val = LSM6DSO32_ODR_FSM_26Hz;
        break;
      case LSM6DSO32_ODR_FSM_52Hz:
        *val = LSM6DSO32_ODR_FSM_52Hz;
        break;
      case LSM6DSO32_ODR_FSM_104Hz:
        *val = LSM6DSO32_ODR_FSM_104Hz;
        break;
      default:
        *val = LSM6DSO32_ODR_FSM_12Hz5;
        break;
    }
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_odr_cfg_b_t::fsm_odr, LSM6DSO32_EMB_FUNC_ODR_CFG_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), LSM6DSO32_ODR_FSM_104Hz, LSM6DSO32_ODR_FSM_12Hz5, LSM6DSO32_ODR_FSM_26Hz, LSM6DSO32_ODR_FSM_52Hz, lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_fsm_data_rate_set()
int32_t lsm6dso32_fsm_data_rate_set (stmdev_ctx_t * ctx, lsm6dso32_fsm_odr_t val)
Finite State Machine ODR configuration.[set].
Parameters
ctx read / write interface definitions
val change the values of fsm_odr in reg EMB_FUNC_ODR_CFG_B
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8559 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_odr_cfg_b_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_ODR_CFG_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg.not_used_01 = 3; /* set default values */
    reg.not_used_02 = 1; /* set default values */
    reg.fsm_odr = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_ODR_CFG_B,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_odr_cfg_b_t::fsm_odr, LSM6DSO32_EMB_FUNC_ODR_CFG_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_write_reg(), lsm6dso32_emb_func_odr_cfg_b_t::not_used_01, and lsm6dso32_emb_func_odr_cfg_b_t::not_used_02.
lsm6dso32_fsm_enable_get()
int32_t lsm6dso32_fsm_enable_get (stmdev_ctx_t * ctx, lsm6dso32_emb_fsm_enable_t * val)
Final State Machine enable.[get].
Parameters
ctx read / write interface definitions
val union of registers from FSM_ENABLE_A to FSM_ENABLE_B
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8348 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FSM_ENABLE_A, (uint8_t *) val,
                             2);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_ENABLE_A, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_fsm_enable_set()
int32_t lsm6dso32_fsm_enable_set (stmdev_ctx_t * ctx, lsm6dso32_emb_fsm_enable_t * val)
Final State Machine enable.[set].
Parameters
ctx read / write interface definitions
val union of registers from FSM_ENABLE_A to FSM_ENABLE_B
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8274 of file lsm6dso32_reg.c.
{
  int32_t ret;
  lsm6dso32_emb_func_en_b_t reg;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_FSM_ENABLE_A,
                              (uint8_t *)&val->fsm_enable_a, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_FSM_ENABLE_B,
                              (uint8_t *)&val->fsm_enable_b, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    if ((val->fsm_enable_a.fsm1_en   |
         val->fsm_enable_a.fsm2_en  |
         val->fsm_enable_a.fsm3_en  |
         val->fsm_enable_a.fsm4_en  |
         val->fsm_enable_a.fsm5_en  |
         val->fsm_enable_a.fsm6_en  |
         val->fsm_enable_a.fsm7_en  |
         val->fsm_enable_a.fsm8_en  |
         val->fsm_enable_b.fsm9_en  |
         val->fsm_enable_b.fsm10_en  |
         val->fsm_enable_b.fsm11_en  |
         val->fsm_enable_b.fsm12_en  |
         val->fsm_enable_b.fsm13_en  |
         val->fsm_enable_b.fsm14_en  |
         val->fsm_enable_b.fsm15_en  |
         val->fsm_enable_b.fsm16_en)
        != PROPERTY_DISABLE)
    {
      reg.fsm_en = PROPERTY_ENABLE;
    }
    else
    {
      reg.fsm_en = PROPERTY_DISABLE;
    }
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_EN_B,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_fsm_enable_b_t::fsm10_en, lsm6dso32_fsm_enable_b_t::fsm11_en, lsm6dso32_fsm_enable_b_t::fsm12_en, lsm6dso32_fsm_enable_b_t::fsm13_en, lsm6dso32_fsm_enable_b_t::fsm14_en, lsm6dso32_fsm_enable_b_t::fsm15_en, lsm6dso32_fsm_enable_b_t::fsm16_en, lsm6dso32_fsm_enable_a_t::fsm1_en, lsm6dso32_fsm_enable_a_t::fsm2_en, lsm6dso32_fsm_enable_a_t::fsm3_en, lsm6dso32_fsm_enable_a_t::fsm4_en, lsm6dso32_fsm_enable_a_t::fsm5_en, lsm6dso32_fsm_enable_a_t::fsm6_en, lsm6dso32_fsm_enable_a_t::fsm7_en, lsm6dso32_fsm_enable_a_t::fsm8_en, lsm6dso32_fsm_enable_b_t::fsm9_en, lsm6dso32_emb_func_en_b_t::fsm_en, lsm6dso32_emb_fsm_enable_t::fsm_enable_a, lsm6dso32_emb_fsm_enable_t::fsm_enable_b, LSM6DSO32_EMB_FUNC_EN_B, LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_ENABLE_A, LSM6DSO32_FSM_ENABLE_B, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, lsm6dso32_write_reg(), PROPERTY_DISABLE, and PROPERTY_ENABLE.
lsm6dso32_fsm_init_get()
int32_t lsm6dso32_fsm_init_get (stmdev_ctx_t * ctx, uint8_t * val)
FSM initialization request.[get].
Parameters
ctx read / write interface definitions
val change the values of fsm_init in reg FSM_INIT
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8687 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_init_b_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_INIT_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.fsm_init;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_init_b_t::fsm_init, LSM6DSO32_EMB_FUNC_INIT_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_fsm_init_set()
int32_t lsm6dso32_fsm_init_set (stmdev_ctx_t * ctx, uint8_t val)
FSM initialization request.[set].
Parameters
ctx read / write interface definitions
val change the values of fsm_init in reg FSM_INIT
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8651 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_init_b_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_INIT_B,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg.fsm_init = val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_EMB_FUNC_INIT_B,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_init_b_t::fsm_init, LSM6DSO32_EMB_FUNC_INIT_B, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, and lsm6dso32_write_reg().
lsm6dso32_fsm_number_of_programs_get()
int32_t lsm6dso32_fsm_number_of_programs_get (stmdev_ctx_t * ctx, uint8_t * buff)
FSM number of programs register.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8797 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_FSM_PROGRAMS, buff);
  return ret;
}
References LSM6DSO32_FSM_PROGRAMS, and lsm6dso32_ln_pg_read_byte().
lsm6dso32_fsm_number_of_programs_set()
int32_t lsm6dso32_fsm_number_of_programs_set (stmdev_ctx_t * ctx, uint8_t * buff)
FSM number of programs register.[set].
Parameters
ctx read / write interface definitions
buff buffer that contains data to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8779 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_FSM_PROGRAMS, buff);
  return ret;
}
References LSM6DSO32_FSM_PROGRAMS, and lsm6dso32_ln_pg_write_byte().
lsm6dso32_fsm_out_get()
int32_t lsm6dso32_fsm_out_get (stmdev_ctx_t * ctx, lsm6dso32_fsm_out_t * val)
FSM output registers[get].
Parameters
ctx read / write interface definitions
val struct of registers from FSM_OUTS1 to FSM_OUTS16
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8530 of file lsm6dso32_reg.c.
{
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FSM_OUTS1, (uint8_t *) &val,
                             16);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_OUTS1, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_fsm_start_address_get()
int32_t lsm6dso32_fsm_start_address_get (stmdev_ctx_t * ctx, uint16_t * val)
FSM start address register (r/w). First available address is 0x033C.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8846 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_FSM_START_ADD_L,
                                  &buff[0]);
  if (ret == 0)
  {
    ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_FSM_START_ADD_H,
                                    &buff[1]);
    *val = buff[1];
    *val = (*val * 256U) +  buff[0];
  }
  return ret;
}
References LSM6DSO32_FSM_START_ADD_H, LSM6DSO32_FSM_START_ADD_L, and lsm6dso32_ln_pg_read_byte().
lsm6dso32_fsm_start_address_set()
int32_t lsm6dso32_fsm_start_address_set (stmdev_ctx_t * ctx, uint16_t val)
FSM start address register (r/w). First available address is 0x033C.[set].
Parameters
ctx read / write interface definitions
buff buffer that contains data to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8816 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  buff[1] = (uint8_t)(val / 256U);
  buff[0] = (uint8_t)(val - (buff[1] * 256U));
  ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_FSM_START_ADD_L,
                                   &buff[0]);
  if (ret == 0)
  {
    ;
    ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_FSM_START_ADD_H,
                                     &buff[1]);
  }
  return ret;
}
References LSM6DSO32_FSM_START_ADD_H, LSM6DSO32_FSM_START_ADD_L, and lsm6dso32_ln_pg_write_byte().
lsm6dso32_long_clr_get()
int32_t lsm6dso32_long_clr_get (stmdev_ctx_t * ctx, lsm6dso32_fsm_lc_clr_t * val)
Clear FSM long counter value.[get].
Parameters
ctx read / write interface definitions
val Get the values of fsm_lc_clr in reg FSM_LONG_COUNTER_CLEAR
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8478 of file lsm6dso32_reg.c.
{
  lsm6dso32_fsm_long_counter_clear_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FSM_LONG_COUNTER_CLEAR,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    switch (reg.fsm_lc_clr)
    {
      case LSM6DSO32_LC_NORMAL:
        *val = LSM6DSO32_LC_NORMAL;
        break;
      case LSM6DSO32_LC_CLEAR:
        *val = LSM6DSO32_LC_CLEAR;
        break;
      case LSM6DSO32_LC_CLEAR_DONE:
        *val = LSM6DSO32_LC_CLEAR_DONE;
        break;
      default:
        *val = LSM6DSO32_LC_NORMAL;
        break;
    }
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_fsm_long_counter_clear_t::fsm_lc_clr, LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_LONG_COUNTER_CLEAR, LSM6DSO32_LC_CLEAR, LSM6DSO32_LC_CLEAR_DONE, LSM6DSO32_LC_NORMAL, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_long_clr_set()
int32_t lsm6dso32_long_clr_set (stmdev_ctx_t * ctx, lsm6dso32_fsm_lc_clr_t val)
Clear FSM long counter value.[set].
Parameters
ctx read / write interface definitions
val change the values of fsm_lc_clr in reg FSM_LONG_COUNTER_CLEAR
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8440 of file lsm6dso32_reg.c.
{
  lsm6dso32_fsm_long_counter_clear_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FSM_LONG_COUNTER_CLEAR,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    reg. fsm_lc_clr = (uint8_t)val;
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_FSM_LONG_COUNTER_CLEAR,
                              (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_LONG_COUNTER_CLEAR, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), LSM6DSO32_USER_BANK, and lsm6dso32_write_reg().
lsm6dso32_long_cnt_flag_data_ready_get()
int32_t lsm6dso32_long_cnt_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Interrupt status bit for FSM long counter timeout interrupt event.[get].
Parameters
ctx read / write interface definitions
val change the values of is_fsm_lc in reg EMB_FUNC_STATUS
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8171 of file lsm6dso32_reg.c.
{
  lsm6dso32_emb_func_status_t reg;
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_EMB_FUNC_STATUS,
                             (uint8_t *)&reg, 1);
  }
  if (ret == 0)
  {
    *val = reg.is_fsm_lc;
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References lsm6dso32_emb_func_status_t::is_fsm_lc, LSM6DSO32_EMB_FUNC_STATUS, LSM6DSO32_EMBEDDED_FUNC_BANK, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_long_cnt_get()
int32_t lsm6dso32_long_cnt_get (stmdev_ctx_t * ctx, uint16_t * val)
FSM long counter status register. Long counter value is an unsigned integer value (16-bit format).[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8409 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_read_reg(ctx, LSM6DSO32_FSM_LONG_COUNTER_L, buff, 2);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
    *val = buff[1];
    *val = (*val * 256U) +  buff[0];
  }
  return ret;
}
References LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_LONG_COUNTER_L, lsm6dso32_mem_bank_set(), lsm6dso32_read_reg(), and LSM6DSO32_USER_BANK.
lsm6dso32_long_cnt_int_value_get()
int32_t lsm6dso32_long_cnt_int_value_get (stmdev_ctx_t * ctx, uint16_t * val)
FSM long counter timeout register (r/w). The long counter timeout value is an unsigned integer value (16-bit format). When the long counter value reached this value, the FSM generates an interrupt.[get].
Parameters
ctx read / write interface definitions
buff buffer that stores data read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8751 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_FSM_LC_TIMEOUT_L,
                                  &buff[0]);
  if (ret == 0)
  {
    ret = lsm6dso32_ln_pg_read_byte(ctx, LSM6DSO32_FSM_LC_TIMEOUT_H,
                                    &buff[1]);
    *val = buff[1];
    *val = (*val * 256U) +  buff[0];
  }
  return ret;
}
References LSM6DSO32_FSM_LC_TIMEOUT_H, LSM6DSO32_FSM_LC_TIMEOUT_L, and lsm6dso32_ln_pg_read_byte().
lsm6dso32_long_cnt_int_value_set()
int32_t lsm6dso32_long_cnt_int_value_set (stmdev_ctx_t * ctx, uint16_t val)
FSM long counter timeout register (r/w). The long counter timeout value is an unsigned integer value (16-bit format). When the long counter value reached this value, the FSM generates an interrupt.[set].
Parameters
ctx read / write interface definitions
buff buffer that contains data to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8720 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  buff[1] = (uint8_t)(val / 256U);
  buff[0] = (uint8_t)(val - (buff[1] * 256U));
  ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_FSM_LC_TIMEOUT_L,
                                   &buff[0]);
  if (ret == 0)
  {
    ret = lsm6dso32_ln_pg_write_byte(ctx, LSM6DSO32_FSM_LC_TIMEOUT_H,
                                     &buff[1]);
  }
  return ret;
}
References LSM6DSO32_FSM_LC_TIMEOUT_H, LSM6DSO32_FSM_LC_TIMEOUT_L, and lsm6dso32_ln_pg_write_byte().
lsm6dso32_long_cnt_set()
int32_t lsm6dso32_long_cnt_set (stmdev_ctx_t * ctx, uint16_t val)
FSM long counter status register. Long counter value is an unsigned integer value (16-bit format).[set].
Parameters
ctx read / write interface definitions
buff buffer that contains data to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 8378 of file lsm6dso32_reg.c.
{
  uint8_t buff[2];
  int32_t ret;
  buff[1] = (uint8_t)(val / 256U);
  buff[0] = (uint8_t)(val - (buff[1] * 256U));
  ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_EMBEDDED_FUNC_BANK);
  if (ret == 0)
  {
    ret = lsm6dso32_write_reg(ctx, LSM6DSO32_FSM_LONG_COUNTER_L, buff, 2);
  }
  if (ret == 0)
  {
    ret = lsm6dso32_mem_bank_set(ctx, LSM6DSO32_USER_BANK);
  }
  return ret;
}
References LSM6DSO32_EMBEDDED_FUNC_BANK, LSM6DSO32_FSM_LONG_COUNTER_L, lsm6dso32_mem_bank_set(), LSM6DSO32_USER_BANK, and lsm6dso32_write_reg().