Da Vinci Firmware: Davinci_2/Core/Inc/main.h File Reference
main.h File Reference
: Header for main.c file. This file contains the common defines of the application.
Functions
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
QSPI_HandleTypeDef hqspi
HAL QSPI handle for the external flash memory.
SPI_HandleTypeDef hspi2
HAL SPI handle for Sensor Bus 1 (e.g., IMU, Baro).
SPI_HandleTypeDef hspi3
HAL SPI handle for Sensor Bus 2 (e.g., secondary sensors).
TIM_HandleTypeDef htim15
HAL Timer handle for the buzzer PWM.
uint8_t mainp
Status flag for the main parachute pyro channel.
uint8_t drogue
Status flag for the drogue parachute pyro channel.
bool flag_kf
RTOS event flag to trigger the Kalman Filter task.
bool flag_MPC
RTOS event flag to trigger the MPC task.
bool flag_flash
RTOS event flag to trigger the data logging task.
bool flag_attitude
RTOS event flag to trigger the attitude estimation task.
Detailed Description
: Header for main.c file. This file contains the common defines of the application.
Author
Francesco Abate, Tommaso Gualtierotti
Attention
Copyright (c) 2025 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
— Doxygen Main Page and Groups —
/**
Definition in file main.h.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 2042 of file main.c.
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
Referenced by buzzer_init(), HAL_FDCAN_MspInit(), HAL_PCD_MspInit(), HAL_QSPI_MspInit(), HAL_SPI_MspInit(), HAL_UART_MspInit(), main(), MX_ADC1_Init(), MX_ADC2_Init(), MX_ADC3_Init(), MX_FDCAN1_Init(), MX_QUADSPI_Init(), MX_SPI1_Init(), MX_SPI2_Init(), MX_SPI3_Init(), MX_TIM13_Init(), MX_TIM15_Init(), MX_TIM2_Init(), MX_TIM6_Init(), MX_TIM7_Init(), MX_UART4_Init(), MX_USART1_UART_Init(), MX_USB_OTG_FS_PCD_Init(), PeriphCommonClock_Config(), StartReceiveVel_Task(), and SystemClock_Config().
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM2 GPIO Configuration PA2 ---—> TIM2_CH3
TIM15 GPIO Configuration PE6 ---—> TIM15_CH2
Definition at line 739 of file stm32h7xx_hal_msp.c.
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim->Instance==TIM2)
  {
    /* USER CODE BEGIN TIM2_MspPostInit 0 */
    /* USER CODE END TIM2_MspPostInit 0 */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = TIM2_CH3_PWM_AIRBRAKES_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM2;
    HAL_GPIO_Init(TIM2_CH3_PWM_AIRBRAKES_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN TIM2_MspPostInit 1 */
    /* USER CODE END TIM2_MspPostInit 1 */
  }
  else if(htim->Instance==TIM15)
  {
    /* USER CODE BEGIN TIM15_MspPostInit 0 */
    /* USER CODE END TIM15_MspPostInit 0 */
    __HAL_RCC_GPIOE_CLK_ENABLE();
    GPIO_InitStruct.Pin = TIM15_CH2_BUZZER_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF4_TIM15;
    HAL_GPIO_Init(TIM15_CH2_BUZZER_GPIO_Port, &GPIO_InitStruct);
    /* USER CODE BEGIN TIM15_MspPostInit 1 */
    /* USER CODE END TIM15_MspPostInit 1 */
  }
}
Referenced by MX_TIM15_Init(), and MX_TIM2_Init().